---
title: "Appendix"
output: 
  html_document:
    toc: true
    toc_float: true
date: "`r Sys.time()`"
params:
  mode: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = here::here())
```

```{r}
if(is.null(params$mode)) {
  source("packages.R")
  devtools::load_all()
}

# load data from targets pipeline
targets::tar_load(config)
targets::tar_load(clean_data)
targets::tar_load(figmap_leep_timeseries)
targets::tar_load(figmap_leep_cone)
targets::tar_load(figmap_leep_stackbar)
targets::tar_load(figmap_leep_diffbar)

# palettes
subpalettes = create_subpalettes(figmap_leep_timeseries, config)
```

# Appendix

## Emissions reductions tables

```{r}
# economy-wide
comparison_tables(var = "Emissions|CO2", 
                suffix = "Economy-Wide", 
                drop_mod = c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "Haiku-RFF"))

# electricity
comparison_tables(var = "Emissions|CO2|Energy|Supply|Electricity", 
                suffix = "Electricity", 
                drop_mod = c("Scout-LEEP"),
                drop_datasrc = c("ReEDS_compiled.csv")) # remove duplicate values for ReEDS-NREL - basically same values
```

```{r}
var = "Emissions|CO2"
suffix = "Economy-Wide"
drop_mod = c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "Haiku-RFF")


baseline_2005 = (clean_data %>% filter(year == 2005 &
                                         model == "EPA-GHGI" & variable == var))$value
baseline_2021 = (clean_data %>% filter(year == 2021 &
                                         model == "EPA-GHGI" & variable == var))$value

# interpolation
# year_range <- seq.int(from = vars$start_yr, to = vars$end_yr)
#
# interp <- data %>%
#   filter(variable %in% unique(vars$variable)) %>%
#   filter(!is.na(value)) %>%
#   complete(nesting(model, scenario, region, variable, unit, datasrc),
#            year = year_range) %>%
#   arrange(model, scenario, region, variable, year) %>%
#   nest(year, value) %>%
#   mutate(int_pts = map(data,
#                        .f = ~approx(x=.$year, y=.$value, xout = .$year) %>% as_tibble() )) %>%
#   unnest(cols = c(data, int_pts)) %>%
#   mutate(value = y) %>%
#   select(-x, -y)

table1 = clean_data %>%
  filter(
    variable == var &
      model %in% config$models_leep &
      !model %in% drop_mod &
      !datasrc %in% drop_datasrc &
      year %in% c(2005, 2025, 2030, 2035) &
      scenario %in% c("IRA", "No IRA")
  ) %>%
  select(-variable, -datasrc, -region) %>%
  mutate(diff_2005 = baseline_2021 - value,
         per_diff_2005 = diff_2005 / baseline_2005 * 100) %>%
  mutate(diff_2021 = baseline_2021 - value,
         per_diff_2021 = diff_2021 / baseline_2021 * 100) %>%
  mutate_if(is.numeric, round, 2)

table2 = table1 %>%
  group_by(year, scenario) %>%
  summarise(
    min_ab = min(value),
    max_ab = max(value),
    median_ab = median(value),
    min_diff_2005 = min(per_diff_2005),
    max_diff_2005 = max(per_diff_2005),
    median_diff_2005 = median(per_diff_2005),
    min_diff_2021 = min(per_diff_2021),
    max_diff_2021 = max(per_diff_2021),
    median_diff_2021 = median(per_diff_2021)
  ) %>%
  mutate_if(is.numeric, round, 2)

table3 = table1 %>%
  select(model, scenario, unit, year, value) %>%
  pivot_wider(names_from = "scenario", values_from = "value") %>%
  mutate(diff_noira = `No IRA` - `IRA`,
         per_diff_noira = diff_noira / `No IRA`) %>%
  mutate_if(is.numeric, round, 2) %>%
  group_by(year) %>%
  summarise(
    min_diff = min(diff_noira),
    max_diff = max(diff_noira),
    median_diff = median(diff_noira),
    min_per = min(per_diff_noira),
    max_per = max(per_diff_noira),
    median_per = median(per_diff_noira)
  )

return(list(table1,
            table2,
            table3))

```

## Economy-Wide Diff
```{r EconWide Differnce}
fig_no = "Ap.1.EconWideEmis"

ts_map_ID = 99
pd_map_ID = 25
ad_map_ID = 3
drop = ""
histsrc = "EPA-GHGI"
metric = "Emissions"
unit = "Mt CO2/yr"

fig = four_corners("Economy-wide CO2 Emissions",ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Electricity Diff
```{r Electricity Differnce}
fig_no = "Ap.2.ElecEmis"

ts_map_ID = 98
pd_map_ID = 26
ad_map_ID = 4
drop = ""
histsrc = "EPA-GHGI"
metric = "Emissions"
unit = "Mt CO2/yr"

fig = four_corners("Electricity CO2 Emissions",ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Transportation Diff
```{r Transportation Differnce}
fig_no = "Ap.3.TranEmis"

ts_map_ID = 19
pd_map_ID = 27
ad_map_ID = 5
drop = c("IPM-EPA","IPM-NRDC")
histsrc = "EPA-GHGI"
metric = "Emissions"
unit = "Mt CO2/yr"

fig = four_corners("Transportation CO2 Emissions",ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Building Diff
```{r Building Difference}
fig_no = "Ap.4.BuilEmis"

ts_map_ID = 23
pd_map_ID = 29
ad_map_ID = 7
drop = ""
histsrc = "EPA-GHGI"
metric = "Emissions"
unit = "Mt CO2/yr"

fig = four_corners("Buildings CO2 Emissions",ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Industry Diff
```{r Industry Differnce}
fig_no = "Ap.5.IndEmis"

ts_map_ID = 21
pd_map_ID = 28
ad_map_ID = 6
drop = ""
histsrc = "EPA-GHGI"
metric = "Emissions"
unit = "Mt CO2/yr"

fig = four_corners("Industry CO2 Emissions",ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)

```

## Coal Diff
```{r Coal Emissions Difference} 
fig_no = "Ap.6.Coal"

ts_map_ID = 94
pd_map_ID = 32
ad_map_ID = 20
drop = "EIAinEMF37.csv"
histsrc = "EIA"
metric = "Emissions"
unit = "Mt CO2/yr"

fig = four_corners("Primary Energy: Coal",ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Gas Diff
```{r Gas Emissions Difference} 
fig_no = "Ap.7.Gas"

ts_map_ID = 93
pd_map_ID = 31
ad_map_ID = 21
drop = "EIAinEMF37.csv"
histsrc = "EIA"
metric = "Emissions"
unit = "Mt CO2/yr"

fig = four_corners("Primary Energy: Gas",ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Petrol Diff
```{r Petrol Emissions Difference} 
fig_no = "Ap.8.Petrol"

ts_map_ID = 92
pd_map_ID = 30
ad_map_ID = 22
drop = "EIAinEMF37.csv"
histsrc = "EIA"
metric = "Emissions"
unit = "Mt CO2/yr"

fig = four_corners("Primary Energy: Petroleum", ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Nuclear Generation Diff
```{r Nuclear Generation Difference} 
fig_no = "Ap.9.NuclearGen"

ts_map_ID = 91
pd_map_ID = 80
ad_map_ID = 8
drop = "EIAinEMF37.csv"
histsrc = "EIA"
metric = "Generation"
unit = "TWh"

fig = four_corners("Nuclear Generation", ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Solar Generation Diff
```{r Solar Generation Difference} 
fig_no = "Ap.10.SolarGen"

ts_map_ID = 90
pd_map_ID = 79
ad_map_ID = 9
drop = c("EIAinEMF37.csv", "IPM-EPA")
histsrc = "EIA"
metric = "Generation"
unit = "TWh"

fig = four_corners("Solar Generation", ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Wind Generation Diff
```{r Wind Generation Difference} 
fig_no = "Ap.11.WindGen"

ts_map_ID = 89
pd_map_ID = 78
ad_map_ID = 10
drop = c("EIAinEMF37.csv", "IPM-EPA")
histsrc = "EIA"
metric = "Generation"
unit = "TWh"

fig = four_corners("Wind Generation", ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## CCS Generation Diff
```{r CCS Generation Difference, eval = FALSE} 
fig_no = "Ap.12.CCSGen"

#there is no historic data here so gotta do a lil manual work 
ts_map_ID = 85
pd_map_ID = 76
ad_map_ID = 14
drop = c("EIAinEMF37.csv", "IPM-EPA")
histsrc = "EIA"
unit = "Quads"

 #Time Series Dataframe
    ts_df = data_from_graph(
    "time_series",
    config,
    clean_data,
    figmap_leep_timeseries,
    ts_map_ID,
    "United States"
  ) %>%
    filter(!model %in% drop) %>%
    filter(!datasrc %in% drop)%>%
    filter(year >= 2021) %>%
    filter(year <= 2021 &
             model == histsrc |
             year > 2021 & scenario != "Historic") %>%
      group_by(model, scenario, year, variable_rename) %>%
      summarize(value = sum(value)) %>%
    pivot_wider(names_from = year, values_from = value)
    
    ts_df = ts_df %>%
    mutate(`2021` = 0) %>%
    pivot_longer(cols = starts_with("20"),
                 names_to = "year",
                 values_to = "value") %>%
    filter(!is.na(value)) %>%
    mutate(year = as.numeric(year)) 
      
    noIRAmedians = ts_df[ts_df$scenario == "No IRA",] %>%
      filter(year == 2030 | year == 2035) %>%
      group_by(year) %>%
      summarize(median = median(value))
    
    IRAmedians = ts_df[ts_df$scenario == "IRA",] %>%
      filter(year == 2030 | year == 2035) %>%
      group_by(year) %>%
      summarize(median = median(value))
    
    NoIRAfigure = ggplot(ts_df[ts_df$scenario == "No IRA", ], aes(year, value, color = model)) +
      geom_line(size = 0.75) +
      scale_subpalette(subpalettes, "Emissions|CO2|Percent difference from No IRA") +
      theme_emf() +
      scale_x_continuous(breaks = c(2021, 2025, 2030, 2035)) +
      labs(title = "No IRA",
           y = unit,
           x = element_blank()) +
      theme(legend.position = "right",
            axis.text.x = element_text(angle = 45, hjust = 1)) +
      geom_point(aes(x = 2021, y = ts_df$value[ts_df$year == 2021][1]), color = "black") +
      geom_point(
        data = noIRAmedians,
        aes(x = year, y = median),
        color = "black",
        shape = 16,
        size = 2
      )
    
    IRAfigure = ggplot(ts_df[ts_df$scenario == "IRA", ], aes(year, value, color = model)) +
      geom_line(size = 0.75) +
      scale_subpalette(subpalettes, "Emissions|CO2|Percent difference from No IRA") +
      theme_emf() +
      scale_x_continuous(breaks = c(2021, 2025, 2030, 2035)) +
      labs(title = "IRA",
           y = unit,
           x = element_blank()) +
      theme(legend.position = "right",
            axis.text.x = element_text(angle = 45, hjust = 1)) +
      geom_point(aes(x = 2021, y = ts_df$value[ts_df$year == 2021][1]), color = "black") +
      geom_point(
        data = IRAmedians,
        aes(x = year, y = median),
        color = "black",
        shape = 16,
        size = 2
      )
    
    #Percent Difference
      
pdfigure = pd(pd_map_ID, "", expression(paste("Percent Difference (%)")), "none", drop)
    
    #Absolute Difference
adfigure = ad(diff_ID = ad_map_ID, "", expression(paste("Absolute Difference (Quads)")), "none", drop)
  
fig = (NoIRAfigure | IRAfigure) / (adfigure$figure | pdfigure$figure)+ 
  plot_layout(guides = "collect") +
  plot_annotation(title = "CCS Generation")

fig

# TODO: This entire figure is broken and saves off data that doesnt exist. I fixed the figure, but the whole thing should be rewritten to fit the format of the rest of the figures and actually output the correct data

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig, fig_no)
```

## Coal Generation Diff
```{r Coal Generation Difference} 
fig_no = "Ap.13.CoalGen"

ts_map_ID = 82
pd_map_ID = 71
ad_map_ID = 17
drop = c("EIAinEMF37.csv", "IPM-EPA")
histsrc = "EIA"
metric = "Generation"
unit = "TWh"


fig = four_corners("Coal Generation", ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Gas Generation Diff
```{r Gas Generation Difference} 
fig_no = "Ap.14.GasGen"

ts_map_ID = 81
pd_map_ID = 70
ad_map_ID = 18
drop = c("EIAinEMF37.csv", "IPM-EPA")
histsrc = "EIA"
metric = "Generation"
unit = "TWh"


fig = four_corners("Gas Generation", ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Other Generation Diff
```{r Other Generation Difference} 
fig_no = "Ap.15.OtherGen"

ts_map_ID = 88
pd_map_ID = 77
ad_map_ID = 11
drop = c("EIAinEMF37.csv", "IPM-EPA")
histsrc = "EIA"
metric = "Generation"
unit = "TWh"


fig = four_corners("Other Generation", ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```











