---
title: "Archive for old figures"
output: 
  html_document:
    toc: true
    toc_float: true
date: "`r Sys.time()`"
params:
  mode: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
knitr::opts_knit$set(root.dir = here::here())
```

```{r}
if(is.null(params$mode)) {
  source("packages.R")
  tar_source()
}

# load data from targets pipeline
targets::tar_load(config)
targets::tar_load(clean_data)
targets::tar_load(figmap_leep_timeseries)
targets::tar_load(figmap_leep_cone)
targets::tar_load(figmap_leep_stackbar)
targets::tar_load(data_min)
targets::tar_load(data_raw)
```

## 2.4 us power sector generation from high and low/zero emitting generation

```{r}
fig_no = 2.4

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 16, "United States")

fig$data <- fig$data %>%
  filter(year == 2021 | year == 2030 | year == 2035)%>%
  filter(!model == "EIA") %>%
  filter(!model == "EIA-STEO") %>%
  mutate(value = value/0.0036, 
         unit = "TWh")

ymin = 0
ymax = 2600
metric = "median"

total <- fig$data %>%
  group_by(scenario, model, year) %>%
  summarise(value = sum(value)) %>%
  mutate(variable_rename = "Total")%>%
  mutate(alpha = case_when(
    model == "USREP-ReEDS" ~ 1, 
    model == "GCAM-PNNL" ~ 1, 
    model == "IPM-EPA" ~ 1,
    scenario == "Historic" ~ 1,
    T ~ 0.8
  ))

low <- fig$data %>%
  filter(variable_rename == "CCS" | 
         variable_rename == "Other" |
         variable_rename == "Nuclear" |
         variable_rename == "Solar" |
         variable_rename == "Wind"
) %>%
  group_by(scenario, model, year) %>%
  summarise(value = sum(value)) %>%
  mutate(variable_rename = "Total_Low")%>%
  mutate(alpha = case_when(
    model == "USREP-ReEDS" ~ 1, 
    model == "GCAM-PNNL" ~ 1, 
    model == "IPM-EPA" ~ 1,
    scenario == "Historic" ~ 1,
    T ~ 0.8
  ))

high <- fig$data %>%
  filter(variable_rename == "Coal" |
         variable_rename == "Natural Gas" |
         variable_rename == "Oil"
) %>%
  group_by(scenario, model, year) %>%
  summarise(value = sum(value)) %>%
  mutate(variable_rename = "Total_High")%>%
  mutate(alpha = case_when(
    model == "USREP-ReEDS" ~ 1, 
    model == "GCAM-PNNL" ~ 1, 
    model == "IPM-EPA" ~ 1,
    scenario == "Historic" ~ 1,
    T ~ 0.8
  ))

individual <- fig$data %>%
  mutate(
    variable_rename = case_when(variable_rename == "Oil" ~ "Other", 
                                T ~ variable_rename)
  ) %>%
  group_by(year, variable_rename, model, scenario) %>%
  summarise(value = sum(value))%>%
  mutate(alpha = case_when(
    model == "USREP-ReEDS" ~ 1, 
    model == "GCAM-PNNL" ~ 1, 
    model == "IPM-EPA" ~ 1,
    scenario == "Historic" ~ 1,
    T ~ 0.8
  ))

##### All Total #####
df_21 = total %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = total %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_35 = total %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

data_total <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

subpalettes = create_subpalettes(figmap_leep_timeseries, config)

dots_Total = ggplot(data = data_total, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"Total Generation") +
    scale_y_continuous(limits = c(ymin, 6500), breaks = c(0, 3250 , 6500), labels = scales::comma) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    labs(y = "Generation (TWh)") +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.x = element_blank(),
          axis.title.y = element_text(size = 7),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)

savedata(data_total, paste(fig_no, "Total"))

##### Low Total #####

df_21 = low %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))

df_30 = low %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  
df_35 = low %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  
mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

data_Low <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

dots_Low = ggplot(data = data_Low, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"Low or Zero Emitting Generation") +
    scale_y_continuous(limits = c(ymin, 6500), breaks = c(0, 3250 , 6500)) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.y = element_blank(), 
          axis.text.y = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)
savedata(data_Low, paste(fig_no, "Low"))

##### High Total #####
df_21 = high %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = high %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))

df_35 = high %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

data_High <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

dots_High = ggplot(data = data_High, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"High Emitting Generation") +
    scale_y_continuous(limits = c(ymin, 6500), breaks = c(0, 3250 , 6500)) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.y = element_blank(), 
          axis.text.y = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)
savedata(data_High, paste(fig_no, "High"))

##### Nuclear #####
df_21 = individual[individual$variable_rename == "Nuclear", ] %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = individual[individual$variable_rename == "Nuclear", ] %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_35 = individual[individual$variable_rename == "Nuclear", ] %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

 

data_Nuclear <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

dots_Nuclear = ggplot(data = data_Nuclear, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"Nuclear") +
    scale_y_continuous(limits = c(ymin, 2600), breaks = c(0, 1300 , 2600)) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.y = element_blank(), 
          axis.text.y = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)
savedata(data_Nuclear, paste(fig_no, "Nuclear"))

##### Solar #####
df_21 = individual[individual$variable_rename == "Solar", ] %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = individual[individual$variable_rename == "Solar", ] %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_35 = individual[individual$variable_rename == "Solar", ] %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

 

data_Solar <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

dots_Solar = ggplot(data = data_Solar, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"Solar") +
    scale_y_continuous(limits = c(ymin, 2600), breaks = c(0, 1300 , 2600)) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.y = element_blank(), 
          axis.text.y = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)
savedata(data_Solar, paste(fig_no, "Solar"))

##### Wind #####

df_21 = individual[individual$variable_rename == "Wind", ] %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = individual[individual$variable_rename == "Wind", ] %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_35 = individual[individual$variable_rename == "Wind", ] %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

 

data_Wind <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

dots_Wind = ggplot(data = data_Wind, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"Wind") +
    scale_y_continuous(limits = c(ymin, 2600), breaks = c(0, 1300 , 2600), labels = scales::comma) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    labs(y = "Generation (TWh)") +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.x = element_blank(),
          axis.title.y = element_text(size = 7),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)
savedata(data_Wind, paste(fig_no, "Wind"))

##### CCS #####

df_21 = individual[individual$variable_rename == "CCS", ] %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = individual[individual$variable_rename == "CCS", ] %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_35 = individual[individual$variable_rename == "CCS", ] %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

 

data_CCS <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

dots_CCS = ggplot(data = data_CCS, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"CCS") +
    scale_y_continuous(limits = c(ymin, 2600), breaks = c(0, 1300 , 2600)) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.y = element_blank(), 
          axis.text.y = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)
savedata(data_CCS, paste(fig_no, "CCS"))

##### Coal #####
df_21 = individual[individual$variable_rename == "Coal", ] %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = individual[individual$variable_rename == "Coal", ] %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_35 = individual[individual$variable_rename == "Coal", ] %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

 

data_Coal <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

dots_Coal = ggplot(data = data_Coal, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"Coal") +
    scale_y_continuous(limits = c(ymin, 2600), breaks = c(0, 1300 , 2600), labels = scales::comma) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    labs(y = "Generation (TWh)") +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.x = element_blank(),
          axis.title.y = element_text(size = 7),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)
savedata(data_Coal, paste(fig_no, "Coal"))

##### Gas #####
df_21 = individual[individual$variable_rename == "Natural Gas", ] %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = individual[individual$variable_rename == "Natural Gas", ] %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_35 = individual[individual$variable_rename == "Natural Gas", ] %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

 

data_Gas <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

dots_Gas = ggplot(data = data_Gas, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"Natural Gas") +
    scale_y_continuous(limits = c(ymin, 2600), breaks = c(0, 1300 , 2600)) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.y = element_blank(), 
          axis.text.y = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)
savedata(data_Gas, paste(fig_no, "Gas"))

##### Other #####
df_21 = individual[individual$variable_rename == "Other", ] %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = individual[individual$variable_rename == "Other", ] %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_35 = individual[individual$variable_rename == "Other", ] %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

 

data_Other <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

dots_Other = ggplot(data = data_Other, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"Other") +
    scale_y_continuous(limits = c(ymin, 2600), breaks = c(0, 1300 , 2600)) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.y = element_blank(), 
          axis.text.y = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)
savedata(data_Other, paste(fig_no, "Other"))

##### Final #####
final = (dots_Total | dots_Low | dots_High) / (dots_Wind | dots_Solar | dots_Nuclear | dots_CCS) / (dots_Coal | dots_Gas | dots_Other) 

final = final + 
  plot_layout(
  guides = "collect"
) & theme(legend.position = "bottom")
final

savefig(final, fig_no)
```

## 1.x Playing around with arrows
```{r, eval = FALSE}
# Economy-wide emissions
clean_data12 = clean_data %>% duplicate_historical_data("EPA-GHGI", 2021, criteria = TRUE)
p = dot_plots_but_with_arrows("time_series", config, clean_data12, figmap_leep_timeseries, 99,
                              "United States", 0, 6000, "Economy-wide Emissions",
                              metric = "median", historic_coord = c(2017,5540),
                              preira_coord = c(2030, 4750), ira_coord = c(2029, 3230) )
p$full

p2 = dot_plots_but_with_arrows("time_series", config, clean_data12,
                               figmap_leep_timeseries, 98,
                              "United States", 0, 2600, "Economy-wide Emissions",
                              metric = "median", historic_coord = c(2017,2100),
                              preira_coord = c(2030, 1520), ira_coord = c(2029, 300) )
p2$full
```

### EV Share OLD 4Corners
```{r}
fig_no = "E.17.EvSalesShare"

subpalettes_ev = create_subpalettes(figmap_leep_timeseries, config)
# TODO: NEMS-OP should only have reporting every 5 years

# clean_data_evshare = spg_clean(ts_map_ID = 118, drop = c(""), histsrc = "EPA-ATR",
#                            config = config, clean_data = clean_data4, figmap_leep_timeseries = figmap_leep_timeseries)
scen_map = read.csv("./data-raw/scenario-mapping.csv") %>% select(datasrc, model, scenario, model_new, scenario_new)
raw = data_raw %>% select(model, scenario, region, variable, unit, datasrc, year, value) %>%
  left_join(scen_map, by = c("datasrc", "model", "scenario")) %>%
  select(-c(model, scenario)) %>%
  rename(model = model_new) %>%
  rename(scenario = scenario_new) %>%
  filter(unit != "thousands") %>%
  filter(!(model == "EPA-ATR" & year >= 2022))

atr_2022 = raw %>% filter(model == "EPA-ATR", year == 2021) %>% mutate(year = 2022)
nems = data_min %>% select(model, scenario, region, variable, unit, datasrc, year, value) %>%
  filter(model == "NEMS-OP",
         scenario %in% c("IRA", "No IRA"),
         datasrc != "LTS_data_small.xlsx",
         grepl("Sales Share", variable),
         unit == "%") %>%
  left_join(scen_map, by = c("datasrc", "model", "scenario")) %>%
  select(-c(model, scenario)) %>%
  rename(model = model_new) %>%
  rename(scenario = scenario_new)

clean_data_evshare = rbind(raw, atr_2022, nems) %>%
  filter(unit != "thousands") %>%
  mutate(value = 100 * value) %>%
  filter(model != "EIA-LTS") %>%
  duplicate_historical_data("EPA-ATR", 2022, criteria = TRUE) %>% mutate(
    variable = case_when(
      variable %in% c(
        "Energy Service|Transportation|Passenger|BEV|Sales Share",
        # "Energy Service|Transportation|Passenger|FCEV|Sales Share",
        # "Energy Service|Transportation|Passenger|HEV|Sales Share",
        # "Energy Service|Transportation|Freight|BEV|Sales Share",
        # "Energy Service|Transportation|Freight|FCEV|Sales Share",
        "Energy Service|Transportation|Passenger|PHEV|Sales Share",
        "Energy Service|Transportation|Passenger|BEV and PHEV|Sales Share"
        ) ~
        "Energy Service|Transportation|Passenger|BEV and PHEV|Sales Share")) %>%
  group_by(model, scenario, unit, datasrc, year, region, variable) %>%
  summarize(value = sum(value)) %>%
  filter(!(is.na(variable))) %>%
  filter(year <= 2035) %>%
#  filter(!(model %in% c("NEMS-OP-LTS"))) %>%
  filter(!(datasrc %in% c("LTS_data_small.xlsx"))) %>%
  mutate(variable_rename = variable) %>%
  mutate(alpha = case_when(
      model == "USREP-ReEDS" ~ 1,
      model == "GCAM-PNNL" ~ 1,
      model == "IPM-EPA" ~ 1,
      scenario == "Historic" ~ 1,
      T ~ 1
  )) %>%
  mutate(value = case_when(year == 2022 & model == "NEMS-OP" ~ 100 * atr_2022$value[1],
                           TRUE ~ value))

clean_data_evshare = clean_data_evshare %>%
  filter(year >= 2021) %>%
  filter(year %in% c(2021, 2025, 2030, 2035))

hist = clean_data_evshare %>%
  group_by(model) %>%
  slice(1) %>%
  ungroup %>%
  mutate(year = 2021) %>%
  mutate(value = value[scenario == "Historic"][1]) %>%
  mutate(scenario = "Historic")

EV_IRA = clean_data_evshare %>%
  filter(scenario != "No IRA")

EV_IRA = rbind(EV_IRA, hist)

EV_noIRA = clean_data_evshare %>%
  filter(scenario != "IRA")

EV_noIRA = rbind(EV_noIRA, hist)

  noIRAmedians = EV_noIRA %>%
    filter(year == 2030 | year == 2035) %>%
    group_by(year) %>%
    summarize(median = median(value))

  IRAmedians = EV_IRA %>%
    filter(year == 2030 | year == 2035) %>%
    group_by(year) %>%
    summarize(median = median(value))

  NoIRAfigure = ggplot(EV_noIRA, aes(year, value, color = model)) +
    geom_line(aes(linetype = model),size = 0.75) +
    scale_subpalette(subpalettes_ev, "Emissions|CO2|Percent difference from No IRA") +
      scale_linetype_manual(values = c("USREP-ReEDS" = "solid", 
                                       "EPS-EI" = "solid", 
                                       "GCAM-CGS" = "solid", 
                                       "GCAM-PNNL" = "solid",
                                       "Haiku-RFF" = "solid",
                                       "IPM-NRDC" = "solid", 
                                       "IPM-EPA" = "solid", 
                                       "MARKAL-NETL" = "solid", 
                                       "NEMS-RHG" = "solid",
                                       "NEMS-OP" = "twodash", 
                                       "REGEN-EPRI" = "dashed", 
                                       "RIO-REPEAT" = "dotted", 
                                       "ReEDS-NREL" = "longdash", 
                                       "NEMS-EIA" = "dotdash")) +
    theme_emf() +
    scale_x_continuous(breaks = c(2021, 2025, 2030, 2035)) +
    scale_y_continuous(limits = c(0, 85), breaks = c(0, 20, 40, 60, 80)) +
    labs(title = "No IRA",
         y = expression(`EV Sales Share (%)`),
         x = element_blank()) +
    theme(legend.position = "right",
         plot.title = element_text(hjust = 0.5),
          axis.text.x = element_text(angle = 45, hjust = 1), 
         axis.ticks = element_line(color = "black"),  
         axis.ticks.length = unit(-0.15, "cm")) +
    geom_point(aes(x = 2021, y = EV_noIRA$value[EV_noIRA$year == 2021][1]), color = "black") +
    geom_point(
      data = noIRAmedians,
      aes(x = year, y = median),
      color = "black",
      shape = 16,
      size = 2
    )

  IRAfigure = ggplot(EV_IRA, aes(year, value, color = model)) +
    geom_line(aes(linetype = model), size = 0.75) +
    scale_subpalette(subpalettes_ev, "Emissions|CO2|Percent difference from No IRA") +
      scale_linetype_manual(values = c("USREP-ReEDS" = "solid", 
                                       "EPS-EI" = "solid", 
                                       "GCAM-CGS" = "solid", 
                                       "GCAM-PNNL" = "solid",
                                       "Haiku-RFF" = "solid",
                                       "IPM-NRDC" = "solid", 
                                       "IPM-EPA" = "solid", 
                                       "MARKAL-NETL" = "solid", 
                                       "NEMS-RHG" = "solid",
                                       "NEMS-OP" = "twodash", 
                                       "REGEN-EPRI" = "dashed", 
                                       "RIO-REPEAT" = "dotted", 
                                       "ReEDS-NREL" = "longdash", 
                                       "NEMS-EIA" = "dotdash")) +
    theme_emf() +
    scale_x_continuous(breaks = c(2021, 2025, 2030, 2035)) +
    scale_y_continuous(limits = c(0, 85), breaks = c(0, 20, 40, 60, 80)) +
    labs(title = "IRA",
         y = expression(`EV Sales Share (%)`),
         x = element_blank()) +
    theme(legend.position = "right",
          plot.title = element_text(hjust = 0.5),
          axis.text.x = element_text(angle = 45, hjust = 1),
          axis.ticks = element_line(color = "black"), 
          axis.ticks.length = unit(-0.15, "cm")) +
    geom_point(aes(x = 2021, y = EV_IRA$value[EV_IRA$year == 2021][1]), color = "black") +
    geom_point(
      data = IRAmedians,
      aes(x = year, y = median),
      color = "black",
      shape = 16,
      size = 2
    )

dif = rbind(EV_IRA, EV_noIRA)

dif_hist = dif %>%
  filter(scenario == "Historic") %>%
  slice(1) %>%
  ungroup() %>%
  mutate(value = 0) %>%
  select(model, year, value) %>%
  mutate(name = "historic")

dif = dif %>%
  filter(scenario != "Historic") %>%
  pivot_wider(names_from = scenario, values_from = value) %>%
  mutate(absdif = IRA - `No IRA`) %>%
  mutate(pdif = ((IRA - `No IRA`) / IRA) * 100) %>%
  ungroup() %>%
  select(model, year, absdif, pdif)

dif_clean = dif %>%
  pivot_longer(cols = c(absdif, pdif))

dif_fin = rbind(dif_clean, dif_hist)

df = dif_fin %>%
  filter(name != "pdif")

medians = df %>%
    filter(year %in% c(2030, 2035)) %>%
    group_by(year) %>%
    summarize(median = median(value))


EV_abdif_figure = ggplot() +
    geom_line(data = df,
              aes(
                x = year,
                y = value,
                group = model,
                color = model
              ),
              size = 0.75) +
    geom_point(aes(x = 2021, y = 0), color = "black") +
    geom_point(
      data = medians,
      aes(x = year, y = median),
      color = "black",
      shape = 16,
      size = 2
    ) +
    scale_subpalette(subpalettes_ev, "Emissions|CO2|Percent difference from No IRA") +
      scale_linetype_manual(values = c("USREP-ReEDS" = "solid", 
                                       "EPS-EI" = "solid", 
                                       "GCAM-CGS" = "solid", 
                                       "GCAM-PNNL" = "solid",
                                       "Haiku-RFF" = "solid",
                                       "IPM-NRDC" = "solid", 
                                       "IPM-EPA" = "solid", 
                                       "MARKAL-NETL" = "solid", 
                                       "NEMS-RHG" = "solid",
                                       "NEMS-OP" = "twodash", 
                                       "REGEN-EPRI" = "dashed", 
                                       "RIO-REPEAT" = "dotted", 
                                       "ReEDS-NREL" = "longdash", 
                                       "NEMS-EIA" = "dotdash")) +
    labs(title = "",
         x = "",
         y = expression(`Absolute Difference (%)`)) +
    theme_emf() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      panel.spacing.x = unit(4, "mm"),
      legend.position = "none", 
      axis.ticks = element_line(color = "black"), 
      axis.ticks.length = unit(-0.15, "cm")
    ) +
    scale_x_continuous(breaks = c(2021, 2025, 2030, 2035))

df = dif_fin %>%
  filter(name != "absdif")

medians = df %>%
    filter(year %in% c(2030, 2035)) %>%
    group_by(year) %>%
    summarize(median = median(value))


EV_pdif_figure = ggplot() +
    geom_line(data = df,
              aes(
                x = year,
                y = value,
                group = model,
                color = model
              ),
              size = 0.75) +
    geom_point(aes(x = 2021, y = 0), color = "black") +
    geom_point(
      data = medians,
      aes(x = year, y = median),
      color = "black",
      shape = 16,
      size = 2
    ) +
    scale_subpalette(subpalettes_ev, "Emissions|CO2|Percent difference from No IRA") +
      scale_linetype_manual(values = c("USREP-ReEDS" = "solid", 
                                       "EPS-EI" = "solid", 
                                       "GCAM-CGS" = "solid", 
                                       "GCAM-PNNL" = "solid",
                                       "Haiku-RFF" = "solid",
                                       "IPM-NRDC" = "solid", 
                                       "IPM-EPA" = "solid", 
                                       "MARKAL-NETL" = "solid", 
                                       "NEMS-RHG" = "solid",
                                       "NEMS-OP" = "twodash", 
                                       "REGEN-EPRI" = "dashed", 
                                       "RIO-REPEAT" = "dotted", 
                                       "ReEDS-NREL" = "longdash", 
                                       "NEMS-EIA" = "dotdash")) +
    labs(title = "",
         x = "",
         y = expression(`Percent Difference (%)`)) +
    theme_emf() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      panel.spacing.x = unit(4, "mm"),
      legend.position = "none", 
      axis.ticks = element_line(color = "black"), 
      axis.ticks.length = unit(-0.15, "cm")
    ) +
    scale_x_continuous(breaks = c(2021, 2025, 2030, 2035))

  figure = (NoIRAfigure | IRAfigure) / (EV_abdif_figure | EV_pdif_figure)+
    plot_layout(guides = "collect") +
    plot_annotation(caption = "EV Sales Share")

savefig(figure, fig_no)

```
