---
title: "Chapter 1: LEEP Report Figures and Data"
date: "`r Sys.time()`"
output: 
  html_document:
    toc: true
    toc_float: true
params:
  mode: NULL
  format: "svg"
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = TRUE, warning = FALSE, message = FALSE, tidy = TRUE, cache = FALSE, paged.print=TRUE)
knitr::opts_knit$set(root.dir = here::here())
```

```{r}
source("packages.R")
devtools::load_all(here())

# load data from targets pipeline
targets::tar_load(config)
targets::tar_load(clean_data)
targets::tar_load(figmap_leep_timeseries)
targets::tar_load(figmap_leep_cone)
targets::tar_load(figmap_leep_stackbar)

# create workbook for saving figure data
# data_wb <- createWorkbook()

# format toggle
format <- "svg"
format <- params$format

# palettes
subpalettes = create_subpalettes(figmap_leep_timeseries, config)
```

```{r}
savefig = function(figure, fig_no, format = "svg", wd = 7, ht = 5, unit = "in") {
  ggsave(filename = paste("output/final_figures/",format,"/Fig",fig_no,".",format,sep=""),
         plot = figure, 
         width = wd, 
         height = ht, 
         units = unit)
}
```

# Chapter 1 - Introduction / Economy-Wide

##  Fig 1.2

```{r}
fig_no = 1.2

metric = "median"
ymin = 0

# economy-wide
ymax = 7000

df <- data_from_graph("time_series", config, clean_data, figmap_leep_timeseries, 15, "United States") %>%
  filter(year <= 2021 & model == "EPA-GHGI" | year > 2021 & scenario != "Historic")%>%
  pivot_wider(names_from = year, values_from = value) %>%
  filter(!model == "IPM-NRDC", 
         !model == "IPM-EPA", 
         !model =="ReEDS-NREL", 
         !model == "Scout-LEEP", 
         !model == "Haiku-RFF" )

df <- df %>%
  mutate(
    `2021` = case_when(
      is.na(`2021`) & variable_rename == "Total Emissions" ~ df$`2021`[df$variable_rename == "Total Emissions" & df$model == "EPA-GHGI"],
      
      is.na(`2021`) & variable_rename == "Electricity" ~ df$`2021`[df$variable_rename == "Electricity" & df$model == "EPA-GHGI"],
      
      is.na(`2021`) & variable_rename == "Transportation" ~ df$`2021`[df$variable_rename == "Transportation" & df$model == "EPA-GHGI"],
      
      is.na(`2021`) & variable_rename == "Industry" ~ df$`2021`[df$variable_rename == "Industry" & df$model == "EPA-GHGI"],
      
      is.na(`2021`) & variable_rename == "Buildings" ~ df$`2021`[df$variable_rename == "Buildings" & df$model == "EPA-GHGI"], 
      T ~ `2021`
    )
  )

df <- df %>%
  pivot_longer(cols = starts_with("20"), names_to = "year", values_to = "value") %>%
  mutate(alpha = case_when(
    model == "USREP-ReEDS" ~ 1, 
    model == "GCAM-PNNL" ~ 1, 
    model == "IPM-EPA" ~ 1,
    scenario == "Historic" ~ 1,
    T ~ 0.8
  )) %>%
  mutate(year = as.numeric(year)) %>%
  filter(!is.na(value))

All <- df %>% 
  filter(variable_rename == "Total Emissions")

Electricity <- df %>% 
  filter(variable_rename == "Electricity") 

A = ggplot(data = All, aes(year, value, color = scenario, group = interaction(model, scenario))) + 
  geom_line(size = 0.5, aes(alpha = alpha)) +
  scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
  labs(title = expression(paste("Economy-Wide C", O[2], " Emissions")),
         x = "",
         y = expression(paste("Mt C", O[2], "/yr")),
         color = "") +
  scale_x_continuous(breaks = c(2005, 2021, 2025, 2030, 2035)) +
  scale_y_continuous(limits = c(0,6200), labels = scales::comma) +
    theme_emf() +
    theme(axis.text.x = element_text(angle = 45, hjust=1))+
    theme(panel.spacing.x = unit(4, "mm"), legend.position = "none") + 
  scale_alpha(range = c(0.6, 1), guide = F) + 
  annotate("text", x = 2015, y = 4900, label = "Historic", color = "black") + 
  annotate("text", x = 2027.5, y = 5500, label = "No IRA", color = "#F28063") + 
  annotate("text", x = 2022, y = 3800, label = "IRA", color = "#0388B3")

B = ggplot(data = Electricity, aes(year, value, color = scenario, group = interaction(model, scenario), alpha = alpha)) + 
  geom_line(size = 0.5, aes(alpha = alpha)) + 
  scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
  theme_emf() +
  theme(legend.position = "none", axis.text.x = element_text(angle = 45, hjust=1))+
  scale_x_continuous(breaks = c(2005, 2021, 2025, 2030, 2035)) +
  scale_y_continuous(limits = c(0,2500), labels = scales::comma) +
  labs(title = "Electricity",
       x = element_blank(),
         y = expression(paste("Mt C", O[2], "/yr")))+ 
  scale_alpha(range = c(0.4, 1), guide = F) 

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 19, "United States")

metric = "median"
ymin = 0
ymax = 2500

fig$data <- fig$data %>%
  filter(
    year <= 2021 & model == "EPA-GHGI" | year >= 2021 & scenario != "Historic"
  ) %>%
  pivot_wider(names_from = year, values_from = value)%>%
  filter(!model == "IPM-NRDC", 
         !model == "IPM-EPA", 
         !model =="ReEDS-NREL", 
         !model == "Scout-LEEP", 
         !model == "USREP-ReEDS")

fig$data <- fig$data %>%
  mutate(
    `2021`= case_when(
      T ~ fig$data$`2021`[fig$data$model == "EPA-GHGI"]
    )
  )

fig$data <- fig$data %>%
  pivot_longer(cols = starts_with("20"), names_to = "year", values_to = "value") %>%
  filter(!is.na(value)) %>%
  mutate(year = as.numeric(year)) %>%
  mutate(alpha = case_when(
    model == "USREP-ReEDS" ~ 1, 
    model == "GCAM-PNNL" ~ 1, 
    model == "IPM-EPA" ~ 1,
    scenario == "Historic" ~ 1,
    T ~ 0.6
  ))


J = ggplot(data = fig$data, aes(year, value, color = scenario, group = interaction(model, scenario))) +
  geom_line(size = 0.5, aes(alpha = alpha)) + 
  scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
  theme_emf() +
  theme(legend.position = "none") +
  scale_x_continuous(breaks = c(2005, 2021, 2025, 2030, 2035)) +
  theme(axis.text.x = element_text(angle = 45, hjust=1))+
  scale_y_continuous(limits = c(0, 2500), labels = scales::comma) +
  labs(title = "Transportation",
       x = element_blank(),
         y = expression(paste("Mt C", O[2], "/yr")))+ 
  scale_alpha(range = c(0.4, 1), guide = F) 

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 23, "United States")

metric = "median"
ymin = 0
ymax = 2500

fig$data <- fig$data %>%
  filter(
    year <= 2021 & model == "EPA-GHGI" | year >= 2021 & scenario != "Historic"
  ) %>%
  pivot_wider(names_from = year, values_from = value)%>%
  filter(!model == "IPM-NRDC", 
         !model == "IPM-EPA", 
         !model =="ReEDS-NREL", 
         !model == "Scout-LEEP", 
         !model == "MARKAL-NETL", 
         !model == "GCAM-PNNL")

fig$data <- fig$data %>%
  mutate(
    `2021`= case_when(
      T ~ fig$data$`2021`[fig$data$model == "EPA-GHGI"]
    )
  )

fig$data <- fig$data %>%
  pivot_longer(cols = starts_with("20"), names_to = "year", values_to = "value") %>%
  filter(!is.na(value)) %>%
  mutate(year = as.numeric(year)) %>%
  mutate(alpha = case_when(
    model == "USREP-ReEDS" ~ 1, 
    model == "GCAM-PNNL" ~ 1, 
    model == "IPM-EPA" ~ 1,
    scenario == "Historic" ~ 1,
    T ~ 0.6
  ))


K = ggplot(data = fig$data, aes(year, value, color = scenario, group = interaction(model, scenario))) + geom_line(size = 0.5, aes(alpha = alpha)) + 
  scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
  theme_emf() +
  theme(legend.position = "none", 
        axis.text.y = element_blank()) +
  scale_x_continuous(breaks = c(2005, 2021, 2025, 2030, 2035)) +
  theme(axis.text.x = element_text(angle = 45, hjust=1))+
  labs(  title = "Buildings",
       x = element_blank(),
         y = element_blank()) + 
  scale_alpha(range = c(0.4, 1), guide = F) + 
  ylim(0,2500)


fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 21, "United States")

metric = "median"
ymin = 0
ymax = 2500

fig$data <- fig$data %>%
  filter(
    year <= 2021 & model == "EPA-GHGI" | year >= 2021 & scenario != "Historic"
  ) %>%
   pivot_wider(names_from = year, values_from = value) %>%
   filter(!model == "IPM-NRDC",
          !model == "IPM-EPA")


fig$data <- fig$data %>%
  mutate(
    `2021`= case_when(
      T ~ fig$data$`2021`[fig$data$model == "EPA-GHGI"]
    )
  )

fig$data <- fig$data %>%
  pivot_longer(cols = starts_with("20"), names_to = "year", values_to = "value") %>%
  filter(!is.na(value)) %>%
  mutate(year = as.numeric(year)) %>%
  mutate(alpha = case_when(
    model == "USREP-ReEDS" ~ 1, 
    model == "GCAM-PNNL" ~ 1, 
    model == "IPM-EPA" ~ 1,
    scenario == "Historic" ~ 1,
    T ~ 0.6
  ))


L = ggplot(data = fig$data, aes(year, value, color = scenario, group = interaction(model, scenario))) +geom_line(size = 0.5, aes(alpha = alpha)) + 
  scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
  theme_emf() +
  theme(legend.position = "none", 
        axis.text.y = element_blank()) +
  scale_x_continuous(breaks = c(2005, 2021, 2025, 2030, 2035)) +
  theme(axis.text.x = element_text(angle = 45, hjust=1))+
  labs(  title = "Industry",
       x = element_blank(),
         y = element_blank()) + 
  scale_alpha(range = c(0.4, 1), guide = F) + 
  ylim(0,2500)


final = (A|B) / (J|K|L) + plot_annotation(tag_levels = list(c("", "", "Sectoral Emissions: Direct + Indirect Electricity", "", ""))) & theme(plot.tag.position = c(1.0, 1.1))

final

savefig(final, fig_no, format, wd = 8)
```

### Table 1.2 Econ

```{r}

title = "Economy Wide Emissions"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 15, "United States")

fig$data <- fig$data %>%
  filter(variable == "Emissions|CO2")

base <- fig$data %>%
  filter(year == 2005 & model == "EPA-GHGI")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (Mt CO2)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (Mt CO2)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (Mt CO2)`)

NoIRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (Mt CO2)` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)

IRA$`Absolute Level (Mt CO2)` = round(IRA$`Absolute Level (Mt CO2)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (Mt CO2)` = round(IRA$`Reductions from No IRA (Mt CO2)`,3)

IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

write.csv(IRA, paste0("./output/leep/", title, ".csv"), row.names = F)

IRA %>%
tableHTML(caption = paste(title), rownames = F)




```

### Table 1.2 Power

```{r}

title = "Power Sector Emissions"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 11, "United States")

base <- fig$data %>%
  filter(year == 2005 & model == "EPA-GHGI")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (Mt CO2)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (Mt CO2)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (Mt CO2)`)

NoIRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (Mt CO2)` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)

IRA$`Absolute Level (Mt CO2)` = round(IRA$`Absolute Level (Mt CO2)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (Mt CO2)` = round(IRA$`Reductions from No IRA (Mt CO2)`,3)

IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

write.csv(IRA, paste0("./output/leep/", title, ".csv"), row.names = F)

IRA %>%
tableHTML(caption = paste(title), rownames = F)




```

### Table 1.2 Transportaiton

```{r}

title = "Total Transportation Emissions"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 19, "United States")

fig$data <- fig$data %>%
  filter(!model == "IPM-NRDC", 
         !model == "IPM-EPA", 
         !model =="ReEDS-NREL", 
         !model == "Scout-LEEP", 
         !model == "MARKAL-NETL", 
         !model == "GCAM-PNNL", 
         !model == "USREP-ReEDS")

base <- fig$data %>%
  filter(year == 2005 & model == "EPA-GHGI")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (Mt CO2)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (Mt CO2)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (Mt CO2)`)

NoIRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (Mt CO2)` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)

IRA$`Absolute Level (Mt CO2)` = round(IRA$`Absolute Level (Mt CO2)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (Mt CO2)` = round(IRA$`Reductions from No IRA (Mt CO2)`,3)

IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

write.csv(IRA, paste0("./output/leep/", title, ".csv"), row.names = F)

IRA %>%
tableHTML(caption = paste(title), rownames = F)
```

### Table 1.2 Buildings

```{r}

title = "Total Building Emissions"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 23, "United States")

fig$data <- fig$data %>%
  filter(!model == "IPM-NRDC", 
         !model == "IPM-EPA", 
         !model =="ReEDS-NREL", 
         !model == "Scout-LEEP", 
         !model == "MARKAL-NETL", 
         !model == "GCAM-PNNL")

base <- fig$data %>%
  filter(year == 2005 & model == "EPA-GHGI")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (Mt CO2)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (Mt CO2)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (Mt CO2)`)

NoIRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (Mt CO2)` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)

IRA$`Absolute Level (Mt CO2)` = round(IRA$`Absolute Level (Mt CO2)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (Mt CO2)` = round(IRA$`Reductions from No IRA (Mt CO2)`,3)

IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

write.csv(IRA, paste0("./output/leep/", title, ".csv"), row.names = F)

IRA %>%
tableHTML(caption = paste(title), rownames = F)





```

### Table 1.2 Industry

```{r}

title = "Total Industry Emissions"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 21, "United States")

fig$data <- fig$data %>%
  filter(!model == "IPM-NRDC", 
         !model == "IPM-EPA", 
         !model == "GCAM-PNNL")

base <- fig$data %>%
  filter(year == 2005 & model == "EPA-GHGI")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (Mt CO2)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (Mt CO2)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (Mt CO2)`)

NoIRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (Mt CO2)` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)

IRA$`Absolute Level (Mt CO2)` = round(IRA$`Absolute Level (Mt CO2)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (Mt CO2)` = round(IRA$`Reductions from No IRA (Mt CO2)`,3)

IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

write.csv(IRA, paste0("./output/leep/", title, ".csv"), row.names = F)

IRA %>%
tableHTML(caption = paste(title), rownames = F)
```

## Fig 1.3

```{r}
fig_no = 1.3
##### Data #####
fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 10, "United States")

metric = "median"
ymin = 0
ymax = 45

fig$data <- fig$data %>%
  filter(
    year <= 2021 & scenario == "Historic" | year > 2021 & scenario != "Historic"
  )%>%
  filter(scenario == "Historic" & model == "EIA" & datasrc != "EIAinEMF37.csv" | scenario != "Historic") %>% 
  pivot_wider(names_from = year, values_from = value) %>%
  filter(!model == "RIO-REPEAT")
  

fig$data <- fig$data %>%
  mutate(
    `2021` = case_when(
      is.na(`2021`) & variable_rename == "Coal" ~ fig$data$`2021`[fig$data$variable_rename == "Coal" & fig$data$model == "EIA"],
      is.na(`2021`) & variable_rename == "Gas" ~ fig$data$`2021`[fig$data$variable_rename == "Gas" & fig$data$model == "EIA"], 
      is.na(`2021`) & variable_rename == "Oil" ~ fig$data$`2021`[fig$data$variable_rename == "Oil" & fig$data$model == "EIA"], 
      T ~ `2021`
    )
  ) %>%
  pivot_longer(cols = starts_with("20"), names_to = "year", values_to = "value") 

fig$data <- fig$data %>%
  filter(!is.na(value)) %>%
  mutate(year = as.numeric(year))%>%
  mutate(alpha = case_when(
    model == "USREP-ReEDS" ~ 1, 
    model == "GCAM-PNNL" ~ 1, 
    model == "IPM-EPA" ~ 1,
    scenario == "Historic" ~ 1,
    T ~ 0.8
  )) %>%
  mutate(value = value*0.94782, 
         unit = "Quads") %>%
  mutate(variable_rename = case_when(
    variable_rename == "Oil" ~ "Petroleum", 
    T ~ variable_rename
  ))

##### Coal #####
fig_coal = ggplot(data = fig$data[fig$data$variable_rename=="Coal",], aes(year, value, color = scenario, group = interaction(model, scenario))) + 
  geom_line(size = 0.75, aes(alpha = alpha)) + 
  facet_grid(~variable_rename) +
  scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
  labs(         x = "",
         y = fig$data$unit,
         color = "") +
    scale_y_continuous(limits = c(ymin, ymax), labels = scales::comma) +
    theme_emf() +
    theme(axis.text.x = element_text(angle = 45, hjust=1), legend.position = "none") +
    theme(panel.spacing.x = unit(4, "mm")) + 
  scale_x_continuous(breaks = c(2005, 2021, 2025, 2030, 2035)) +
  scale_alpha(range = c(0.6, 1), guide = F)

df_30 = fig$data[fig$data$variable_rename=="Coal",] %>%
    filter(year %in% c(2030))
  df_stat_30 = df_30 %>%
    group_by(scenario,year,variable_rename) %>%
    summarise(mean = mean(value),
           median = median(value))
  
  df_35 = fig$data[fig$data$variable_rename=="Coal",] %>%
    filter(year %in% c(2035))
  df_stat_35 = df_35 %>%
    group_by(scenario,year,variable_rename) %>%
    summarise(mean = mean(value),
           median = median(value))
  
  
  mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
  mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean
  median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
  median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median
  # stick em all in a data frame
  stats = data.frame("year" = c(2030,2035,2030,2035), "metric" = c("mean","mean","median","median"), 
                     "difference" = c(mean_diff_30, mean_diff_35, median_diff_30, median_diff_35))
  
# print("Coal")
# print(stats)
# print(df_stat_30) 
# print(df_stat_35)  

  # a few of the ggplot lines of code vary based on the year or on the metric chosen, so conditionally choose the right one here
  if (metric == "mean") {
    segment_code_30 = geom_segment(data = df_stat_30, aes(x = year - 0.1, xend = year + 0.1, y = mean, yend = mean, color = scenario), 
                                   size = 1)
    segment_code_35 = geom_segment(data = df_stat_35, aes(x = year - 0.1, xend = year + 0.1, y = mean, yend = mean, color = scenario),
                                   size = 1)
  } else if (metric == "median") {
    segment_code_30 = geom_segment(data = df_stat_30, aes(x = year - 0.1, xend = year + 0.1, y = median, yend = median, color = scenario), 
                                   size = 1)
    segment_code_35 = geom_segment(data = df_stat_35, aes(x = year - 0.1, xend = year + 0.1, y = median, yend = median, color = scenario), 
                                   size = 1)
  }
  
  dots_30_coal = ggplot() +
    geom_point(data = df_30, aes(x = year, y = value, color = scenario, alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = 0.2)) +
    segment_code_30 +
    #text_code +
    scale_x_continuous(breaks = c(2030), labels = c("2030"), limits = c(2029.9, 2030.1)) +
    scale_y_continuous(limits = c(ymin, ymax)) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(panel.grid = element_blank(), plot.title = element_blank(),
          axis.text.y = element_blank(),
          axis.text.x = element_text(angle = 45, hjust=1),
          axis.title.y = element_blank(), axis.title.x = element_blank(),
          axis.ticks = element_blank(), panel.border = element_blank(),
          legend.position = "none", plot.margin = margin(0,0,0,0))+
  scale_alpha(range = c(0.6, 1), guide = F)
  
  # dot plot for 2035
  dots_35_coal = ggplot() +
    geom_point(data = df_35, aes(x = year, y = value, color = scenario, alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = 0.2)) +
    segment_code_35 +
    scale_x_continuous(breaks = c(2035), labels = c("2035"), limits = c(2034.9, 2035.1)) +
    scale_y_continuous(limits = c(ymin,ymax)) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(panel.grid = element_blank(), plot.title = element_blank(),
          axis.text.x = element_text(angle = 45, hjust=1),
          axis.text.y = element_blank(),
          axis.title.y = element_blank(), axis.title.x = element_blank(),
          axis.ticks = element_blank(), panel.border = element_blank(),
          legend.position = "none", plot.margin = margin(0,0,0,0))+
  scale_alpha(range = c(0.6, 1), guide = F)
  

  
  
##### Oil #####

fig_oil = ggplot(data = fig$data[fig$data$variable_rename=="Petroleum",], aes(year, value, color = scenario, group = interaction(model, scenario))) + 
  geom_line(size = 0.75, aes(alpha = alpha)) + 
  facet_grid(~variable_rename) +
  scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
  labs(x = "",
         y = element_blank(),
         color = "") +
    theme_emf() +
    theme(axis.text.x = element_text(angle = 45, hjust=1), legend.position = "none", axis.text.y = element_blank()) +
    theme(panel.spacing.x = unit(4, "mm")) + 
  scale_x_continuous(breaks = c(2005, 2021, 2025, 2030, 2035)) +
    ylim(ymin,ymax)+
  scale_alpha(range = c(0.6, 1), guide = F)
  
  df_30 = fig$data[fig$data$variable_rename=="Petroleum",] %>%
    filter(year %in% c(2030))
  df_stat_30 = df_30 %>%
    group_by(scenario,year,variable_rename) %>%
    summarise(mean = mean(value),
           median = median(value))
  
  df_35 = fig$data[fig$data$variable_rename=="Petroleum",] %>%
    filter(year %in% c(2035))
  df_stat_35 = df_35 %>%
    group_by(scenario,year,variable_rename) %>%
    summarise(mean = mean(value),
           median = median(value))
  
  
  mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
  mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean
  median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
  median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median
  # stick em all in a data frame
  stats = data.frame("year" = c(2030,2035,2030,2035), "metric" = c("mean","mean","median","median"), 
                     "difference" = c(mean_diff_30, mean_diff_35, median_diff_30, median_diff_35))
  
# print("Oil")
# print(stats)
# print(df_stat_30) 
# print(df_stat_35) 

  # a few of the ggplot lines of code vary based on the year or on the metric chosen, so conditionally choose the right one here
  if (metric == "mean") {
    segment_code_30 = geom_segment(data = df_stat_30, aes(x = year - 0.1, xend = year + 0.1, y = mean, yend = mean, color = scenario), 
                                   size = 1)
    segment_code_35 = geom_segment(data = df_stat_35, aes(x = year - 0.1, xend = year + 0.1, y = mean, yend = mean, color = scenario),
                                   size = 1)
  } else if (metric == "median") {
    segment_code_30 = geom_segment(data = df_stat_30, aes(x = year - 0.1, xend = year + 0.1, y = median, yend = median, color = scenario), 
                                   size = 1)
    segment_code_35 = geom_segment(data = df_stat_35, aes(x = year - 0.1, xend = year + 0.1, y = median, yend = median, color = scenario), 
                                   size = 1)
  }
  
  dots_30_oil = ggplot() +
    geom_point(data = df_30, aes(x = year, y = value, color = scenario, alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = 0.2)) +
    segment_code_30 +
    #text_code +
    scale_x_continuous(breaks = c(2030), labels = c("2030"), limits = c(2029.9, 2030.1)) +
    scale_y_continuous(limits = c(ymin, ymax)) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(panel.grid = element_blank(), plot.title = element_blank(),
          axis.text.y = element_blank(),
          axis.text.x = element_text(angle = 45, hjust=1),
          axis.title.y = element_blank(), axis.title.x = element_blank(),
          axis.ticks = element_blank(), panel.border = element_blank(),
          legend.position = "none", plot.margin = margin(0,0,0,0))+
  scale_alpha(range = c(0.6, 1), guide = F)
  
  # dot plot for 2035
  dots_35_oil = ggplot() +
    geom_point(data = df_35, aes(x = year, y = value, color = scenario, alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = 0.2)) +
    segment_code_35 +
    scale_x_continuous(breaks = c(2035), labels = c("2035"), limits = c(2034.9, 2035.1)) +
    scale_y_continuous(limits = c(ymin,ymax)) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(panel.grid = element_blank(), plot.title = element_blank(),
          axis.text.y = element_blank(),
          axis.text.x = element_text(angle = 45, hjust=1),
          axis.title.y = element_blank(), axis.title.x = element_blank(),
          axis.ticks = element_blank(), panel.border = element_blank(),
          legend.position = "none", plot.margin = margin(0,0,0,0))+
  scale_alpha(range = c(0.6, 1), guide = F)

  
##### Gas #####
fig_gas = ggplot(data = fig$data[fig$data$variable_rename=="Gas",], aes(year, value, color = scenario, group = interaction(model, scenario))) + 
  geom_line(size = 0.75, aes(alpha = alpha)) + 
  facet_grid(~variable_rename) +
  scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
  labs(x = "",
         y = element_blank(),
         color = "") +
    scale_y_continuous(limits = c(ymin, ymax), labels = scales::comma) +
    theme_emf() +
    theme(axis.text.x = element_text(angle = 45, hjust=1), legend.position = "none", axis.text.y = element_blank()) +
    theme(panel.spacing.x = unit(4, "mm")) + 
  scale_x_continuous(breaks = c(2005, 2021, 2025, 2030, 2035)) +
  scale_alpha(range = c(0.6, 1), guide = F) +
  annotate("text", x = 2010, y = 35, label = "Historic", color = "black") + 
  annotate("text", x = 2027.5, y = 35, label = "No IRA", color = "#F28063") + 
  annotate("text", x = 2022, y = 22.5, label = "IRA", color = "#0388B3")

df_30 = fig$data[fig$data$variable_rename=="Gas",] %>%
    filter(year %in% c(2030))
  df_stat_30 = df_30 %>%
    group_by(scenario,year,variable_rename) %>%
    summarise(mean = mean(value),
           median = median(value))
  
  df_35 = fig$data[fig$data$variable_rename=="Gas",] %>%
    filter(year %in% c(2035))
  df_stat_35 = df_35 %>%
    group_by(scenario,year,variable_rename) %>%
    summarise(mean = mean(value),
           median = median(value))
  
  
  mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
  mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean
  median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
  median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median
  # stick em all in a data frame
  stats = data.frame("year" = c(2030,2035,2030,2035), "metric" = c("mean","mean","median","median"), 
                     "difference" = c(mean_diff_30, mean_diff_35, median_diff_30, median_diff_35))
  
# print("Gas")
# print(stats)
# print(df_stat_30) 
# print(df_stat_35) 

  # a few of the ggplot lines of code vary based on the year or on the metric chosen, so conditionally choose the right one here
  if (metric == "mean") {
    segment_code_30 = geom_segment(data = df_stat_30, aes(x = year - 0.1, xend = year + 0.1, y = mean, yend = mean, color = scenario), 
                                   size = 1)
    segment_code_35 = geom_segment(data = df_stat_35, aes(x = year - 0.1, xend = year + 0.1, y = mean, yend = mean, color = scenario),
                                   size = 1)
  } else if (metric == "median") {
    segment_code_30 = geom_segment(data = df_stat_30, aes(x = year - 0.1, xend = year + 0.1, y = median, yend = median, color = scenario), 
                                   size = 1)
    segment_code_35 = geom_segment(data = df_stat_35, aes(x = year - 0.1, xend = year + 0.1, y = median, yend = median, color = scenario), 
                                   size = 1)
  }
  
  dots_30_gas = ggplot() +
    geom_point(data = df_30, aes(x = year, y = value, color = scenario, alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = 0.2)) +
    segment_code_30 +
    #text_code +
    scale_x_continuous(breaks = c(2030), labels = c("2030"), limits = c(2029.9, 2030.1)) +
    scale_y_continuous(limits = c(ymin, ymax)) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(panel.grid = element_blank(), plot.title = element_blank(),
          axis.text.y = element_blank(),
          axis.text.x = element_text(angle = 45, hjust=1),
          axis.title.y = element_blank(), axis.title.x = element_blank(),
          axis.ticks = element_blank(), panel.border = element_blank(),
          legend.position = "none", plot.margin = margin(0,0,0,0)) +
  scale_alpha(range = c(0.6, 1), guide = F)
  
  # dot plot for 2035
  dots_35_gas = ggplot() +
    geom_point(data = df_35, aes(x = year, y = value, color = scenario, alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = 0.2)) +
    segment_code_35 +
    scale_x_continuous(breaks = c(2035), labels = c("2035"), limits = c(2034.9, 2035.1)) +
    scale_y_continuous(limits = c(ymin,ymax)) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(panel.grid = element_blank(), plot.title = element_blank(),
          axis.text.y = element_blank(),
          axis.text.x = element_text(angle = 45, hjust=1),
          axis.title.y = element_blank(), axis.title.x = element_blank(),
          axis.ticks = element_blank(), panel.border = element_blank(),
          legend.position = "none", plot.margin = margin(0,0,0,0))+
  scale_alpha(range = c(0.6, 1), guide = F)

final_coal = fig_coal + dots_30_coal + dots_35_coal +
    plot_layout(widths = c(10,1,1)) +
    theme(plot.margin = margin(0,0,0,0))

final_gas = fig_gas + dots_30_gas + dots_35_gas + 
    plot_layout(widths = c(10,1,1)) +
    theme(plot.margin = margin(0,0,0,0))
  
final_oil = fig_oil + dots_30_oil + dots_35_oil + 
    plot_layout(widths = c(10,1,1)) +
    theme(plot.margin = margin(0,0,0,0))



final = (final_coal | final_gas | final_oil)


print(final)

ggsave(filename = paste("output/final_figures/",format,"/Fig",fig_no,".",format,sep=""), 
       plot = final, width = 7, height = 5, units = "in")
```

### Table 1.3 Coal

```{r}

title = "Coal Emissions"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 10, "United States")

fig$data <- fig$data %>%
  filter(variable_rename == "Coal")

base <- fig$data %>%
  filter(year == 2005 & model == "EIA")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (Mt CO2)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (Mt CO2)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (Mt CO2)`)

NoIRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (Mt CO2)` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)

IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

IRA$`Absolute Level (Mt CO2)` = round(IRA$`Absolute Level (Mt CO2)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (Mt CO2)` = round(IRA$`Reductions from No IRA (Mt CO2)`,3)

write.csv(IRA, paste0("./output/leep/", title, ".csv"), row.names = F)

IRA %>%
tableHTML(caption = paste(title), rownames = F)
```

### Table 1.3 Gas

```{r}

title = "Gas Emissions"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 10, "United States")

fig$data <- fig$data %>%
  filter(variable_rename == "Gas")

base <- fig$data %>%
  filter(year == 2005 & model == "EIA")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (Mt CO2)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (Mt CO2)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (Mt CO2)`)

NoIRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (Mt CO2)` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)

IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

IRA$`Absolute Level (Mt CO2)` = round(IRA$`Absolute Level (Mt CO2)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (Mt CO2)` = round(IRA$`Reductions from No IRA (Mt CO2)`,3)

write.csv(IRA, paste0("./output/leep/", title, ".csv"), row.names = F)

IRA %>%
tableHTML(caption = paste(title), rownames = F)
```

### Table 1.3 Oil

```{r}

title = "Oil Emissions"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 10, "United States")

fig$data <- fig$data %>%
  filter(variable_rename == "Oil")

base <- fig$data %>%
  filter(year == 2005 & model == "EIA")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (Mt CO2)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (Mt CO2)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (Mt CO2)`)

NoIRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (Mt CO2)` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)

IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

IRA$`Absolute Level (Mt CO2)` = round(IRA$`Absolute Level (Mt CO2)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (Mt CO2)` = round(IRA$`Reductions from No IRA (Mt CO2)`,3)

write.csv(IRA, paste0("./output/leep/", title, ".csv"), row.names = F)

IRA %>%
tableHTML(caption = paste(title), rownames = F)
```

