---
title: "Chapter 4: Buildings"
output: 
  html_document:
    toc: true
    toc_float: true
date: "`r Sys.time()`"
params:
  mode: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = here::here())
```

```{r}
if(is.null(params$mode)) {
  source("packages.R")
  devtools::load_all()
}

# load data from targets pipeline
targets::tar_load(config)
targets::tar_load(clean_data)
targets::tar_load(figmap_leep_timeseries)
targets::tar_load(figmap_leep_cone)
targets::tar_load(figmap_leep_stackbar)
targets::tar_load(data_min)
targets::tar_load(data_raw)

# create workbook for saving figure data
# data_wb <- createWorkbook()
```

## 4.1 co2 emissions from the buildings sector in the us compared to economy-wide co2 emissions

```{r}
fig_no = 4.1

subpalettes = create_subpalettes(figmap_leep_stackbar, config)

dta3 = data_from_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 9, "United States") %>%
  mutate(variable_rename = case_when(
    variable_rename == "Buildings: Direct" ~ variable_rename,
    variable_rename == "Buildings: Indirect" ~ variable_rename,
    TRUE ~ "Other Sectors"
  )) %>%
  mutate(variable_rename = factor(variable_rename, 
                                  levels = c("Buildings: Direct", "Buildings: Indirect","Other Sectors")))

p3 = emis_stack(dta3, "Buildings CO2 Emissions", figmap_leep_stackbar, config) + 
  scale_fill_manual(values = c("Other Sectors" = "white", "Buildings: Indirect" = subpalettes$`Emissions Stack`[["Buildings: Indirect"]], "Buildings: Direct" = subpalettes$`Emissions Stack`[["Buildings: Direct"]])) +
  scale_color_manual(values = c("Other Sectors" = "#CECECE", "Buildings: Indirect" = subpalettes$`Emissions Stack`[["Buildings: Indirect"]], "Buildings: Direct" = subpalettes$`Emissions Stack`[["Buildings: Direct"]])) +
  scale_alpha_manual(values = c("Other Sectors" = 0.5, "Buildings: Indirect" = 1, "Buildings: Direct" = 1))
p3

dta3 = clean_supplemental_data(dta3, fig_no)

saveall(p3, dta3, fig_no)
```

## 4.2 buildings total co2 emissions

```{r}
fig_no = 4.2

Tot_data = spg_clean(
  23,
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Haiku-RFF"),
  "EPA-GHGI", 
  config, 
  clean_data,
  figmap_leep_timeseries
  )

TotSpg = spg2(
  Tot_data,
  expression(paste("Total Building C", O[2])),
  expression(paste("Emissions (Mt C", O[2], "/yr)")),
  gd = "none",
  0,
  2500,
  c(0, 500, 1000, 1500, 2000, 2500),
  scales::comma, 
  1, 
  c(2015, 2250), 
  c(2030, 1675), 
  c(2022.5, 1000), 
  config, 
  figmap_leep_timeseries)

TotDot = dotted(TotSpg$data, TotSpg$figure, "median", 0, 2500, config, figmap_leep_timeseries)
TotDot

TotTab = html(TotSpg$data, "Total Building CO<sub>2<sub>")

Dir_data = spg_clean(
  95, 
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "MARKAL-NETL", "GCAM-PNNL"),
  "EPA-GHGI", 
  config, 
  clean_data, 
  figmap_leep_timeseries)

DirSpg = spg2(
  Dir_data,
  expression(paste("Direct Combustion")),
  expression(paste("Emissions(Mt C", O[2], "/yr)")),
  gd = "none",
  0,
  2000,
  c(0, 500, 1000, 1500, 2000),
  scales::comma, 
  0, 
  c(2015, 1000), 
  c(2030, 1000), 
  c(2022.5, 1000), 
  config,
  figmap_leep_timeseries)

DirDot = dotted(DirSpg$data, DirSpg$figure, "median", 0, 2000, config, figmap_leep_timeseries)

DirTab = html(DirSpg$data, "Direct Building CO<sub>2<sub>")

IndDir_data = spg_clean(
  22, 
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "MARKAL-NETL", "GCAM-PNNL"),
  "EPA-GHGI", 
  config, 
  clean_data, 
  figmap_leep_timeseries
)


IndDirSpg = spg2(
  IndDir_data,
  expression(paste("Indirect from Electricity")),
  "",
  gd = "none",
  0,
  2000,
  c(0, 500, 1000, 1500, 2000),
  NULL, 
  0, 
  c(2015, 1000), 
  c(2030, 1000), 
  c(2022.5, 1000), 
  config,
  figmap_leep_timeseries)

IndDirDot = dotted(IndDirSpg$data, IndDirSpg$figure, "median", 0, 2000, config, figmap_leep_timeseries)

IndDirTab = html(IndDirSpg$data, "Indirect Building CO<sub>2<sub>")

figure = TotDot / (DirDot | IndDirDot)
figure

savefig(TotDot, fig_no) # only using total, not using direct/indirect anymore

TotTab
DirTab
IndDirTab

TotSpg$data = clean_supplemental_data(TotSpg$data, fig_no)
DirSpg$data = clean_supplemental_data(DirSpg$data, fig_no)
IndDirSpg$data = clean_supplemental_data(IndDirSpg$data, fig_no)

savedata(TotSpg$data, paste(fig_no, "Total"))
savedata(DirSpg$data, paste(fig_no, "Direct"))
savedata(IndDirSpg$data, paste(fig_no, "Indirect"))
```

## 4.3 emissions reudctions by end use type from scout modeling

```{r}
fig_no = 4.3

data <- read.csv("./data-extra/scout_buildings_IRA_scenario_emissions_wedges.csv")

data_sort <- data %>%
  filter(year <= 2035) %>%
  filter(year >= 2025) %>%
  mutate(scenario = case_when(
    scenario == "IRA-Low" ~ "IRA-Pessimistic", 
    scenario == "IRA-Central" ~ "IRA-Moderate", 
    scenario == "IRA-High" ~ "IRA-Optimistic"
  )) %>%
  rename(Reference = `Reference.Building.Emissions`,
         Total = `Total.Building.Emissions`, 
         Power = `Power.Supply.Decarbonization`, 
         WaterHeating = `Water.Heating`, 
         HVAC = HVAC.Env) %>%
  pivot_longer(
    cols = c(Reference, Total, Power, Other, WaterHeating, HVAC), names_to = "variable_rename"
  )
  
ref <- data_sort[data_sort$variable_rename == "Reference",]

data_sort$scenario <- factor(data_sort$scenario, levels = c("IRA-Pessimistic", "IRA-Moderate", "IRA-Optimistic"))
data_sort$variable_rename <- factor(data_sort$variable_rename, levels = c("HVAC", "WaterHeating", "Other","Power", "Total", "Reference"))

fin = ggplot(data = data_sort[data_sort$variable_rename != "Reference",] , aes(x=year, y=value, fill = variable_rename)) +
  geom_area() +
  facet_grid(~scenario) +
  labs(title = "",
         x = "",
         y = expression(paste("Emissions (Mt C", O[2], "/yr)")),
         color = "") +
    scale_y_continuous(limits = c(0, 1500), labels = scales::comma) +
    theme_emf() +
    scale_x_continuous(breaks = c(2025, 2030, 2035)) + 
    theme(axis.text.x = element_text(angle = 45, hjust=1)) +
    theme(panel.spacing.x = unit(4, "mm"), legend.position = "bottom") + 
  guides(fill = guide_legend(nrow = 2)) + 
  scale_fill_manual(name = "", 
    labels = c("HVAC/Env", "Water Heating", "Other" , "Power Supply Decarbonizaiton", "Total Building Emissions", "Reference"),
    breaks = c("HVAC", "WaterHeating", "Other","Power", "Total", "Reference"), 
    values = c("#75FF8E", '#f58231', "#FFF362",  '#42d4f4', "#DEDEDE", "#767684"),
    limits = c("HVAC", "WaterHeating", "Other", "Power", "Total") 
  ) + 
  geom_line(data = data_sort[data_sort$variable_rename == "Reference",],  aes(x=year, y=value, color = variable_rename),linetype="dashed") +
  scale_color_manual(name = "", 
    labels = c("HVAC/Env", "Water Heating", "Other" , "Power Supply Decarbonizaiton", "Total Building Emissions", "Reference"),
    breaks = c("HVAC", "WaterHeating", "Other","ower", "Total", "Reference"), 
    values = c("#75FF8E", '#f58231', "#FFF362",  '#42d4f4', "#DEDEDE", "#767684"),
    limits = c("Reference") 
  )
fin

data_sort = data_sort %>% mutate(figure_num = fig_no)

saveall(fin, data_sort, fig_no, wd = 9)
```
