---
title: "LEEP Report Figures and Data"
date: "`r Sys.time()`"
output: 
  html_document:
    toc: true
    toc_float: true
params:
  mode: NULL
  format: "svg"
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = TRUE, warning = FALSE, message = FALSE, tidy = TRUE, cache = FALSE, paged.print=TRUE)
knitr::opts_knit$set(root.dir = here::here())
```

```{r}
source("packages.R")
devtools::load_all(here())

# load data from targets pipeline
targets::tar_load(config)
targets::tar_load(clean_data)
targets::tar_load(figmap_leep_timeseries)
targets::tar_load(figmap_leep_cone)
targets::tar_load(figmap_leep_stackbar)

# create workbook for saving figure data
# data_wb <- createWorkbook()

# format toggle
format <- "svg"
format <- params$format

# palettes
subpalettes = create_subpalettes(figmap_leep_timeseries, config)
```

```{r}
savefig = function(figure, fig_no, format = "svg", wd = 7, ht = 5, unit = "in") {
  ggsave(filename = paste("output/final_figures/",format,"/Fig",fig_no,".",format,sep=""),
         plot = figure, 
         width = wd, 
         height = ht, 
         units = unit)
}
```

# Chapter 2 - Electricity

## Fig 2.1

```{r}
fig_no = 2.1

data <- clean_data %>%
  filter(model == "EPA-GHGI") %>%
  filter(year >= 2005) %>%
  filter(variable == "Emissions|CO2|Energy|Demand|Buildings|Commercial|Coal"|
         variable == "Emissions|CO2|Energy|Demand|Buildings|Commercial|Gas" |
         variable == "Emissions|CO2|Energy|Demand|Buildings|Commercial|Oil" |
         variable == "Emissions|CO2|Energy|Demand|Buildings|Residential|Coal" |
         variable == "Emissions|CO2|Energy|Demand|Buildings|Residential|Gas" |
         variable == "Emissions|CO2|Energy|Demand|Buildings|Residential|Oil" |
         variable == "Emissions|CO2|Energy|Demand|Industry|Coal" |
         variable == "Emissions|CO2|Energy|Demand|Industry|Gas" |
         variable == "Emissions|CO2|Energy|Demand|Industry|Oil" |
         variable == "Emissions|CO2|Energy|Demand|Transportation|Gas" |
         variable == "Emissions|CO2|Energy|Demand|Transportation|Oil" |
         variable == "Emissions|CO2|Energy|Supply|Electricity|Coal" |
         variable == "Emissions|CO2|Energy|Supply|Electricity|Gas" |
         variable == "Emissions|CO2|Energy|Supply|Electricity|Oil") %>%
  mutate(variable_rename = case_when(
    grepl("Demand", variable) ~ "Other Sectors",
    grepl("Coal", variable) ~ "Coal", 
    grepl("Gas", variable) ~ "Gas", 
    grepl("Oil", variable) ~ "Petroleum",
  )) %>%
  group_by(year, variable_rename) %>%
  summarise(value = sum(value)) %>%
  mutate(alpha = case_when(
    variable_rename == "Other Sectors" ~ 0.5, 
    T ~ 1))

data$variable_rename <- factor(data$variable_rename, level = c("Other Sectors", "Coal", "Gas", "Petroleum"))

fig = ggplot(data, aes(fill = variable_rename, y = value, alpha = alpha, x = year, color = variable_rename)) + 
  geom_bar(position = "stack", stat = "identity") + 
  theme_emf() +
  labs(title = "",
         x = "",
         y = expression(paste("Mt C", O[2], "/yr"))) +
    scale_y_continuous(limits = c(0, 6000), labels = scales::comma) +
    scale_x_continuous(breaks = c(2005, 2021)) + 
    theme(panel.spacing.x = unit(4, "mm"), legend.position = "bottom") +
    scale_alpha(range = c(0.6, 1), guide = F)+
  scale_color_manual(breaks = c( "Coal", "Gas", "Petroleum", "Other Sectors"), 
                     values = c( "#003052", "#BC8F73", "#733D3D", "black")) +
  scale_fill_manual(breaks = c( "Coal", "Gas", "Petroleum", "Other Sectors"), 
                     values = c( "#003052", "#BC8F73", "#733D3D", "white")) 

print(fig)

ggsave(filename = paste("output/final_figures/",format,"/Fig",fig_no,".",format,sep=""), 
       plot = final, width = 7, height = 5, units = "in")
```

## Fig 2.3

```{r}
fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 11, "United States")

metric = "median"
ymin = 0
ymax = 2500

fig$data <- fig$data %>%
  filter(
    year <= 2021 & model == "EPA-GHGI" | year >= 2021 & scenario != "Historic"
  ) %>%
  pivot_wider(names_from = year, values_from = value)

fig$data <- fig$data %>%
  mutate(
    `2021`= case_when(
      is.na(`2021`) ~ fig$data$`2021`[fig$data$model == "EPA-GHGI"],
      T ~ `2021`
    )
  )

fig$data <- fig$data %>%
  pivot_longer(cols = starts_with("20"), names_to = "year", values_to = "value") %>%
  filter(!is.na(value)) %>%
  mutate(year = as.numeric(year))%>%
  mutate(alpha = case_when(
    model == "USREP-ReEDS" ~ 1, 
    model == "GCAM-PNNL" ~ 1, 
    model == "IPM-EPA" ~ 1,
    scenario == "Historic" ~ 1,
    T ~ 0.8
  ))
  

fig = ggplot(data = fig$data, aes(year, value, color = scenario, group = interaction(model, scenario))) + 
  geom_line(size = 0.75, aes(alpha = alpha)) +  
  scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
  labs(title = "",
         x = "",
         y = expression(paste("Mt C", O[2], "/yr")),
         color = "") +
    scale_y_continuous(limits = c(ymin, ymax), labels = scales::comma) +
    theme_emf() +
    theme(axis.text.x = element_text(angle = 45, hjust=1)) +
    theme(panel.spacing.x = unit(4, "mm"), legend.position = "none") +
  scale_x_continuous(breaks = c(2005, 2021, 2025, 2030, 2035)) +
    scale_alpha(range = c(0.6, 1), guide = F)+
  annotate("text", x = 2015, y = 2250, label = "Historic", color = "black") + 
  annotate("text", x = 2027.5, y = 1750, label = "No IRA", color = "#F28063") + 
  annotate("text", x = 2023, y = 650, label = "IRA", color = "#0388B3")

df_30 = fig$data %>%
    filter(year %in% c(2030))
  df_stat_30 = df_30 %>%
    group_by(scenario,year,variable_rename) %>%
    summarise(mean = mean(value),
           median = median(value))
  
  df_35 = fig$data %>%
    filter(year %in% c(2035))
  df_stat_35 = df_35 %>%
    group_by(scenario,year,variable_rename) %>%
    summarise(mean = mean(value),
           median = median(value))
  
  
  mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
  mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean
  median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
  median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median
  # stick em all in a data frame
  stats = data.frame("year" = c(2030,2035,2030,2035), "metric" = c("mean","mean","median","median"), 
                     "difference" = c(mean_diff_30, mean_diff_35, median_diff_30, median_diff_35))
  
  # a few of the ggplot lines of code vary based on the year or on the metric chosen, so conditionally choose the right one here
  if (metric == "mean") {
    segment_code_30 = geom_segment(data = df_stat_30, aes(x = year - 0.025, xend = year + 0.025, y = mean, yend = mean, color = scenario), 
                                   size = 1)
    segment_code_35 = geom_segment(data = df_stat_35, aes(x = year - 0.025, xend = year + 0.025, y = mean, yend = mean, color = scenario),
                                   size = 1)
  } else if (metric == "median") {
    segment_code_30 = geom_segment(data = df_stat_30, aes(x = year - 0.025, xend = year + 0.025, y = median, yend = median, color = scenario), 
                                   size = 1)
    segment_code_35 = geom_segment(data = df_stat_35, aes(x = year - 0.025, xend = year + 0.025, y = median, yend = median, color = scenario), 
                                   size = 1)
  }
  
  dots_30 = ggplot() +
    geom_point(data = df_30, aes(x = year, y = value, color = scenario, alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = 0.05)) +
    segment_code_30 +
    scale_x_continuous(breaks = c(2030), labels = c("2030"), limits = c(2029.9, 2030.1)) +
    scale_y_continuous(limits = c(ymin, ymax)) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(panel.grid = element_blank(), plot.title = element_blank(),
          axis.text.y = element_blank(),
          axis.text.x = element_text(angle = 45, hjust=1),
          axis.title.y = element_blank(), axis.title.x = element_blank(),
          axis.ticks = element_blank(), panel.border = element_blank(),
          legend.position = "none", plot.margin = margin(0,0,0,0)) +
    scale_alpha(range = c(0.6, 1), guide = F)
  
  # dot plot for 2035
  dots_35 = ggplot() +
    geom_point(data = df_35, aes(x = year, y = value, color = scenario, alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = 0.05)) +
    segment_code_35 +
    scale_x_continuous(breaks = c(2035), labels = c("2035"), limits = c(2034.9, 2035.1)) +
    scale_y_continuous(limits = c(ymin,ymax)) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(panel.grid = element_blank(), plot.title = element_blank(),
          axis.text.y = element_blank(),
          axis.text.x = element_text(angle = 45, hjust=1),
          axis.title.y = element_blank(), axis.title.x = element_blank(),
          axis.ticks = element_blank(), panel.border = element_blank(),
          legend.position = "none", plot.margin = margin(0,0,0,0))+
    scale_alpha(range = c(0.6, 1), guide = F)

final = fig + dots_30 + dots_35 +
    plot_annotation(title =  fig$data$plot_title, theme = theme(plot.title = element_text(hjust = 0.5))) +
    plot_layout(guides = "collect", widths = c(10,1,1)) +
    theme(plot.margin = margin(0,0,0,0))

print(final)


ggsave(filename = "output/final_figures/Fig2.3.svg", plot = final,width = 7, height = 5, units = "in")

ggsave(filename = "output/final_figures/Fig2.3.png", plot = final,width = 7, height = 5, units = "in")
```

### Table 2.3

```{r}

title = "Power Sector Emissions"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 11, "United States")

base <- fig$data %>%
  filter(year == 2005 & model == "EPA-GHGI")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (Mt CO2)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (Mt CO2)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (Mt CO2)`)

NoIRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (Mt CO2)` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)

IRA$`Absolute Level (Mt CO2)` = round(IRA$`Absolute Level (Mt CO2)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (Mt CO2)` = round(IRA$`Reductions from No IRA (Mt CO2)`,3)

IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

write.csv(IRA, paste0("./output/leep/", title, ".csv"), row.names = F)

IRA %>%
tableHTML(caption = paste(title), rownames = F)




```

## Fig 2.4

```{r}
##### Data #####
fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 16, "United States")

fig$data <- fig$data %>%
  filter(year == 2021 | year == 2030 | year == 2035)%>%
  filter(!model == "EIA") %>%
  filter(!model == "EIA-STEO") %>%
  mutate(value = value/0.0036, 
         unit = "TWh")

ymin = 0
ymax = 2600
metric = "median"

total <- fig$data %>%
  group_by(scenario, model, year) %>%
  summarise(value = sum(value)) %>%
  mutate(variable_rename = "Total")%>%
  mutate(alpha = case_when(
    model == "USREP-ReEDS" ~ 1, 
    model == "GCAM-PNNL" ~ 1, 
    model == "IPM-EPA" ~ 1,
    scenario == "Historic" ~ 1,
    T ~ 0.8
  ))

low <- fig$data %>%
  filter(variable_rename == "CCS" | 
         variable_rename == "Other" |
         variable_rename == "Nuclear" |
         variable_rename == "Solar" |
         variable_rename == "Wind"
) %>%
  group_by(scenario, model, year) %>%
  summarise(value = sum(value)) %>%
  mutate(variable_rename = "Total_Low")%>%
  mutate(alpha = case_when(
    model == "USREP-ReEDS" ~ 1, 
    model == "GCAM-PNNL" ~ 1, 
    model == "IPM-EPA" ~ 1,
    scenario == "Historic" ~ 1,
    T ~ 0.8
  ))

high <- fig$data %>%
  filter(variable_rename == "Coal" |
         variable_rename == "Natural Gas" |
         variable_rename == "Oil"
) %>%
  group_by(scenario, model, year) %>%
  summarise(value = sum(value)) %>%
  mutate(variable_rename = "Total_High")%>%
  mutate(alpha = case_when(
    model == "USREP-ReEDS" ~ 1, 
    model == "GCAM-PNNL" ~ 1, 
    model == "IPM-EPA" ~ 1,
    scenario == "Historic" ~ 1,
    T ~ 0.8
  ))

individual <- fig$data %>%
  mutate(
    variable_rename = case_when(variable_rename == "Oil" ~ "Other", 
                                T ~ variable_rename)
  ) %>%
  group_by(year, variable_rename, model, scenario) %>%
  summarise(value = sum(value))%>%
  mutate(alpha = case_when(
    model == "USREP-ReEDS" ~ 1, 
    model == "GCAM-PNNL" ~ 1, 
    model == "IPM-EPA" ~ 1,
    scenario == "Historic" ~ 1,
    T ~ 0.8
  ))




##### All Total #####
df_21 = total %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = total %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_35 = total %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

 

data_total <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

dots_Total = ggplot(data = data_total, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"Total Generation") +
    scale_y_continuous(limits = c(ymin, 6500), breaks = c(0, 3250 , 6500), labels = scales::comma) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    labs(y = "TWh") +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.x = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)

##### Low Total #####
df_21 = low %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = low %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_35 = low %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

 

data_Low <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

dots_Low = ggplot(data = data_Low, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"Low or Zero Emitting Generation") +
    scale_y_continuous(limits = c(ymin, 6500), breaks = c(0, 3250 , 6500)) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.y = element_blank(), 
          axis.text.y = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)

##### High Total #####
df_21 = high %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = high %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))

df_35 = high %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

 

data_High <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

dots_High = ggplot(data = data_High, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"High Emitting Generation") +
    scale_y_continuous(limits = c(ymin, 6500), breaks = c(0, 3250 , 6500)) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.y = element_blank(), 
          axis.text.y = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)

##### Nuclear #####
df_21 = individual[individual$variable_rename == "Nuclear", ] %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = individual[individual$variable_rename == "Nuclear", ] %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_35 = individual[individual$variable_rename == "Nuclear", ] %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

 

data_Nuclear <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

dots_Nuclear = ggplot(data = data_Nuclear, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"Nuclear") +
    scale_y_continuous(limits = c(ymin, 2600), breaks = c(0, 1300 , 2600)) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.y = element_blank(), 
          axis.text.y = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)

##### Solar #####
df_21 = individual[individual$variable_rename == "Solar", ] %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = individual[individual$variable_rename == "Solar", ] %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_35 = individual[individual$variable_rename == "Solar", ] %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

 

data_Solar <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

dots_Solar = ggplot(data = data_Solar, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"Solar") +
    scale_y_continuous(limits = c(ymin, 2600), breaks = c(0, 1300 , 2600)) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.y = element_blank(), 
          axis.text.y = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)

##### Wind #####

df_21 = individual[individual$variable_rename == "Wind", ] %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = individual[individual$variable_rename == "Wind", ] %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_35 = individual[individual$variable_rename == "Wind", ] %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

 

data_Wind <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

dots_Wind = ggplot(data = data_Wind, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"Wind") +
    scale_y_continuous(limits = c(ymin, 2600), breaks = c(0, 1300 , 2600), labels = scales::comma) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    labs(y = "TWh") +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.x = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)

##### CCS #####

df_21 = individual[individual$variable_rename == "CCS", ] %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = individual[individual$variable_rename == "CCS", ] %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_35 = individual[individual$variable_rename == "CCS", ] %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

 

data_CCS <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

dots_CCS = ggplot(data = data_CCS, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"CCS") +
    scale_y_continuous(limits = c(ymin, 2600), breaks = c(0, 1300 , 2600)) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.y = element_blank(), 
          axis.text.y = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)

##### Coal #####
df_21 = individual[individual$variable_rename == "Coal", ] %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = individual[individual$variable_rename == "Coal", ] %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_35 = individual[individual$variable_rename == "Coal", ] %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

 

data_Coal <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

dots_Coal = ggplot(data = data_Coal, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"Coal") +
    scale_y_continuous(limits = c(ymin, 2600), breaks = c(0, 1300 , 2600), labels = scales::comma) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    labs(y = "TWh") +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.x = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)

##### Gas #####
df_21 = individual[individual$variable_rename == "Natural Gas", ] %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = individual[individual$variable_rename == "Natural Gas", ] %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_35 = individual[individual$variable_rename == "Natural Gas", ] %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

 

data_Gas <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

dots_Gas = ggplot(data = data_Gas, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"Natural Gas") +
    scale_y_continuous(limits = c(ymin, 2600), breaks = c(0, 1300 , 2600)) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.y = element_blank(), 
          axis.text.y = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)

##### Other #####
df_21 = individual[individual$variable_rename == "Other", ] %>%
  filter(year %in% c(2021))
df_stat_21 = df_21 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = individual[individual$variable_rename == "Other", ] %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_35 = individual[individual$variable_rename == "Other", ] %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2030, 2035, 2030, 2035), "metric" = c("mean","mean","median","median"), 
                   "difference" = c(mean_diff_30, mean_diff_35,median_diff_30, median_diff_35))

data = rbind(df_21, df_30, df_35) 

 

data_Other <- data %>%
  mutate(axe = case_when(
    year == 2021 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  mutate(scenario = case_when(
    year == 2021 ~ "Historic", 
    T ~ scenario)
  )

dots_Other = ggplot(data = data_Other, aes(x = axe, y = value,  color = scenario)) +
  geom_point(aes(alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = -0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
    facet_wrap(~"Other") +
    scale_y_continuous(limits = c(ymin, 2600), breaks = c(0, 1300 , 2600)) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2021", "2030", "2035")) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.y = element_blank(), 
          axis.text.y = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none", 
          plot.margin = margin(0,0,0,0)) + 
  scale_alpha(range = c(0.6, 1), guide = F)

##### Final #####
final = (dots_Total | dots_Low | dots_High) / (dots_Wind | dots_Solar | dots_Nuclear | dots_CCS) / (dots_Coal | dots_Gas | dots_Other) 

final = final + 
  plot_layout(
  guides = "collect"
) & theme(legend.position = "bottom")
final

ggsave(filename = "output/final_figures/Fig2.4.svg", plot = final,width = 9, height = 8, units = "in")

ggsave(filename = "output/final_figures/Fig2.4.png", plot = final,width = 9, height = 8, units = "in")
```

### Table 2.4 Total

```{r}

title = "Total Electricity Generation"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 16, "United States")

fig$data <- fig$data %>%
  filter(year == 2005 | year == 2021 | year == 2030 | year == 2035)%>%
  filter(!model == "EIA") %>%
  filter(!model == "EIA-STEO") %>%
  mutate(value = value/0.0036, 
         unit = "TWh")

total <- fig$data %>%
  group_by(scenario, model, year) %>%
  summarise(value = sum(value)) %>%
  mutate(variable_rename = "Total")

base <- total %>%
  filter(year == 2005 & model == "EIA-LTS")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (TWh)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (TWh)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (TWh)`)

NoIRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (TWh)` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)


IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)


IRA$`Absolute Level (TWh)` = round(IRA$`Absolute Level (TWh)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (TWh)` = round(IRA$`Reductions from No IRA (TWh)`,3)

write.csv(IRA, paste0("./output/leep/", title, ".csv"), row.names = F)

IRA %>%
tableHTML(caption = paste(title), rownames = F)




```

### Table 2.4 Low

```{r}

title = "Low Emitting Electricity Generation"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 16, "United States")

fig$data <- fig$data %>%
  filter(year == 2005 | year == 2021 | year == 2030 | year == 2035)%>%
  filter(!model == "EIA") %>%
  filter(!model == "EIA-STEO") %>%
  mutate(value = value/0.0036, 
         unit = "TWh")

total <- fig$data %>%
  filter(variable_rename == "CCS" | 
         variable_rename == "Other" |
         variable_rename == "Nuclear" |
         variable_rename == "Solar" |
         variable_rename == "Wind"
) %>%
  group_by(scenario, model, year) %>%
  summarise(value = sum(value)) %>%
  mutate(variable_rename = "Total_Low")

base <- total %>%
  filter(year == 2005 & model == "EIA-LTS")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (TWh)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (TWh)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (TWh)`)

NoIRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (TWh)` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)



IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

IRA$`Absolute Level (TWh)` = round(IRA$`Absolute Level (TWh)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (TWh)` = round(IRA$`Reductions from No IRA (TWh)`,3)

write.csv(IRA, paste0("./output/leep/", title, ".csv"), row.names = F)

IRA %>%
tableHTML(caption = paste(title), rownames = F)




```

### Table 2.4 High

```{r}

title = "High Emitting Electricity Generation"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 16, "United States")

fig$data <- fig$data %>%
  filter(year == 2005 | year == 2021 | year == 2030 | year == 2035)%>%
  filter(!model == "EIA") %>%
  filter(!model == "EIA-STEO") %>%
  mutate(value = value/0.0036, 
         unit = "TWh")

total <- fig$data %>%
  filter(variable_rename == "Coal" |
         variable_rename == "Natural Gas" |
         variable_rename == "Oil"
) %>%
  group_by(scenario, model, year) %>%
  summarise(value = sum(value)) %>%
  mutate(variable_rename = "Total_High")

base <- total %>%
  filter(year == 2005 & model == "EIA-LTS")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (TWh)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (TWh)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (TWh)`)

NoIRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (TWh)` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)



IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

IRA$`Absolute Level (TWh)` = round(IRA$`Absolute Level (TWh)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (TWh)` = round(IRA$`Reductions from No IRA (TWh)`,3)

write.csv(IRA, paste0("./output/leep/", title, ".csv"), row.names = F)

IRA %>%
tableHTML(caption = paste(title), rownames = F)




```

### Table 2.4 Wind

```{r}

title = "Wind Electricity Generation"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 16, "United States")

fig$data <- fig$data %>%
  filter(year == 2005 | year == 2021 | year == 2030 | year == 2035)%>%
  filter(!model == "EIA") %>%
  filter(!model == "EIA-STEO") %>%
  mutate(value = value/0.0036, 
         unit = "TWh")

total <- fig$data %>%
  mutate(
    variable_rename = case_when(variable_rename == "Oil" ~ "Other", 
                                T ~ variable_rename)
  ) %>%
  group_by(year, variable_rename, model, scenario) %>%
  summarise(value = sum(value)) %>%
  filter(variable_rename == "Wind")

base <- total %>%
  filter(year == 2005 & model == "EIA-LTS")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (TWh)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (TWh)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (TWh)`)

NoIRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (TWh)` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)



IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

IRA$`Absolute Level (TWh)` = round(IRA$`Absolute Level (TWh)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (TWh)` = round(IRA$`Reductions from No IRA (TWh)`,3)

write.csv(IRA, paste0("./output/leep/", title, ".csv"), row.names = F)

IRA %>%
tableHTML(caption = paste(title), rownames = F)




```

### Table 2.4 Solar

```{r}

title = "Solar Electricity Generation"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 16, "United States")

fig$data <- fig$data %>%
  filter(year == 2005 | year == 2021 | year == 2030 | year == 2035)%>%
  filter(!model == "EIA") %>%
  filter(!model == "EIA-STEO") %>%
  mutate(value = value/0.0036, 
         unit = "TWh")

total <- fig$data %>%
  mutate(
    variable_rename = case_when(variable_rename == "Oil" ~ "Other", 
                                T ~ variable_rename)
  ) %>%
  group_by(year, variable_rename, model, scenario) %>%
  summarise(value = sum(value)) %>%
  filter(variable_rename == "Solar")

base <- total %>%
  filter(year == 2005 & model == "EIA-LTS")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (TWh)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (TWh)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (TWh)`)

NoIRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (TWh)` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)



IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

IRA$`Absolute Level (TWh)` = round(IRA$`Absolute Level (TWh)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (TWh)` = round(IRA$`Reductions from No IRA (TWh)`,3)

write.csv(IRA, paste0("./output/leep/", title, ".csv"), row.names = F)

IRA %>%
tableHTML(caption = paste(title), rownames = F)




```

### Table 2.4 Nuclear

```{r}

title = "Nuclear Electricity Generation"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 16, "United States")

fig$data <- fig$data %>%
  filter(year == 2005 | year == 2021 | year == 2030 | year == 2035)%>%
  filter(!model == "EIA") %>%
  filter(!model == "EIA-STEO") %>%
  mutate(value = value/0.0036, 
         unit = "TWh")

total <- fig$data %>%
  mutate(
    variable_rename = case_when(variable_rename == "Oil" ~ "Other", 
                                T ~ variable_rename)
  ) %>%
  group_by(year, variable_rename, model, scenario) %>%
  summarise(value = sum(value)) %>%
  filter(variable_rename == "Nuclear")

base <- total %>%
  filter(year == 2005 & model == "EIA-LTS")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (TWh)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (TWh)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (TWh)`)

NoIRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (TWh)` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)



IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

IRA$`Absolute Level (TWh)` = round(IRA$`Absolute Level (TWh)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (TWh)` = round(IRA$`Reductions from No IRA (TWh)`,3)

write.csv(IRA, paste0("./output/leep/", title, ".csv"), row.names = F)

IRA %>%
tableHTML(caption = paste(title), rownames = F)




```

### Table 2.4 CCS

```{r}

title = "CCS Electricity Generation"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 16, "United States")

fig$data <- fig$data %>%
  filter(year == 2005 | year == 2021 | year == 2030 | year == 2035)%>%
  filter(!model == "EIA") %>%
  filter(!model == "EIA-STEO") %>%
  mutate(value = value/0.0036, 
         unit = "TWh")

total <- fig$data %>%
  mutate(
    variable_rename = case_when(variable_rename == "Oil" ~ "Other", 
                                T ~ variable_rename)
  ) %>%
  group_by(year, variable_rename, model, scenario) %>%
  summarise(value = sum(value)) %>%
  filter(variable_rename == "CCS")

base <- total %>%
  filter(year == 2005 & model == "EIA-LTS")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (TWh)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (TWh)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (TWh)`)

NoIRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (TWh)` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)



IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

IRA$`Absolute Level (TWh)` = round(IRA$`Absolute Level (TWh)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (TWh)` = round(IRA$`Reductions from No IRA (TWh)`,3)

write.csv(IRA, paste0("./output/leep/", title, ".csv"), row.names = F)

IRA %>%
tableHTML(caption = paste(title), rownames = F)




```

### Table 2.4 Coal

```{r}

title = "Coal Electricity Generation"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 16, "United States")

fig$data <- fig$data %>%
  filter(year == 2005 | year == 2021 | year == 2030 | year == 2035)%>%
  filter(!model == "EIA") %>%
  filter(!model == "EIA-STEO") %>%
  mutate(value = value/0.0036, 
         unit = "TWh")

total <- fig$data %>%
  mutate(
    variable_rename = case_when(variable_rename == "Oil" ~ "Other", 
                                T ~ variable_rename)
  ) %>%
  group_by(year, variable_rename, model, scenario) %>%
  summarise(value = sum(value)) %>%
  filter(variable_rename == "Coal")

base <- total %>%
  filter(year == 2005 & model == "EIA-LTS")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (TWh)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (TWh)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (TWh)`)

NoIRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (TWh)` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)



IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

IRA$`Absolute Level (TWh)` = round(IRA$`Absolute Level (TWh)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (TWh)` = round(IRA$`Reductions from No IRA (TWh)`,3)

write.csv(IRA, paste0("./output/leep/", title, ".csv"), row.names = F)

IRA %>%
tableHTML(caption = paste(title), rownames = F)




```

### Table 2.4 Gas

```{r}

title = "Nautural Gas Electricity Generation"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 16, "United States")

fig$data <- fig$data %>%
  filter(year == 2005 | year == 2021 | year == 2030 | year == 2035)%>%
  filter(!model == "EIA") %>%
  filter(!model == "EIA-STEO") %>%
  mutate(value = value/0.0036, 
         unit = "TWh")

total <- fig$data %>%
  mutate(
    variable_rename = case_when(variable_rename == "Oil" ~ "Other", 
                                T ~ variable_rename)
  ) %>%
  group_by(year, variable_rename, model, scenario) %>%
  summarise(value = sum(value)) %>%
  filter(variable_rename == "Natural Gas")

base <- total %>%
  filter(year == 2005 & model == "EIA-LTS")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (TWh)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (TWh)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (TWh)`)

NoIRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (TWh)` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)



IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

IRA$`Absolute Level (TWh)` = round(IRA$`Absolute Level (TWh)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (TWh)` = round(IRA$`Reductions from No IRA (TWh)`,3)

write.csv(IRA, paste0("./output/leep/", title, ".csv"), row.names = F)

IRA %>%
tableHTML(caption = paste(title), rownames = F)




```

### Table 2.4 Other

```{r}

title = "Other Electricity Generation"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 16, "United States")

fig$data <- fig$data %>%
  filter(year == 2005 | year == 2021 | year == 2030 | year == 2035)%>%
  filter(!model == "EIA") %>%
  filter(!model == "EIA-STEO") %>%
  mutate(value = value/0.0036, 
         unit = "TWh")

total <- fig$data %>%
  mutate(
    variable_rename = case_when(variable_rename == "Oil" ~ "Other", 
                                T ~ variable_rename)
  ) %>%
  group_by(year, variable_rename, model, scenario) %>%
  summarise(value = sum(value)) %>%
  filter(variable_rename == "Other")

base <- total %>%
  filter(year == 2005 & model == "EIA-LTS")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (TWh)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (TWh)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (TWh)`)

NoIRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (TWh)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- total %>%
  filter(year == 2021 | year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (TWh)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (TWh)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)/NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (TWh)` = case_when(
            year == 2021 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2021 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2021 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (TWh)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (TWh)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (TWh)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)



IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

IRA$`Absolute Level (TWh)` = round(IRA$`Absolute Level (TWh)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (TWh)` = round(IRA$`Reductions from No IRA (TWh)`,3)

write.csv(IRA, paste0("./output/leep/", title, ".csv"), row.names = F)

IRA %>%
tableHTML(caption = paste(title), rownames = F)
```

