---
title: "Chapter 3: Transportation"
output: 
  html_document:
    toc: true
    toc_float: true
date: "`r Sys.time()`"
params:
  mode: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = here::here())
```

```{r}
if(is.null(params$mode)) {
  source("packages.R")
  devtools::load_all()
}

# load data from targets pipeline
targets::tar_load(config)
targets::tar_load(clean_data)
targets::tar_load(figmap_leep_timeseries)
targets::tar_load(figmap_leep_cone)
targets::tar_load(figmap_leep_stackbar)
targets::tar_load(data_min)
targets::tar_load(data_raw)

# temporary filter on clean data
clean_data = clean_data %>%
  filter(!(model == "IPM-EPA" & year == 2025))
```

## 3.1 co2 emissions from the transportation sector in the us compared to economy-wide co2 emissions

```{r}
fig_no = "3.1.trnco2_direct_indirect"

subpalettes = create_subpalettes(figmap_leep_stackbar, config)

dta2 = data_from_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 9, "United States") %>%
  mutate(variable_rename = case_when(
    variable_rename == "Transportation: Direct" ~ variable_rename,
    variable_rename == "Transportation: Indirect" ~ variable_rename,
    TRUE ~ "Other Sectors"
  )) %>%
  mutate(variable_rename = factor(variable_rename, 
                                  levels = c("Transportation: Direct", "Transportation: Indirect", "Other Sectors")))

p2 = emis_stack(dta2, "Transportation CO2 Emissions", figmap_leep_stackbar, config) + 
  scale_fill_manual(values = c("Other Sectors" = "white", "Transportation: Indirect" = subpalettes$`Emissions Stack`[["Transportation: Indirect"]], "Transportation: Direct" = subpalettes$`Emissions Stack`[["Transportation: Direct"]])) + 
  scale_color_manual(values = c("Other Sectors" = "#CECECE", "Transportation: Indirect" = "#CECECE", "Transportation: Direct" = "#CECECE")) +
  scale_alpha_manual(values = c("Other Sectors" = 0.5, "Transportation: Indirect" = 1, "Transportation: Direct" = 1))
p2

dta2 = clean_supplemental_data(dta2, fig_no)

saveall(p2, dta2, fig_no)
```

## 3.2 co2 emissions from the transportation sector in the us by end use

```{r}
fig_no = "3.2.trnco2_breakout"

subpalettes = create_subpalettes(figmap_leep_stackbar, config)
sp = subpalettes$`Transportation CO2`

dta = data_from_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 3, "United States")

fig = print_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 3, "United States", 
                  level_var = c("Other", "Pipelines", "Water", 
                                "Aircraft", "MHD Trucks", "LD Trucks", "Passenger Cars")) +
  # scale_fill_manual(labels = c("Passenger Cars", "LD Trucks", "MHD Trucks", "Aircraft", "Water", "Pipelines", "Other"),
  #                   breaks = c("Passenger Cars", "LD Trucks", "MHD Trucks", "Aircraft", "Water", "Pipelines", "Other"),
  #                   values = c(sp[['Passenger Cars']], sp[['LD Trucks']], sp[['MHD Trucks']], sp[['Aircraft']],
  #                              sp[['Water']], sp[['Pipelines']], sp[['Other']])) +
  scale_y_continuous(expand = c(0,0), limits = c(0,2000), labels = scales::comma,
                     name = expression(paste("Emissions (Mt C",O[2],"/yr)"))) +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5), plot.title = element_blank(),
        axis.ticks.x = element_blank(), legend.position = "right", 
        axis.ticks.y = element_line(color = "black"), 
        axis.ticks.length = unit(-0.15, "cm")
        )

fig

dta = clean_supplemental_data(dta, fig_no)

saveall(fig, dta, fig_no)
```

## 3.3 total co2 emissions in the transportation sector

```{r}
fig_no = "3.3.trnco2_projection"

Tran_data = spg_clean(
  19, 
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "Haiku-RFF"),
  "EPA-GHGI", 
  config, 
  clean_data, 
  figmap_leep_timeseries
)

TranSpg = spg2(
  Tran_data,
  "",
  expression(paste("Transportation C", O[2], "Emissions (Mt C", O[2], "/yr)")),
  gd = "none",
  0,
  2500,
  c(0, 500, 1000, 1500, 2000, 2500),
  scales::comma, 
  1, 
  c(2015, 2000), 
  c(2030, 2100), 
  c(2025, 1250), 
  config, 
  figmap_leep_timeseries) 

fig = dotted(TranSpg$data, TranSpg$figure, "median", 0, 2500, config, figmap_leep_timeseries)
fig
TranSpg$data = clean_supplemental_data(TranSpg$data, fig_no)
TranSpg$data = TranSpg$data %>%
  mutate(figure_num = paste0(fig_no,"_main"))

saveall(fig, data.frame(), paste0(fig_no, "_main"))

delta = delta(27, c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "Haiku-RFF"), config, clean_data, figmap_leep_timeseries)
saveall(delta$figure, data.frame(), paste0(fig_no, "_delta"), wd = 3.012, ht = 3)

delta$df = delta$df %>%
  mutate(variable = "Emissions|CO2|Energy|Demand|Transportation|Total|% Difference from No IRA",
         unit = "%",
         figure_num = paste0(fig_no,"_delta")) %>%
  rename("label" = "variable_rename")
  

#TranSpg$data = clean_supplemental_data(TranSpg$data, fig_no)

data_combo = bind_rows(TranSpg$data, delta$df)
savedata(data_combo,fig_no)


html(TranSpg$data, "Transportation CO2")
```

## 3.4 electric vehicle percent share of new sales

```{r}
fig_no = "3.4.ev_salesshare"

# TODO: NEMS-OP should only have reporting every 5 years

# clean_data_evshare = spg_clean(ts_map_ID = 118, drop = c(""), histsrc = "EPA-ATR", 
#                            config = config, clean_data = clean_data4, figmap_leep_timeseries = figmap_leep_timeseries)
scen_map = read.csv("./data-raw/scenario-mapping.csv") %>% select(datasrc, model, scenario, model_new, scenario_new)

raw = data_raw %>% select(model, scenario, region, variable, unit, datasrc, year, value) %>%
  left_join(scen_map, by = c("datasrc", "model", "scenario")) %>%
  select(-c(model, scenario)) %>%
  rename(model = model_new) %>%
  rename(scenario = scenario_new) %>%
  filter(unit != "thousands") %>%
  filter(!(model == "EPA-ATR" & year >= 2022))

atr_2022 = raw %>% filter(model == "EPA-ATR", year == 2021) %>% mutate(year = 2022)

nems = data_min %>% select(model, scenario, region, variable, unit, datasrc, year, value) %>%
  filter(model == "OP-NEMS", 
         scenario %in% c("OP IRA Moderate", "OP No New Policies"),
         datasrc != "LTS_data_small.xlsx",
         grepl("Sales Share", variable),
         unit == "%") %>%
  left_join(scen_map, by = c("datasrc", "model", "scenario")) %>%
  select(-c(model, scenario)) %>%
  rename(model = model_new) %>%
  rename(scenario = scenario_new) %>%
  mutate(model = case_when(
    model == "OP-NEMS" ~ "NEMS-OP",
    TRUE ~ model
  )) 

pnnl = data_min %>% select(model, scenario, region, variable, unit, datasrc, year, value) %>%
  filter(model == "GCAM6.0", 
         scenario %in% c("IRA", "NoIRA"),
         grepl("Sales Share", variable),
         unit == "%") %>%
  left_join(scen_map, by = c("datasrc", "model", "scenario")) %>%
  select(-c(model, scenario)) %>%
  rename(model = model_new) %>%
  rename(scenario = scenario_new) %>%
  mutate(value = value / 100)

eia = data_min %>% select(model, scenario, region, variable, unit, datasrc, year, value) %>%
  filter(model == "AEO 2023", 
         scenario %in% c("AEO23 Ref", "AEO23 No IRA"),
         grepl("Sales Share", variable),
         unit == "%") %>%
  filter(grepl("BEV", variable) | grepl("PHEV", variable)) %>%
  left_join(scen_map, by = c("datasrc", "model", "scenario")) %>%
  select(-c(model, scenario)) %>%
  rename(model = model_new) %>%
  rename(scenario = scenario_new)
  
clean_data_evshare = rbind(raw, atr_2022, nems, pnnl, eia) %>% 
  filter(unit != "thousands") %>% 
  mutate(value = 100 * value) %>%
  filter(model != "EIA-LTS") %>% 
  duplicate_historical_data("EPA-ATR", 2022, criteria = TRUE) %>% 
  mutate(
    variable = case_when(
      variable %in% c(
        "Energy Service|Transportation|Passenger|BEV|Sales Share",
        # "Energy Service|Transportation|Passenger|FCEV|Sales Share",
        # "Energy Service|Transportation|Passenger|HEV|Sales Share",
        # "Energy Service|Transportation|Freight|BEV|Sales Share",
        # "Energy Service|Transportation|Freight|FCEV|Sales Share",
        "Energy Service|Transportation|Passenger|PHEV|Sales Share",
        "Energy Service|Transportation|Passenger|BEV and PHEV|Sales Share"
        ) ~ 
        "Energy Service|Transportation|Passenger|BEV and PHEV|Sales Share")) %>%
  group_by(model, scenario, unit, datasrc, year, region, variable) %>%
  summarize(value = sum(value)) %>%
  filter(!(is.na(variable))) %>%
  filter(year <= 2035) %>%
#  filter(!(model %in% c("NEMS-OP-LTS"))) %>%
  filter(!(datasrc %in% c("LTS_data_small.xlsx"))) %>%
  mutate(variable_rename = variable) %>%
  mutate(alpha = case_when(
      model == "USREP-ReEDS" ~ 1,
      model == "GCAM-PNNL" ~ 1,
      model == "IPM-EPA" ~ 1,
      scenario == "Historic" ~ 1,
      T ~ 1
  )) %>%
  #duplicate_historical_data("EPA-ATR", 2022, criteria = TRUE) %>%
  mutate(value = case_when(year == 2022 ~ 100 * atr_2022$value[1], 
                           TRUE ~ value))

output = spg2_2010(df = clean_data_evshare, title = "", yname = expression("EV Sales Share (%)"), gd = "none", ymin = 0, ymax = 100, 
              ybreaks = waiver(), yax_format = waiver(), annotate = 1, 
              historic_coord = c(2015,8), preira_coord = c(2030, 9), ira_coord = c(2027, 52),
              config = config, figmap_leep_timeseries = figmap_leep_timeseries)
output$figure

figure = output$figure

ev_share_data = output$data
ev_share_data = clean_supplemental_data(ev_share_data, fig_no)
figure_full = dotted(clean_data_evshare, figure, "median", ymin = 0, ymax = 100, 
                config = config, figmap_leep_timeseries = figmap_leep_timeseries)

stats = ev_share_data %>%
  filter(year %in% c(2030, 2035)) %>%
  group_by(variable, year, scenario) %>%
  summarize(min = min(value), 
            median = median(value),
            max = max(value))

stats

saveall(figure_full, ev_share_data, fig_no)

```


```{r, eval = FALSE}
# fig_no = 3.4
# 
# scen_map = read.csv("./data-raw/scenario-mapping.csv") %>% select(datasrc, model, scenario, model_new, scenario_new)
# 
# raw = data_raw %>% select(model, scenario, region, variable, unit, datasrc, year, value) %>%
#   left_join(scen_map, by = c("datasrc", "model", "scenario")) %>%
#   select(-c(model, scenario)) %>%
#   rename(model = model_new) %>%
#   rename(scenario = scenario_new) %>%
#   filter(unit != "thousands") %>%
#   filter(!(model == "EPA-ATR" & year >= 2022))
# 
# atr_2022 = raw %>% filter(model == "EPA-ATR", year == 2021) %>% mutate(year = 2022)
# nems = data_min %>% select(model, scenario, region, variable, unit, datasrc, year, value) %>%
#   filter(model == "NEMS-OP", grepl("Sales Share", variable),
#          unit == "%") %>%
#   left_join(scen_map, by = c("datasrc", "model", "scenario")) %>%
#   select(-c(model, scenario)) %>%
#   rename(model = model_new) %>%
#   rename(scenario = scenario_new)
# 
# clean_data4 = rbind(raw, atr_2022, nems) %>% 
#   filter(unit != "thousands") %>% 
#   mutate(value = 100 * value) %>%
#   filter(model != "EIA-LTS") %>% 
#   duplicate_historical_data("EPA-ATR", 2022, criteria = TRUE) %>% mutate(
#     variable = case_when(
#       variable %in% c(
#         "Energy Service|Transportation|Passenger|BEV|Sales Share",
#         # "Energy Service|Transportation|Passenger|FCEV|Sales Share",
#         # "Energy Service|Transportation|Passenger|HEV|Sales Share",
#         # "Energy Service|Transportation|Freight|BEV|Sales Share",
#         # "Energy Service|Transportation|Freight|FCEV|Sales Share",
#         "Energy Service|Transportation|Passenger|PHEV|Sales Share",
#         "Energy Service|Transportation|Passenger|BEV and PHEV|Sales Share"
#         ) ~ 
#         "Energy Service|Transportation|Passenger|BEV and PHEV|Sales Share")) %>%
#   group_by(model, scenario, unit, datasrc, year, region, variable) %>%
#   summarize(value = sum(value)) %>%
#   filter(!(is.na(variable))) %>%
#   mutate(alpha = case_when(
#     model == "USREP-ReEDS" ~ 1,
#     model == "GCAM-PNNL" ~ 1,
#     model == "NEMS-OP" ~ 1,
#     scenario == "Historic" ~ 1,
#     TRUE ~ 0.8)
#   ) %>%
#   mutate(value = case_when(year == 2022 & model == "NEMS-OP" ~ 100 * atr_2022$value[1], 
#                            TRUE ~ value))
# 
# fig = print_graph("time_series", config, clean_data4, figmap_leep_timeseries, 118, "United States")
# fig
# dta = data_from_graph("time_series", config, clean_data4, figmap_leep_timeseries, 118, "United States")
# dta = clean_supplemental_data(dta, fig_no)
# 
# p = dot_plots("time_series", config, clean_data4, figmap_leep_timeseries, 118, "United States", 0, 100, "EV Share", metric = "median", hist_year = 2022, historic_coord = c(2015,8), preira_coord = c(2030, 10), ira_coord = c(2027, 53), ylab = "EV Sales Share (%)")
# p$full
# 
# print(p$stats)
# 
# saveall(p$full, dta, fig_no)
```

## 3.5 electricity demand from light-duty vehicles in the transportation sector

```{r}
fig_no = "3.5.elc_ldv"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 24, "United States")

ymin = 0
ymin = 700
metric = "median"

data <- fig$data %>%
  filter(year == 2025 | year == 2030 | year == 2035)%>%
  mutate(alpha = case_when(
    model == "USREP-ReEDS" ~ 1, 
    model == "GCAM-PNNL" ~ 1, 
    model == "IPM-EPA" ~ 1,
    scenario == "Historic" ~ 1,
    T ~ 1
  ))%>%
  mutate(value = value/0.0036, 
         unit = "TWh")

df_25 = data %>%
  filter(year %in% c(2025))
df_stat_25 = df_25 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_30 = data %>%
  filter(year %in% c(2030))
df_stat_30 = df_30 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

df_35 = data %>%
  filter(year %in% c(2035))
df_stat_35 = df_35 %>%
  group_by(scenario,year,variable_rename) %>%
  summarise(mean = mean(value),
            median = median(value))
  

mean_diff_25 = df_stat_30[df_stat_25$scenario == "No IRA","mean"]$mean - df_stat_25[df_stat_25$scenario == "IRA","mean"]$mean
median_diff_25 = df_stat_35[df_stat_25$scenario == "No IRA","median"]$median - df_stat_25[df_stat_25$scenario == "IRA","median"]$median

mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean

median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median

stats = data.frame("year" = c(2025, 2030, 2035, 2025,  2030, 2035), "metric" = c("mean","mean", "mean", "median", "median","median"), 
                   "difference" = c(mean_diff_25, mean_diff_30, mean_diff_35, median_diff_25, median_diff_30, median_diff_35))

data = rbind(df_25, df_30, df_35) 

print("Light-Duty Vehicles")

data <- data %>%
  mutate(axe = case_when(
    year == 2025 ~ 1, 
    year == 2030 ~ 2, 
    year == 2035 ~ 3
  )) %>%
  filter(scenario == "No IRA" | scenario == "IRA")

subpalettes = create_subpalettes(figmap_leep_timeseries, config)
  subpalettes$`Emissions|CO2|Energy|Demand|Industry`[1] = "black"
    annoclr = subpalettes$`Emissions|CO2|Energy|Demand|Industry`
    histclr = annoclr[1]
    noIRAclr = annoclr[2]
    IRAclr = annoclr[3]

A = ggplot(data = data, aes(x = axe, y = value,  color = scenario, shape = scenario)) +
  geom_point(aes(alpha = alpha), size = 1.5, position = position_dodge(width = 0.5)) +
  geom_segment(data = df_stat_35, aes(x = 2.94, xend = 3.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_30, aes(x = 1.94, xend = 2.06, y = median, yend = median, color = scenario), size = 0.5) +
  geom_segment(data = df_stat_25, aes(x = 0.94, xend = 1.06, y = median, yend = median, color = scenario), size = 0.5) +
    scale_x_continuous(breaks = c(1,2,3), labels = c("2025", "2030", "2035")) +
    scale_shape_manual(values = c("IRA" = 1, "No IRA" = 2)) +
    theme_emf() +
    labs(y = expression("LDV Electricity Demand (TWh)")) +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(axis.title.x = element_blank(),
          axis.ticks.y = element_line(color = "black"),
          axis.ticks.x = element_blank(), 
          axis.ticks.length = unit(-0.15, "cm"),
          legend.position = "none") + 
  scale_alpha(range = c(1, 1), guide = F) + 
  annotate("text", x = 1.77, y = 325, label = "No IRA", color = noIRAclr, alpha = 1) +
  annotate("text", x = 2.17, y = 375, label = "IRA", color = IRAclr, alpha = 1) +
  ylim(0, 700)

print(A)

data = clean_supplemental_data(data, fig_no)

saveall(A, data, fig_no, wd = 4, ht = 4)
```

### Table 3.5

```{r}
title = "Light Duty Vehicles"

fig = print_graph("time_series", config, clean_data, figmap_leep_timeseries, 24, "United States")

fig$data <- fig$data %>%
   mutate(value = value/0.0036)

base <- fig$data %>%
  filter(year == 2005 & model == "EPA-GHGI")

baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (Mt CO2)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (Mt CO2)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (Mt CO2)`)

NoIRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- fig$data %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (Mt CO2)` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)

IRA$`Absolute Level (Mt CO2)` = round(IRA$`Absolute Level (Mt CO2)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (Mt CO2)` = round(IRA$`Reductions from No IRA (Mt CO2)`,3)

IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

IRA %>%
tableHTML(caption = paste(title), rownames = F)
```

## sensitivities data

```{r}
sector = "transportation"
#metric = "absolute"
#metric = "percent"
metric = "percent_2005"

var_sens = "Emissions|CO2|Energy|Demand|Transportation|Total"

# electric sector emissions sensitivity dot plots
panel1_scens = c("Core","IRA", "IRA.Low","IRA.High")
panel2_scens = c("Low Growth", "High Growth", "IRA") # Economic Growth
panel3_scens = c("Low Energy Price","High Energy Price", "Core", "IRA") # Energy Prices
panel4_scens = c("All Advanced", "Adv Battery/Renew", "Cons Battery/Renew", "Constrained Deployment", "Core", "IRA") # Technology Cost and deployment constraints
panel5_scens = c("Pess-IRA.Adv", "Opt-IRA.Adv", "Core", "IRA") # Combos

sens_dta = clean_data %>% filter(variable == var_sens,
                                 year %in% c(2030, 2035)) #%>% 
#  mutate(year = factor(year))

print(max(sens_dta$value))
print(min(sens_dta$value))

filler = data.frame(year = c(2035), value = c(-200), scenario = c(""), model = c("NA"))

sens_dta_panel1 = sens_dta %>% filter(scenario %in% panel1_scens) %>%
  filter(model %in% c("EPS-EI", "GCAM-CGS","RIO-REPEAT","REGEN-EPRI",
                      "USREP-ReEDS")) %>%
  #filter(!(model == "ReEDS-NREL" & datasrc == "bistline_ira_tall.csv")) %>%
  mutate(scenario = case_when(scenario == "Core" ~ "IRA", TRUE ~ scenario)) %>%
  mutate(stagger = case_when(
    scenario == "IRA.Low" ~ -0.7,
    scenario == "IRA.High" ~ 0.7,
    TRUE ~ 0
  ))

sens_dta_panel2 = sens_dta %>% filter(scenario %in% panel2_scens) %>% 
  filter(model == "GCAM-PNNL") %>% 
  mutate(scenario = case_when((scenario == "IRA" | scenario == "Core") ~ "Mod", 
                              TRUE ~ scenario)) %>%
  mutate(scenario = case_when(
    scenario == "High Growth" ~ "High",
    scenario == "Low Growth" ~ "Low",
    TRUE ~ scenario
  ))

sens_dta_panel3 = sens_dta %>% filter(scenario %in% panel3_scens) %>%
  filter(model %in% c("ReEDS-NREL", "GCAM-PNNL")) %>% 
  filter(datasrc != "bistline_ira_tall.csv") %>%
  mutate(scenario = case_when((scenario == "IRA" | scenario == "Core") ~ "Mod", 
                              TRUE ~ scenario)) %>%
  mutate(scenario = case_when(
    scenario == "High Energy Price" ~ "High",
    scenario == "Low Energy Price" ~ "Low",
    TRUE ~ scenario
  )) %>%
  # mutate(scenario = case_when(model == "ReEDS-NREL" ~ paste0("R.",scenario),
  #                          model == "GCAM-PNNL" ~ paste0("GP.",scenario),
  #                          TRUE ~ scenario)) %>%
  mutate(stagger = case_when(model == "ReEDS-NREL" ~ 0.4,
                             model == "GCAM-PNNL" ~ -0.4,
                             TRUE ~ 0.0))

sens_dta_panel4 = sens_dta %>% filter(scenario %in% panel4_scens) %>% 
  filter(model %in% c("ReEDS-NREL", "USREP-ReEDS")) %>% 
  filter(datasrc != "bistline_ira_tall.csv") %>%
  mutate(scenario = case_when((scenario == "IRA" | scenario == "Core") ~ "Mod", 
                              TRUE ~ scenario)) %>%
  mutate(scenario = case_when(
    scenario == "Constrained Deployment" ~ "Constr",
    scenario == "All Advanced" ~ "All-Adv",
    scenario == "Adv Battery/Renew" ~ "Adv Renew",
    scenario == "Cons Battery/Renew" ~ "Cons Renew",
    TRUE ~ scenario
  )) %>%
  # mutate(scenario = case_when(model == "ReEDS-NREL" ~ paste0("R.",scenario),
  #                             model == "USREP-ReEDS" ~ paste0("UR.",scenario),
  #                             TRUE ~ scenario)) %>%
  mutate(stagger = case_when(model == "ReEDS-NREL" ~ -0.4,
                             model == "USREP-ReEDS" ~ +0.4,
                             TRUE ~ 0.0))
  
sens_dta_panel5 = sens_dta %>% filter(scenario %in% panel5_scens) %>%
  filter(model %in% c("USREP-ReEDS","NEMS-OP")) %>% 
  mutate(scenario = case_when((scenario == "IRA" | scenario == "Core") ~ "Mod", 
                              TRUE ~ scenario)) %>%
  mutate(scenario = case_when(
    scenario == "Pess-IRA.Adv" ~ "Pess-Adv",
    scenario == "Opt-IRA.Adv" ~ "Opt-Adv",
    TRUE ~ scenario
  )) %>%
  # mutate(scenario = case_when(model == "USREP-ReEDS" ~ paste0("UR.",scenario),
  #                          model == "NEMS-OP" ~ paste0("ON.",scenario),
  #                          TRUE ~ scenario)) %>%
  mutate(stagger = case_when(model == "USREP-ReEDS" ~ 0.4,
                             model == "NEMS-OP" ~ -0.4,
                             TRUE ~ 0.0))
  
  
## put things into table format

historic_emissions = (clean_data %>%
  filter(model == "EPA-GHGI",
         scenario == "Historic",
         variable == var_sens,
         year == 2005))$value

panel1_summ = sens_dta_panel1 %>%
  select(-c(stagger,datasrc,region)) %>%
  mutate(scenario = case_when(scenario == "IRA.High" ~ "Optimistic",
                              scenario == "IRA.Low" ~ "Pessimistic",
                              TRUE ~ "Core")) %>%
  pivot_wider(names_from = scenario, values_from = value, names_prefix = "value_")

if (metric == "absolute") {
  panel1_summ = panel1_summ %>%
      mutate(diff_opt = value_Optimistic - value_Core,
             diff_pess = value_Pessimistic - value_Core)
} else if (metric == "percent") {
  panel1_summ = panel1_summ %>%
      mutate(diff_opt = (value_Optimistic - value_Core) / value_Core,
             diff_pess = (value_Pessimistic - value_Core) / value_Core) 
} else if (metric == "percent_2005") {
  panel1_summ = panel1_summ %>%
      mutate(diff_opt = (value_Optimistic - value_Core) / historic_emissions,
             diff_pess = (value_Pessimistic - value_Core) / historic_emissions)
}

panel1_summ = panel1_summ %>%
  group_by(variable, unit, year) %>%
  summarize(opt_median = median(diff_opt),
            opt_min = min(diff_opt),
            opt_max = max(diff_opt),
            pess_median = median(diff_pess),
            pess_min = min(diff_pess),
            pess_max = max(diff_pess)) %>%
  pivot_longer(cols = starts_with(c("opt_","pess_")), names_to = c("scen","metric"), names_sep = "_") %>%
  #mutate(value = round(value,1)) %>%
  pivot_wider(names_from = scen, values_from = value) %>%
  rename(c("Optimistic" = "opt", "Pessimistic" = "pess"))

panel2_summ = sens_dta_panel2 %>%
  select(-c(datasrc,region)) %>%
  mutate(scenario = case_when(scenario == "High" ~ "Optimistic",
                              scenario == "Low" ~ "Pessimistic",
                              TRUE ~ "Core")) %>%
  pivot_wider(names_from = scenario, values_from = value, names_prefix = "value_")

if (metric == "absolute") {
  panel2_summ = panel2_summ %>%
      mutate(diff_opt = value_Optimistic - value_Core,
             diff_pess = value_Pessimistic - value_Core)
} else if (metric == "percent") {
  panel2_summ = panel2_summ %>%
      mutate(diff_opt = (value_Optimistic - value_Core) / value_Core,
             diff_pess = (value_Pessimistic - value_Core) / value_Core) 
}else if (metric == "percent_2005") {
  panel2_summ = panel2_summ %>%
      mutate(diff_opt = (value_Optimistic - value_Core) / historic_emissions,
             diff_pess = (value_Pessimistic - value_Core) / historic_emissions)
}

panel2_summ = panel2_summ %>%
  group_by(variable, unit, year) %>%
  summarize(opt_median = median(diff_opt),
            opt_min = min(diff_opt),
            opt_max = max(diff_opt),
            pess_median = median(diff_pess),
            pess_min = min(diff_pess),
            pess_max = max(diff_pess)) %>%
  pivot_longer(cols = starts_with(c("opt_","pess_")), names_to = c("scen","metric"), names_sep = "_") %>%
  #mutate(value = round(value,1)) %>%
  pivot_wider(names_from = scen, values_from = value) %>%
  rename(c("High Growth" = "opt", "Low Growth" = "pess")) %>%
  data.frame() %>%
  select(-c(variable,unit,year,metric))

panel3_summ = sens_dta_panel3 %>%
  select(-c(stagger,datasrc,region)) %>%
  mutate(scenario = case_when(scenario == "High" ~ "Optimistic",
                              scenario == "Low" ~ "Pessimistic",
                              TRUE ~ "Core")) %>%
  pivot_wider(names_from = scenario, values_from = value, names_prefix = "value_")

if (metric == "absolute") {
  panel3_summ = panel3_summ %>%
      mutate(diff_opt = value_Optimistic - value_Core,
             diff_pess = value_Pessimistic - value_Core)
} else if (metric == "percent") {
  panel3_summ = panel3_summ %>%
      mutate(diff_opt = (value_Optimistic - value_Core) / value_Core,
             diff_pess = (value_Pessimistic - value_Core) / value_Core) 
} else if (metric == "percent_2005") {
  panel3_summ = panel3_summ %>%
      mutate(diff_opt = (value_Optimistic - value_Core) / historic_emissions,
             diff_pess = (value_Pessimistic - value_Core) / historic_emissions)
}

panel3_summ = panel3_summ %>%
  group_by(variable, unit, year) %>%
  summarize(opt_median = median(diff_opt),
            opt_min = min(diff_opt),
            opt_max = max(diff_opt),
            pess_median = median(diff_pess),
            pess_min = min(diff_pess),
            pess_max = max(diff_pess)) %>%
  pivot_longer(cols = starts_with(c("opt_","pess_")), names_to = c("scen","metric"), names_sep = "_") %>%
  #mutate(value = round(value,1)) %>%
  pivot_wider(names_from = scen, values_from = value) %>%
  rename(c("High Price" = "opt", "Low Price" = "pess")) %>%
  data.frame() %>%
  select(-c(variable,unit,year,metric))

panel4_summ = sens_dta_panel4 %>%
  select(-c(stagger,datasrc,region)) %>%
  mutate(scenario = case_when(scenario == "Constr" ~ "Constr",
                              scenario == "All-Adv" ~ "AllAdv",
                              TRUE ~ "Core")) %>%
  pivot_wider(names_from = scenario, values_from = value, names_prefix = "value_") %>%
  mutate(value_Constr = case_when(is.na(value_Constr) ~ value_Core
                                            , TRUE ~ value_Constr))

if (metric == "absolute") {
  panel4_summ = panel4_summ %>%
      mutate(diff_constr = value_Constr - value_Core,
             diff_alladv = value_AllAdv - value_Core)
} else if (metric == "percent") {
  panel4_summ = panel4_summ %>%
      mutate(diff_constr = (value_Constr - value_Core) / value_Core,
             diff_alladv = (value_AllAdv - value_Core) / value_Core) 
} else if (metric == "percent_2005") {
  panel4_summ = panel4_summ %>%
      mutate(diff_constr = (value_Constr - value_Core) / historic_emissions,
             diff_alladv = (value_AllAdv - value_Core) / historic_emissions)
}

panel4_summ = panel4_summ %>%
  replace_with_na(replace = list(diff_opt = c(0), diff_pess = c(0),
                             diff_constr = c(0), diff_alladv = c(0))) %>%
  group_by(variable, unit, year) %>%
  summarize(constr_median = median(diff_constr, na.rm = T),
            constr_min = min(diff_constr, na.rm = T),
            constr_max = max(diff_constr, na.rm = T),
            alladv_median = median(diff_alladv, na.rm = T),
            alladv_min = min(diff_alladv, na.rm = T),
            alladv_max = max(diff_alladv, na.rm = T)) %>%
  pivot_longer(cols = starts_with(c("constr_","alladv_")), names_to = c("scen","metric"), names_sep = "_") %>%
  #mutate(value = round(value,1)) %>%
  pivot_wider(names_from = scen, values_from = value)  %>%
  mutate(constr = case_when((constr == Inf | constr == -Inf) ~ NA, TRUE ~ constr),
         alladv = case_when((alladv == Inf | alladv == -Inf) ~ NA, TRUE ~ alladv)) %>%
  rename(c("Constrained" = "constr",
           "All Adv" = "alladv")) %>%
  data.frame() %>%
  select(-c(variable,unit,year,metric))

panel5_summ = sens_dta_panel5 %>%
  select(-c(stagger,datasrc,region)) %>%
  mutate(scenario = case_when(scenario == "Opt-Adv" ~ "Optimistic",
                              scenario == "Pess-Adv" ~ "Pessimistic",
                              TRUE ~ "Core")) %>%
  pivot_wider(names_from = scenario, values_from = value, names_prefix = "value_") %>%
  mutate(value_Optimistic = case_when(is.na(value_Optimistic) ~ value_Core
                                            , TRUE ~ value_Optimistic),
         value_Pessimistic = case_when(is.na(value_Pessimistic) ~ value_Core
                                            , TRUE ~ value_Pessimistic))

if (metric == "absolute") {
  panel5_summ = panel5_summ %>%
      mutate(diff_opt = value_Optimistic - value_Core,
             diff_pess = value_Pessimistic - value_Core)
} else if (metric == "percent") {
  panel5_summ = panel5_summ %>%
      mutate(diff_opt = (value_Optimistic - value_Core) / value_Core,
             diff_pess = (value_Pessimistic - value_Core) / value_Core) 
} else if (metric == "percent_2005") {
  panel5_summ = panel5_summ %>%
      mutate(diff_opt = (value_Optimistic - value_Core) / historic_emissions,
             diff_pess = (value_Pessimistic - value_Core) / historic_emissions)
}

panel5_summ = panel5_summ %>%
  replace_with_na(replace = list(diff_opt = c(0), diff_pess = c(0),
                             diff_constr = c(0), diff_alladv = c(0))) %>%
  group_by(variable, unit, year) %>%
  summarize(opt_median = median(diff_opt, na.rm = T),
            opt_min = min(diff_opt, na.rm = T),
            opt_max = max(diff_opt, na.rm = T),
            pess_median = median(diff_pess, na.rm = T),
            pess_min = min(diff_pess, na.rm = T),
            pess_max = max(diff_pess, na.rm = T)) %>%
  pivot_longer(cols = starts_with(c("opt_","pess_")), names_to = c("scen","metric"), names_sep = "_") %>%
  #mutate(value = round(value,1)) %>%
  pivot_wider(names_from = scen, values_from = value) %>%
  rename(c("Opt-Adv" = "opt", "Pess-Adv" = "pess")) %>%
  data.frame() %>%
  select(-c(variable,unit,year,metric))

all_panels = cbind(panel1_summ, panel4_summ, panel5_summ, panel3_summ, panel2_summ)

#write_csv(all_panels, paste("output/final_figures/data/sensitivities_",sector,"_",metric,".csv"))
```
