---
title: "Template Presentation Figures"
author: "Ruying Gao"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 5
    theme: cerulean
    toc_float: 
      collapsed: true
      smooth_scroll: true
params:
  mode: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = here::here())
```

```{r, warning = FALSE}
if(is.null(params$mode)) {
  library(targets)
  library(tidyverse)
  library(here)
  library(glue)
  library(plotly)
  library(data.table)
  devtools::load_all(here())
}
```

# Part 0. Basic Setup 

Read in the necessary data

```{r data}
tar_load(config)
stopifnot(exists("config"))

tar_load(emf_data_long)
stopifnot(exists("emf_data_long"))

tar_load(emf_summary_long)
stopifnot(exists("emf_summary_long"))

tar_load(overview_sb_presentation_figmap)
stopifnot(exists("overview_sb_presentation_figmap"))

tar_load(overview_db_presentation_figmap)
stopifnot(exists("overview_db_presentation_figmap"))

tar_load(overview_ts_presentation_figmap)
stopifnot(exists("overview_ts_presentation_figmap"))
```

Set up file paths 

```{r file path setup}
overall_path = "./output/round1/template_presentation/"
subfolders = c("", "stacked_bar", "diff_bar", "time_series")
create_folders(sapply(subfolders, function(x) {paste(overall_path, x, sep = "")}))
```

# Part I. Stacked Bar
 
```{r stacked bar pre-processing, echo=FALSE}
plot_list <- overview_sb_presentation_figmap
# select the key variables, flip values, and merge with specific figure requests
df <- preliminary_data_processing_for_plotting(emf_data_long, plot_list)
# assign color palettes
subpalettes = create_subpalettes(plot_list)
```


```{r stacked bar pdf png, echo=FALSE}
# type = "stackedbar", "diffbar" or "ts" 
pdf_plots(overall_path, df, "overview", "stacked_bar", subpalettes)
png_plots(overall_path, df, "overview", "stacked_bar", subpalettes)
```

# Part 2. Difference Bar

1). Difference Bar: Load Data, Preliminary Processing, Create Directories, Assign colors 
 
```{r diif bar pre-processing, echo=FALSE}
plot_list <- overview_db_presentation_figmap
# select the key variables, flip values, and merge with specific figure requests
df <- preliminary_data_processing_for_plotting(emf_data_long, plot_list)
# assign color palettes
subpalettes = create_subpalettes(plot_list)
```
  
```{r diff bar pdf png, echo=FALSE}
pdf_plots(overall_path, df, "overview", "diff_bar", subpalettes)
png_plots(overall_path, df, "overview", "diff_bar", subpalettes)
```

# Part 3. Time Series
```{r time series pre-processing}
plot_list <- overview_ts_presentation_figmap
df <- preliminary_data_processing_for_plotting(emf_data_long, plot_list)
# assign color palettes
subpalettes = create_subpalettes(plot_list)
```

```{r time series pdf png, echo=FALSE}
pdf_plots(overall_path, df, "overview", "time_series", subpalettes)
png_plots(overall_path, df, "overview", "time_series", subpalettes)
```
