---
title: "Building Study Group Diff Bar Presentation Figures"
author: "Ruying Gao"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 5
    theme: cerulean
    toc_float: 
      collapsed: true
      smooth_scroll: true
params:
  plot_years: !r c(2050)
  mode: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = here::here())
```

```{r, warning = FALSE}
if(is.null(params$mode)) {
  library(targets)
  library(tidyverse)
  library(here)
  library(glue)
  library(plotly)
  library(data.table)
  devtools::load_all(here())
}
```

# Part 0. Basic Setup 

Read in the necessary data

```{r data}
tar_load(config)
stopifnot(exists("config"))

tar_load(emf_data_long)
stopifnot(exists("emf_data_long"))

tar_load(emf_summary_long)
stopifnot(exists("emf_summary_long"))

tar_load(bsg_db_presentation_figmap)
stopifnot(exists("bsg_db_presentation_figmap"))
```

# Part I. Data Processing

1). Load Data, Preliminary Processing, Create Directories, Assign colors 
 
```{r load and check plot list, echo=FALSE}
plot_list <- bsg_db_presentation_figmap
# check_figure_csv(plot_list, "diff")
```

```{r preliminary data processing, echo=FALSE}
# select the key variables, flip values, and merge with specific figure requests
df <- preliminary_data_processing_for_plotting(emf_data_long, plot_list)
```

```{r add color subpalettes, echo=FALSE}
figure_titles = unique(plot_list$title_name)

for (figure_title in figure_titles) {
  temp = plot_list %>% filter(title_name == figure_title) 
  var_palette = unique(temp$variable_rename)
  names(var_palette) = var_palette
  sub_palettes[[figure_title]] = var_palette
  sub_palettes = sub_palettes %>%
    map(~find_color(.x, color_map))
}
```


# Part 2. Figures

  
```{r diff bar pdf, echo=FALSE}
pdf(file=paste("output/round1/presentation/bsg_diffbar_presentation.pdf",sep=""), width = 14, height = 6)
print(paste("There are a total of ", length(unique(df$title_name)), " figures", sep = ""))
i = 0
for (figure in unique(df$title_name)) {
    print(figure)
    
    dat = df %>% 
      filter(title_name == figure) %>%
      diff_bar_figure_specific_data_processing()
    
    for (selected_region in unique(dat$region)) {
      dat_filtered = dat %>%
        filter(region == selected_region)
    
      if (check_dat_before_plotting(dat_filtered)) {
      if (unique(dat_filtered$type) == "grid") {
          bar_plot = stacked_bar_grid_plot_fn(df = dat_filtered, 
                            x = unique(dat_filtered$x), y = unique(dat_filtered$y), 
                            color = "variable_rename", 
                            facet1 = unique(dat_filtered$facet1), facet2 = unique(dat_filtered$facet2),
                          mapping_list = list(
                            xlab = unique(dat_filtered$x),
                             ylab= unique(dat_filtered$unit),
                             title = paste(figure, selected_region, sep = "-"),
                            model_color_palette = figure,
                            palettes = sub_palettes))
          
          if (unique(dat_filtered$line_request)) {
            bar_plot = bar_plot +
              geom_line(aes(y = .data[["diff_sum"]]))
          }
          
          print(bar_plot)
      } else if (unique(dat_filtered$type) == "wrap") {
          bar_plot = stacked_bar_plot_fn(df = dat_filtered, 
                            x = unique(dat_filtered$x), y = unique(dat_filtered$y), 
                            color = "variable_rename", 
                            facet = unique(dat_filtered$facet1),
                          mapping_list = list(
                            xlab = unique(dat_filtered$x),
                             ylab= unique(dat_filtered$unit),
                             title = paste(figure, selected_region, sep = "-"),
                            model_color_palette = figure,
                            palettes = sub_palettes))
          
          if (unique(dat_filtered$line_request)) {
            bar_plot = bar_plot +
              geom_line(aes(y = .data[["diff_sum"]]))
          }
      }
    }
    
    }
}
dev.off()
  
```

