---
title: "Stacked_Bar_Plots"
author: "Ruying Gao"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 5
    theme: cerulean
    toc_float: 
      collapsed: true
      smooth_scroll: true
params: 
  mode: NULL
---
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = here::here())
```

```{r, warning=FALSE}
if(is.null(params$mode)) {
  library(targets)
  library(tidyverse)
  library(here)
  library(glue)
  library(plotly)
  library(data.table)
  devtools::load_all(here())
}
```

# Part 0. Basic Setup 

Read in the necessary data

```{r data}
tar_load(config)
stopifnot(exists("config"))

tar_load(emf_data_long)
stopifnot(exists("emf_data_long"))

tar_load(emf_summary_long)
stopifnot(exists("emf_summary_long"))

tar_load(bsg_ts_presentation_figmap)
stopifnot(exists("bsg_ts_presentation_figmap"))
```

```{r path}
overall_path = "output/round1/bsg_presentation/"
```

# Presentation Figures

```{r merge}
plot_list <- bsg_ts_presentation_figmap
df <- preliminary_data_processing_for_plotting(emf_data_long, plot_list)
```


```{r add color subpalettes - stacked, echo=FALSE}
for (figure_title in unique(plot_list$title_name)) {
  temp = plot_list %>% filter(title_name == figure_title) 
  
  if (unique(temp$color) == "variable_rename") {
    var_palette = unique(temp$variable_rename)
  } else if (unique(temp$color) == "model") {
    var_palette = config[[unique(temp$models)]]
  }
  names(var_palette) = var_palette
  sub_palettes[[figure_title]] = var_palette
  sub_palettes = sub_palettes %>%
    map(~find_color(.x, color_map))
}
```


 
```{r time series pdf, echo=FALSE}
pdf(file=paste(overall_path, "bsg_time_series_presentation.pdf",sep=""), width = 14, height = 6)
print(paste("There are a total of ", length(unique(df$title_name)), " figures", sep = ""))
i = 0
for (figure in unique(df$title_name)) {
  
    print(figure)
    
    dat = df %>% 
      filter(title_name == figure) %>%
      time_series_figure_specific_data_processing()
    
    for (selected_region in unique(dat$region)) {
      dat_filtered = dat %>%
        filter(region == selected_region)
    
      if (check_dat_before_plotting(dat_filtered)) {
      if (unique(dat_filtered$type) == "grid") {
          print(time_series_grid_fn(df = dat_filtered, 
                            x = unique(dat_filtered$x), y = unique(dat_filtered$y), 
                            color = unique(dat_filtered$color), 
                            facet1 = unique(dat_filtered$facet1), facet2 = unique(dat_filtered$facet2),
                          mapping_list = list(
                            xlab = unique(dat_filtered$x),
                             ylab= unique(dat_filtered$unit),
                             title = paste(figure, selected_region, sep = "-"),
                            model_color_palette = figure,
                            palettes = sub_palettes)))
      } else{
        print("test")
      }
    }
    
    }
}
dev.off()
  
```




```{r stacked bar png, echo=FALSE}
i = 0
for (figure in unique(df$title_name)) {
  i = i + 1
  print(i)

  dat = df %>%
      filter(title_name == figure) %>%
      time_series_figure_specific_data_processing()
  
  for (selected_region in unique(dat$region)) {
      dat_filtered = dat %>%
        filter(region == selected_region)
    
      png(filename=paste(overall_path, "time_series/", str_replace(selected_region, " ", "_"), "_",
                       str_replace_all(unique(dat$title_name), "\\|","_") , ".png", sep = ""), width=1200, height=600)

      if (check_dat_before_plotting(dat_filtered)) {
      if (unique(dat_filtered$type) == "grid") {
          print(time_series_grid_fn(df = dat_filtered, 
                            x = unique(dat_filtered$x), y = unique(dat_filtered$y), 
                            color = unique(dat_filtered$color), 
                            facet1 = unique(dat_filtered$facet1), facet2 = unique(dat_filtered$facet2),
                          mapping_list = list(
                            xlab = unique(dat_filtered$x),
                             ylab= unique(dat_filtered$unit),
                             title = paste(figure, selected_region, sep = "-"),
                            model_color_palette = figure,
                            palettes = sub_palettes)))
        
      } else{
        print("test")
      }
        dev.off()
    }
    
  }
}
```

