---
title: "Stacked Bar BSG Figures"
author: "Morgan Browning"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 5
    theme: cerulean
    toc_float: 
      collapsed: true
      smooth_scroll: true
params:
  plot_years: !r c(2020, 2050)
  regions: !r c("United States")
  mode: NULL       
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = here::here())
```

```{r, warning = FALSE}
if(is.null(params$mode)) {
  library(targets)
  library(tidyverse)
  library(here)
  library(glue)
  library(plotly)
  library(data.table)
  devtools::load_all(here())
}
```

# Part 0. Basic Setup 

Read in the necessary data

```{r data}
tar_load(config)
stopifnot(exists("config"))

tar_load(emf_data_long)
stopifnot(exists("emf_data_long"))

tar_load(emf_summary_long)
stopifnot(exists("emf_summary_long"))
```

# Part I. Specific Figures

1). Load Data and Assign colors 
 
```{r load plot list, echo=FALSE}
plot_list <- readr::read_csv("plot_mapping/round1/stacked_bar_building_MBrowning.csv")
```

```{r add color subpalettes, echo=FALSE}
figure_titles <- unique(plot_list$title_name)

for (figure_title in figure_titles) {
  temp = plot_list %>% filter(title_name == figure_title) 
  var_palette = unique(temp$variable_rename)
  names(var_palette) = var_palette
  sub_palettes[[figure_title]] = var_palette
  sub_palettes = sub_palettes %>%
    map(~find_color(.x, color_map))
}
```


2) Process Data 

```{r data processing 2, echo=FALSE}
df <- emf_data_long

df <- df %>% 
  filter(variable %in% plot_list$variable) %>%
  filter(model %in% config$models_stack) %>%
  filter(region %in% params$region) %>%
  left_join(plot_list, by = ("variable" = "variable"))

df <- df %>%
  mutate(value = ifelse(flip_sign == 0, value, -value))

## Reorder the scenarios 
df <- df %>%
  filter(scenario %in% config$sm_scenarios) %>%
  mutate(scenario = factor(scenario, levels = config$main_scenarios))

df <- df %>% 
  filter(year %in% config$default10) 

## Group and rename the variables
df <- df %>%
  group_by(model, scenario, region, year, unit, title_name, datasrc, figure_no) 
```

```{r create dir}
lapply(params$regions, 
       function(x) if(!dir.exists(paste("output/round1/BSG presentation/", str_replace(x, " ", "_"), sep = ""))) 
         {dir.create(paste("output/round1/BSG presentation/", str_replace(x, " ", "_"), sep = "") )}
       )
```
  
```{r stacked bar png, echo=FALSE}
for (region in params$regions) {
  i = 0
  for (figure in unique(df$title_name)) {
    i = i + 1
    print(i)
    
    dat = df %>% filter(title_name == figure) %>%
      filter(region == region)
    
    png(filename=paste("output/round1/BSG presentation/",
                       str_replace(region," ","_"),"/",str_replace_all(unique(dat$title_name),"\\|","_"), "_stacked_bar.png", sep=""), 
        width=1200, height=600)
    
    
    
    if (nrow(dat) == 0) {
      print(paste('there is no observation for ', level, sep = ""))
    } else if (!(length(unique(dat$unit))==1)) {
      print(paste('there are multiple units for ', level, sep = ""))
    } else {
        print(stacked_bar_grid_plot_fn(df = dat, 
                            x = "year" , y = "value", 
                            color = "variable_rename", 
                           facet1 = "scenario", facet2 = "model",
                          mapping_list = list(
                            xlab = "year",
                             ylab= unique(dat$unit),
                             title = figure,
                            model_color_palette = figure,
                            palettes = sub_palettes)))
    }
    dev.off()
   }
}
```


