---
title: "Stacked_Bar_Plots"
author: "Ruying Gao"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 5
    theme: cerulean
    toc_float: 
      collapsed: true
      smooth_scroll: true
params: 
  mode: NULL
  regions: r! c("United States", "Canada", "Mexico")
---
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = here::here())
```

```{r, warning=FALSE}
if(is.null(params$mode)) {
  library(targets)
  library(tidyverse)
  library(here)
  library(glue)
  library(plotly)
  library(data.table)
  devtools::load_all(here())
}
```

# Part 0. Basic Setup 

Read in the necessary data

```{r data}
tar_load(config)
stopifnot(exists("config"))

tar_load(emf_data_long)
stopifnot(exists("emf_data_long"))

tar_load(emf_summary_long)
stopifnot(exists("emf_summary_long"))

tar_load(ts_presentation_figmap)
stopifnot(exists("ts_presentation_figmap"))
```

# Presentation Figures

```{r merge}
df <-  emf_data_long

presentation_figures <- ts_presentation_figmap

df <- df %>% 
  left_join(presentation_figures, by = c("variable" = "variable"))

df <- df %>%
  ts_filter(unique(presentation_figures$variable)) %>%
  filter(model %in% config$models_main) 
  
df <- df %>%
  group_by(title_name, figure_no)
```

```{r create dir}
lapply(params$regions, function(x) if(!dir.exists(paste("output/round1/presentation/", str_replace(x, " ", "_"), sep = ""))) dir.create(paste("output/round1/presentation/", str_replace(x, " ", "_"), sep = "") ))
```

```{r presentation pdf}

for (region in params$regions) {
  pdf(file=paste("output/round1/presentation/", str_replace(region, " ", "_"), "/time_series_presentation.pdf",sep=""), width = 12, height = 6)
  i = 0
  for (plot in unique(presentation_figures$figure_no)) {
    i = i + 1
    print(i)
    
    dat <- df  %>%
    filter(figure_no %in% plot) %>%
      filter(region == region)
  
    print(time_series_grid_fn(df = dat, 
                         x = "year", y = "value", 
                         color = "model", shape = "model", 
                         facet1 = "variable_name", facet2 = "scenario",
                         mapping_list = list(
                           title = paste(unique(dat$title_name), sep = " "),
                           xlab = "year",
                           ylab = dat$unit,
                           model_color_palette = "models_main"
                         ))) 
  }   
  dev.off()
  
  
}

```

```{r presentation png}

for (region in params$regions) {
  i = 0
  for (plot in unique(presentation_figures$figure_no)) {
      i = i + 1
      print(i)
      
      dat <- df  %>%
      filter(figure_no %in% plot) %>%
      filter(region == region)
      
      png(filename=paste("output/round1/presentation/", str_replace(region, " ", "_"), "/", unique(dat$title_name), "_time_series.png", sep = ""), width=1000, height=600)
    
      print(time_series_grid_fn(df = dat, 
                           x = "year", y = "value", 
                           color = "model", shape = "model", 
                           facet1 = "variable_name", facet2 = "scenario",
                           mapping_list = list(
                             title = unique(dat$title_name),
                             xlab = "year",
                             ylab = dat$unit,
                             model_color_palette = "models_main"
                           ))) 
      dev.off()
  } 
}
```
