---
title: "Submission Summary"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    theme: spacelab
params:
  mode: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = here::here())
```

```{r library}
if(is.null(params$mode)) {
  library(knitr)
  library(ggplot2)
  library(tidyverse)
  source("packages.R")
  devtools::load_all(here())
}

library(kableExtra)
library(DT)
```

```{r data}
deps <- tar_read(text_rmd_outputs) # make sure this runs after text summaries, b/c kableExtra messes with md output

tar_load(config)
stopifnot(exists("config"))

tar_load(emf_data_min)
stopifnot(exists("emf_data_min"))

tar_load(emf_data_long)
stopifnot(exists("emf_data_long"))

tar_load(emf_summary_long)
stopifnot(exists("emf_summary_long"))

tar_load(emf_template)
stopifnot(exists("emf_template"))

tar_load(text_rmd_outputs) # dependency set to run text_rmd_outputs before submission_summary runs
```

# Submissions Overview

### Model Submissions

```{r total submissions}
scen_mapping_submissions <- config$scen_mapping %>%
  filter(model_new %in% config$models_main) %>%
  arrange(model_new)

num_models_data <- pull(scen_mapping_submissions, model_new) %>%
  unique()

num_models_in_iiasa_db <- scen_mapping_submissions %>%
  filter(model_new %in% num_models_data) %>%
  filter(str_detect(datasrc, "^emf37_")) %>%
  pull(model_new) %>%
  unique()

num_via_email <- setdiff(num_models_data, num_models_in_iiasa_db)

data.frame(
  Stat = c("Total Submittied","-- IIASA Database","-- Workbook"),
  Number = c(length(num_models_data),length(num_models_in_iiasa_db),length(num_via_email))
  ) %>%
  kable(align = c('l','c')) %>% 
  kable_styling(full_width = F, position = "left", bootstrap_options = "striped")
```

### Submissions per Model

```{r model overview table}
submitted_models <- vector(mode = "character", length = length(num_models_data))
scenario_count <- vector(mode = "numeric", length = length(num_models_data))
variable_count <- vector(mode = "numeric", length = length(num_models_data))

for (i in 1:length(num_models_data)) {
  submitted_models[i] <- num_models_data[i]
  scenario_count[i] <- length(unique((emf_data_long %>% filter(model == num_models_data[i]))$scenario))
  variable_count[i] <- length(unique((emf_data_long %>% filter(model == num_models_data[i]))$variable))
}

model_overview <- data.frame(submitted_models, scenario_count, variable_count) %>%
  rename(Model = submitted_models,
         `Scenarios` = scenario_count,
         `Variables` = variable_count)

model_overview %>%
  kable(align = c('l','c','c')) %>% 
  kable_styling(full_width = F, position = "left", bootstrap_options = "striped") %>%
  column_spec(1, bold = T) %>%
  add_header_above(c(" " = 1 ,"Submissions" = 2))
```

### Submissions Matrix

```{r model submission matrix}
options(knitr.kable.NA = '')

num <- length(unique(scen_mapping_submissions$model_new))

scen_mapping_submissions %>%
  select(model_new, scenario_new) %>%
  rename(model = model_new, scenario = scenario_new) %>%
  filter(!is.na(scenario)) %>%
  distinct(model, scenario) %>%
  mutate(submitted = "x") %>%
  # arrange(match(scenario, c(
  #   "NT.Ref","NT.All","NT.BSG","NT.ISG","NT.TSG",
  #   "0by50.Ref","0by50.All","0by50.BSG","0by50.CMSG","0by50.CMSG1","0by50.CMSG2","0by50.CMSG3","0by50.CMSG4","0by50.ISG","0by50.TSG",
  #   "0by60.All","0by80.All","0GHGby50.All"))) %>%
  pivot_wider(names_from = "model", values_from = "submitted") %>%
  arrange(scenario) %>%
  rename(` `= scenario) %>%
  kable(align = c('r',rep('c', num))) %>% 
  kable_styling(full_width = F, position = "left", bootstrap_options = "striped") %>%
  column_spec(1, bold = T) %>%
  add_header_above(c("Scenario" = 1 ,"Model" = num))
```

### Submissions per Scenario

```{r}
df <- scen_mapping_submissions %>%
  select(model_new, scenario_new) %>%
  rename(model = model_new, scenario = scenario_new) %>%
  filter(!is.na(scenario)) %>%
  distinct(model, scenario) %>%
  count(scenario) %>%
  rename(Scenario = scenario,
         Submissions = n) %>%
  arrange(desc(Submissions))

cbind(df[1:9,], df[10:18,]) %>%
  kable(align = c('l','c','l','c')) %>% 
  kable_styling(full_width = F, position = "left", bootstrap_options = "striped")
```

### Variable Submissions

```{r variables with n submissions}
var_count <- function(model_count) {
  df <- emf_data_long %>%
  group_by(variable) %>%
  mutate(count = length(unique(model))) %>% 
  filter(count >= model_count) %>% 
  ungroup()
  
  return(length(unique(df$variable)))
}

var_counts <- vector(mode = "numeric", length = 5)

for(i in 1:5) {
  var_counts[i] <- var_count(i)
}

data.frame(
  c(1,2,3,4,5),
  c(var_counts)
  ) %>%
  rename(`Variables with at least<br/> n model submissions` = `c.1..2..3..4..5.`,
         Count = `c.var_counts.`) %>%
  kable(escape = FALSE, align = 'cc') %>% 
  kable_styling(full_width = F, position = "left", bootstrap_options = "striped")
```

### Model Submissions per Variable

```{r}
template_vars <- config$template %>% 
  distinct(round, variable) %>% 
  arrange(round, variable)

all_model_data_long <- emf_data_long %>% 
  filter(!is.na(value)) %>%
  filter(model %in% config$models_main)

vars_data <- template_vars %>%
  filter(round == 1) %>%
  left_join(all_model_data_long, by = "variable") %>%
  group_by(variable) %>%
  summarize(num_models = length(unique(model))) %>%
  rename(Variable = variable,
         `Model Count` = num_models)

datatable(vars_data, options = list(pageLength = 10))
```
