---
title: "Stacked_Bar_Plots"
author: "Ruying Gao"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 5
    theme: cerulean
    toc_float: 
      collapsed: true
      smooth_scroll: true
params:
  mode: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = here::here())
```

```{r, warning=FALSE}
if(is.null(params$mode)) {
  library(targets)
  library(tidyverse)
  library(here)
  library(glue)
  library(plotly)
  library(data.table)
  devtools::load_all(here())
}
```

# Part 0. Basic Setup 

Read in the necessary data

```{r data}
tar_load(config)
stopifnot(exists("config"))

tar_load(emf_data_long)
stopifnot(exists("emf_data_long"))

tar_load(emf_summary_long)
stopifnot(exists("emf_summary_long"))

tar_load(ts_batch_figmap)
stopifnot(exists("ts_batch_figmap"))
```

# Part I. Graphs

##  1. x = year, y = value, color by model, facet by scenario

1). Process Data 

```{r process data, echo=FALSE}
## Select the key variables we want to plot 
# var_list <- ts_batch_figmap
# var_names <- var_list$variables
# title_names <- var_list$figure_name

filter_data <- function(model_count) {
  df = emf_data_long %>%
  group_by(variable) %>%
  mutate(count = length(unique(model))) %>% 
  filter(count >= model_count) %>% 
  ungroup()
  
  print(length(unique(df$variable)))
  return(unique(df$variable))
}

var_names = filter_data(4)
title_names = var_names
```

2) Make graphs 

a) Sample graph 

```{r make sample graph, fig.align="center", echo = FALSE}
dat = emf_data_long %>% filter(variable == var_names[1])

# modified models, scenarios, and years
  # dat = emf_data_long %>% 
  #   filter(variable == var_names[50]) %>% 
  #   filter(model %in% config$models_main) %>%
  #   filter(scenario %in% (config$main_scenarios) | scenario %in% c( "MER")) %>%
  #   filter(year >= 2020) %>%
  #   filter(year <= 2050) 


print(time_series_fn(df = dat, 
                       x = "year", y = "value", 
                       color = "model", shape = "model", 
                       facet = "scenario", 
                       mapping_list = list(
                         title = title_names[1],
                         xlab = "year",
                         ylab = dat$unit,
                         model_color_palette = "models_main"
                       ))) 
```

b) Loop to make all the graphs

```{r make graphs, echo=FALSE}

pdf(file="output/round1/time_series_batch/timeseries.pdf", width = 12, height = 6)

for (i in 1:length(var_names)) {
  if (i%%10 == 0) {
    print(i)
  }
  dat = emf_data_long %>% 
    filter(variable == var_names[i]) %>% 
    filter(model %in% config$models_main) %>%
    filter(scenario %in% config$main_scenarios| scenario %in% c( "MER")) %>%
    filter(year >= 2020) %>%
    filter(year <= 2050)    


  print(time_series_fn(df = dat, 
                       x = "year", y = "value", 
                       color = "model", shape = "model", 
                       facet = "scenario", 
                       mapping_list = list(
                         title = title_names[i],
                         xlab = "year",
                         ylab = dat$unit,
                         model_color_palette = "models_main"
                       )))
  }

dev.off()

```
