---
title: "EMF37 Overview"
author: ""
date: "`r Sys.Date()`"
output:  
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = here::here())
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r packages, include=FALSE}
source("packages.R")
library(knitr)
library(ggplot2)
```

```{r data, include=FALSE}
tar_load(config)
stopifnot(exists("config"))

tar_load(emf_data_min)
stopifnot(exists("emf_data_min"))

tar_load(emf_data_long)
stopifnot(exists("emf_data_long"))
```

```{r submissions}
scen_mapping_submissions <- config$scen_mapping %>%
  filter(!str_detect(model_new, "^AEO2"),
         !str_detect(model_new, "^EIA_"))

num_models_data <- pull(scen_mapping_submissions, model_new) %>%
  unique()

num_models_in_iiasa_db <- scen_mapping_submissions %>%
  filter(model_new %in% num_models_data) %>%
  filter(str_detect(datasrc, "^emf37_internal_")) %>%
  pull(model_new) %>%
  unique()

num_via_email <- setdiff(num_models_data, num_models_in_iiasa_db)
```


# Data Submissions

- Number models submitted/included: `r length(num_models_data)`  
- Of these, in IIASA EMF37 DB: `r length(num_models_in_iiasa_db)`
- Via email: `r length(num_via_email)`

Models Submitting:

```{r, results='asis'}
cat(paste('-', num_models_data), sep = '\n')
```

# Submission Stats

Beta round scenarios:
```{r}
scen_mapping_submissions %>%
  select(model_new, scenario_new) %>%
  rename(model = model_new, scenario = scenario_new) %>%
  filter(!is.na(scenario)) %>%
  distinct(model, scenario) %>%
  count(scenario) %>%
  knitr::kable()
```

Additional Scenarios:

```{r}
scen_mapping_submissions %>%
  filter(is.na(scenario_new)) %>%
  select(model_new, scenario) %>%
  rename(model = model_new) %>%
  filter(!is.na(scenario)) %>%
  count(scenario) %>%
  knitr::kable()
```


Variables:

```{r}
template_vars <- config$template %>% 
  mutate(round = factor(round, c("beta", "1", "2", "tbd", "optional"))) %>%
  distinct(round, variable) %>% arrange(round, variable)

tar_load("emf_data_long")
stopifnot(exists("emf_data_long"))
all_model_data_long <- emf_data_long %>% 
  filter(!is.na(value)) %>%
  filter(!str_detect(model, "^AEO2"),
         !str_detect(model, "^EIA_"))

vars_data <- template_vars %>%
  filter(round == "beta") %>%
  left_join(all_model_data_long, by = "variable") %>%
  group_by(variable) %>%
  summarize(num_models = length(unique(model)))

vars_data %>%
  knitr::kable()
```

