---
title: "Appendix"
output: 
  html_document:
    toc: true
    toc_float: true
date: "`r Sys.time()`"
params:
  mode: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = here::here())
```

```{r}
if(is.null(params$mode)) {
  source("packages.R")
  devtools::load_all()
}

# load data from targets pipeline
targets::tar_load(config)
targets::tar_load(clean_data)
targets::tar_load(figmap_leep_timeseries)
targets::tar_load(figmap_leep_cone)
targets::tar_load(figmap_leep_stackbar)
targets::tar_load(figmap_leep_diffbar)

# palettes
subpalettes = create_subpalettes(figmap_leep_timeseries, config)
```

# Appendix

## Emissions Summary Tables

```{r}
tab_a1 = summary_tables(
  table_no = "A1 Economy-Wide Emissions",
  var = "Emissions|CO2",
  suffix = "Economy-wide emissions",
  drop_mod = c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "Haiku-RFF"),
  data = clean_data,
  config = config
)

tab_a2 = summary_tables(
  table_no = "A2 Power Sector Emissions",
  var = "Emissions|CO2|Energy|Supply|Electricity",
  suffix = "Power sector emissions",
  drop_mod = c("Scout-LEEP"),
  drop_datasrc = c("ReEDS_compiled.csv"), # remove duplicate values for ReEDS-NREL - basically same values
  data = clean_data,
  config = config
)

tab_a3 = summary_tables(
  table_no = "A3 Transportation Emissions",
  var = "Emissions|CO2|Energy|Demand|Transportation|Total",
  suffix = "Transportation emissions",
  drop_mod = c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "Haiku-RFF"),
  data = clean_data,
  config = config
)

tab_a4 = summary_tables(
  table_no = "A4 Buildings Emissions",
  var = "Emissions|CO2|Energy|Demand|Buildings|Total",
  suffix = "Buildings emissions",
  drop_mod = c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Haiku-RFF"),
  data = clean_data,
  config = config
)

tab_a5 = summary_tables(
  table_no = "A5 Industry Emissions",
  var = "Emissions|CO2|Energy|Demand|Industry and Fuel Production|Total",
  suffix = "Industry emissions",
  drop_mod = c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "Haiku-RFF"),
  data = clean_data,
  config = config
)
```

## Economy-Wide Diff
```{r EconWide Differnce}
fig_no = "Ap.1.EconWideEmis"

ts_map_ID = 99
pd_map_ID = 25
ad_map_ID = 3
drop = ""
histsrc = "EPA-GHGI"
metric = "Emissions"
unit = "Mt CO2/yr"
ymin = 2950
ymax = 5050
brk = c(3000, 4000, 5000)

fig = four_corners("Economy-wide CO2 Emissions",ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit, fig_no, ymin, ymax, brk)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Electricity Diff
```{r Electricity Differnce}
fig_no = "Ap.2.ElecEmis"

ts_map_ID = 98
pd_map_ID = 26
ad_map_ID = 4
drop = ""
histsrc = "EPA-GHGI"
metric = "Emissions"
unit = "Mt CO2/yr"
ymin = 300
ymax = 1650
brk = c(400, 800, 1200, 1600)

fig = four_corners("Electricity CO2 Emissions",ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit, fig_no, ymin, ymax, brk)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Transportation Diff
```{r Transportation Differnce}
fig_no = "Ap.3.TranEmis"

ts_map_ID = 19
pd_map_ID = 27
ad_map_ID = 5
drop = c("IPM-EPA","IPM-NRDC")
histsrc = "EPA-GHGI"
metric = "Emissions"
unit = "Mt CO2/yr"
ymin = 1150
ymax = 1900
brk = c(1200, 1500, 1800)

fig = four_corners("Transportation CO2 Emissions",ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit, fig_no, ymin, ymax, brk)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Building Diff
```{r Building Difference}
fig_no = "Ap.4.BuilEmis"

ts_map_ID = 23
pd_map_ID = 29
ad_map_ID = 7
drop = c("IPM-EPA", "IPM-NRDC")
histsrc = "EPA-GHGI"
metric = "Emissions"
unit = "Mt CO2/yr"
ymin = 400
ymax = 1800
brk = c(400, 800, 1200, 1600)

fig = four_corners("Buildings CO2 Emissions",ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit, fig_no, ymin, ymax, brk)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Industry Diff
```{r Industry Differnce}
fig_no = "Ap.5.IndEmis"

ts_map_ID = 21
pd_map_ID = 28
ad_map_ID = 6
drop = c("IPM-EPA", "IPM-NRDC")
histsrc = "EPA-GHGI"
metric = "Emissions"
unit = "Mt CO2/yr"
ymin = 0
ymax = 1600
brk = c(0, 500, 1000, 1500)

fig = four_corners("Industry CO2 Emissions",ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit, fig_no, ymin, ymax, brk)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)

```

## Coal Diff
```{r Coal Emissions Difference} 
fig_no = "Ap.6.Coal"

ts_map_ID = 94
pd_map_ID = 32
ad_map_ID = 20
drop = c("EIAinEMF37.csv")
histsrc = "EIA"
metric = "Emissions"
unit = "Mt CO2/yr"
ymin = 0
ymax = 20
brk = c(0, 5, 10, 15, 20)

fig = four_corners("Emissions from Coal",ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit, fig_no, ymin, ymax, brk)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Gas Diff
```{r Gas Emissions Difference} 
fig_no = "Ap.7.Gas"

ts_map_ID = 93
pd_map_ID = 31
ad_map_ID = 21
drop = c("EIAinEMF37.csv", "RIO-REPEAT")
histsrc = "EIA"
metric = "Emissions"
unit = "Mt CO2/yr"
ymin = 20
ymax = 35
brk = c(20, 25, 30, 35)

fig = four_corners("Emissions from Gas",ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit, fig_no, ymin, ymax, brk)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Petrol Diff
```{r Petrol Emissions Difference} 
fig_no = "Ap.8.Petrol"

ts_map_ID = 92
pd_map_ID = 30
ad_map_ID = 22
drop = "EIAinEMF37.csv"
histsrc = "EIA"
metric = "Emissions"
unit = "Mt CO2/yr"
ymin = 20
ymax = 40
brk = c(20, 30, 40)

fig = four_corners("Emissions from Petroleum", ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit, fig_no, ymin, ymax, brk)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Nuclear Generation Diff
```{r Nuclear Generation Difference} 
fig_no = "Ap.9.NuclearGen"

ts_map_ID = 91
pd_map_ID = 80
ad_map_ID = 8
drop = "EIAinEMF37.csv"
histsrc = "EIA"
metric = "Generation"
unit = "TWh"
ymin = 0
ymax = 850
brk = c(0, 200, 400, 600, 800)

fig = four_corners("Electricity Generation from Nuclear", ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit, fig_no, ymin, ymax, brk)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Solar Generation Diff
```{r Solar Generation Difference} 
fig_no = "Ap.10.SolarGen"

ts_map_ID = 90
pd_map_ID = 79
ad_map_ID = 9
drop = c("EIAinEMF37.csv", "IPM-EPA")
histsrc = "EIA"
metric = "Generation"
unit = "TWh"
ymin = 100
ymax = 2200
brk = c(500, 1000, 1500, 2000)

fig = four_corners("Electricity Generation from Solar", ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit, fig_no, ymin, ymax, brk)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Wind Generation Diff
```{r Wind Generation Difference} 
fig_no = "Ap.11.WindGen"

ts_map_ID = 89
pd_map_ID = 78
ad_map_ID = 10
drop = c("EIAinEMF37.csv", "IPM-EPA")
histsrc = "EIA"
metric = "Generation"
unit = "TWh"
ymin = 350
ymax = 2600
brk = c(500, 1000, 1500, 2000, 2500)

fig = four_corners("Electricity Generation from Wind", ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit, fig_no, ymin, ymax, brk)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## CCS Generation Diff
```{r CCS Generation Difference, eval = FALSE} 
fig_no = "Ap.12.CCSGen"

#there is no historic data here so gotta do a lil manual work 
ts_map_ID = 85
pd_map_ID = 76
ad_map_ID = 14
drop = c("EIAinEMF37.csv", "IPM-EPA")
histsrc = "EIA"
unit = "Generation (Quads)"
ymin = 0 
ymax = 5
brk = c(0, 1, 2, 3, 4, 5)

 #Time Series Dataframe
    ts_df = data_from_graph(
    "time_series",
    config,
    clean_data,
    figmap_leep_timeseries,
    ts_map_ID,
    "United States"
  ) %>%
    filter(!model %in% drop) %>%
    filter(!datasrc %in% drop)%>%
    filter(year >= 2021) %>%
    filter(year <= 2021 &
             model == histsrc |
             year > 2021 & scenario != "Historic") %>%
      group_by(model, scenario, year, variable_rename) %>%
      summarize(value = sum(value)) %>%
    pivot_wider(names_from = year, values_from = value)
    
    ts_df = ts_df %>%
    mutate(`2021` = 0) %>%
    pivot_longer(cols = starts_with("20"),
                 names_to = "year",
                 values_to = "value") %>%
    filter(!is.na(value)) %>%
    mutate(year = as.numeric(year)) 
      
    noIRAmedians = ts_df[ts_df$scenario == "No IRA",] %>%
      filter(year == 2030 | year == 2035) %>%
      group_by(year) %>%
      summarize(median = median(value))
    
    IRAmedians = ts_df[ts_df$scenario == "IRA",] %>%
      filter(year == 2030 | year == 2035) %>%
      group_by(year) %>%
      summarize(median = median(value))
    
    NoIRAfigure = ggplot(ts_df[ts_df$scenario == "No IRA", ], aes(year, value, color = model)) +
      geom_line(size = 0.75) +
      scale_subpalette(subpalettes, "Emissions|CO2|Percent difference from No IRA") +
      theme_emf() +
      scale_x_continuous(breaks = c(2021, 2025, 2030, 2035)) +    
      scale_y_continuous(limits = c(ymin, ymax), breaks = brk) + 
      labs(title = "No IRA",
           y = unit,
           x = element_blank()) +
      theme(plot.title = element_text(hjust = 0.5),
            legend.position = "right",
            axis.text.x = element_text(angle = 45, hjust = 1)) +
      geom_point(aes(x = 2021, y = ts_df$value[ts_df$year == 2021][1]), color = "black") +
      geom_point(
        data = noIRAmedians,
        aes(x = year, y = median),
        color = "black",
        shape = 16,
        size = 2
      )
    
    IRAfigure = ggplot(ts_df[ts_df$scenario == "IRA", ], aes(year, value, color = model)) +
      geom_line(size = 0.75) +
      scale_subpalette(subpalettes, "Emissions|CO2|Percent difference from No IRA") +
      theme_emf() +
      scale_x_continuous(breaks = c(2021, 2025, 2030, 2035)) +
      scale_y_continuous(limits = c(ymin, ymax), breaks = brk) + 
      labs(title = "IRA",
           y = unit,
           x = element_blank()) +
      theme(plot.title = element_text(hjust = 0.5),
            legend.position = "right",
            axis.text.x = element_text(angle = 45, hjust = 1)) +
      geom_point(aes(x = 2021, y = ts_df$value[ts_df$year == 2021][1]), color = "black") +
      geom_point(
        data = IRAmedians,
        aes(x = year, y = median),
        color = "black",
        shape = 16,
        size = 2
      )
    
    #Percent Difference
      
pdfigure = pd(pd_map_ID, "", expression(paste("Percent Difference (%)")), "none", drop)
    
    #Absolute Difference
adfigure = ad(diff_ID = ad_map_ID, "", expression(paste("Absolute Difference (Quads)")), "none", drop)
  
fig = (NoIRAfigure | IRAfigure) / (adfigure$figure | pdfigure$figure)+ 
  plot_layout(guides = "collect") +
  plot_annotation(title = "Electricity Generation from Coal with CCS")

fig

# TODO: This entire figure is broken and saves off data that doesnt exist. I fixed the figure, but the whole thing should be rewritten to fit the format of the rest of the figures and actually output the correct data

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig, fig_no)
```

## Coal Generation Diff
```{r Coal Generation Difference} 
fig_no = "Ap.13.CoalGen"

ts_map_ID = 82
pd_map_ID = 71
ad_map_ID = 17
drop = c("EIAinEMF37.csv", "IPM-EPA")
histsrc = "EIA"
metric = "Generation"
unit = "TWh"
ymin = 0
ymax = 1100
brk = c(0, 250, 500, 750, 1000)


fig = four_corners("Coal Generation", ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit, fig_no, ymin, ymax, brk)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Gas Generation Diff
```{r Gas Generation Difference} 
fig_no = "Ap.14.GasGen"

ts_map_ID = 81
pd_map_ID = 70
ad_map_ID = 18
drop = c("EIAinEMF37.csv", "IPM-EPA", "AEO.2023")
histsrc = "EIA"
metric = "Generation"
unit = "TWh"
ymin = 0
ymax = 2500
brk = c(0, 500, 1000, 1500, 2000, 2500)


fig = four_corners("Electricity Generation from Gas", ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit, fig_no, ymin, ymax, brk)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```

## Other Generation Diff
```{r Other Generation Difference} 
fig_no = "Ap.15.OtherGen"

ts_map_ID = 88
pd_map_ID = 77
ad_map_ID = 11
drop = c("EIAinEMF37.csv", "IPM-EPA")
histsrc = "EIA"
metric = "Generation"
unit = "TWh"
ymin = 250
ymax = 500
brk = c(250, 375, 500)


fig = four_corners("Electricity Generation from Other", ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc, metric, unit, fig_no, ymin, ymax, brk)

fig$figure

write.csv(fig$ts_df, file = paste("output/final_figures/data/Fig",fig_no,"a_Scen.csv",sep=""), row.names = FALSE)
write.csv(fig$pd_df, file = paste("output/final_figures/data/Fig",fig_no,"b_PercDiff.csv",sep=""), row.names = FALSE)
write.csv(fig$ad_df, file = paste("output/final_figures/data/Fig",fig_no,"c_AbsDiff.csv",sep=""), row.names = FALSE)

savefig(fig$figure, fig_no)
```











