---
title: "Figure Examples"
output: html_document
date: "2023-05-10"
params:
  mode: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = here::here())
```

```{r}
if(is.null(params$mode)) {
  source("./packages.R")
  library(patchwork)
  library(egg)
  library(ggbreak)
  devtools::load_all()
}
```

```{r}
tar_load(config)
tar_load(clean_data)
tar_load(data_min)
tar_load(data_raw)
# tar_load(clean_data_index)
tar_load(figmap_leep_cone)
tar_load(figmap_leep_timeseries)
tar_load(figmap_leep_stackbar)

subpalettes = create_subpalettes(figmap_leep_timeseries, config)

# convert EJ to Quad
clean_data = clean_data %>% mutate(value = case_when(
  unit == "EJ/yr" ~ value * 0.9478,
  TRUE ~ value
)) %>% mutate(unit = case_when(
  unit == "EJ/yr" ~ "Quads",
  TRUE ~ unit
))

clean_data = clean_data %>% mutate(value = case_when(
    (model == "OP-NEMS-LTS" & scenario == "LTS.High" & year == 2025 & variable == "Emissions|CO2|Energy|Demand|Buildings") ~ (clean_data[(clean_data$model == "OP-NEMS-LTS" & clean_data$scenario == "LTS.High" & clean_data$year == 2020 & clean_data$variable == "Emissions|CO2|Energy|Demand|Buildings"),"value"]$value + clean_data[(clean_data$model == "OP-NEMS-LTS" & clean_data$scenario == "LTS.High" & clean_data$year == 2030 & clean_data$variable == "Emissions|CO2|Energy|Demand|Buildings"),"value"]$value) / 2,
    (model == "OP-NEMS-LTS" & scenario == "LTS.High" & year == 2025 & variable == "Emissions|CO2|Energy|Demand|Industry") ~ (clean_data[(clean_data$model == "OP-NEMS-LTS" & clean_data$scenario == "LTS.High" & clean_data$year == 2020 & clean_data$variable == "Emissions|CO2|Energy|Demand|Industry"),"value"]$value + clean_data[(clean_data$model == "OP-NEMS-LTS" & clean_data$scenario == "LTS.High" & clean_data$year == 2030 & clean_data$variable == "Emissions|CO2|Energy|Demand|Industry"),"value"]$value) / 2,
    (model == "OP-NEMS-LTS" & scenario == "LTS.High" & year == 2025 & variable == "Emissions|CO2|Energy|Demand|Transportation") ~ (clean_data[(clean_data$model == "OP-NEMS-LTS" & clean_data$scenario == "LTS.High" & clean_data$year == 2020 & clean_data$variable == "Emissions|CO2|Energy|Demand|Transportation"),"value"]$value + clean_data[(clean_data$model == "OP-NEMS-LTS" & clean_data$scenario == "LTS.High" & clean_data$year == 2030 & clean_data$variable == "Emissions|CO2|Energy|Demand|Transportation"),"value"]$value) / 2,
    
    (model == "OP-NEMS-LTS" & scenario == "LTS.Low" & year == 2025 & variable == "Emissions|CO2|Energy|Demand|Buildings") ~ (clean_data[(clean_data$model == "OP-NEMS-LTS" & clean_data$scenario == "LTS.Low" & clean_data$year == 2020 & clean_data$variable == "Emissions|CO2|Energy|Demand|Buildings"),"value"]$value + clean_data[(clean_data$model == "OP-NEMS-LTS" & clean_data$scenario == "LTS.Low" & clean_data$year == 2030 & clean_data$variable == "Emissions|CO2|Energy|Demand|Buildings"),"value"]$value) / 2,
    (model == "OP-NEMS-LTS" & scenario == "LTS.Low" & year == 2025 & variable == "Emissions|CO2|Energy|Demand|Industry") ~ (clean_data[(clean_data$model == "OP-NEMS-LTS" & clean_data$scenario == "LTS.Low" & clean_data$year == 2020 & clean_data$variable == "Emissions|CO2|Energy|Demand|Industry"),"value"]$value + clean_data[(clean_data$model == "OP-NEMS-LTS" & clean_data$scenario == "LTS.Low" & clean_data$year == 2030 & clean_data$variable == "Emissions|CO2|Energy|Demand|Industry"),"value"]$value) / 2,
    (model == "OP-NEMS-LTS" & scenario == "LTS.Low" & year == 2025 & variable == "Emissions|CO2|Energy|Demand|Transportation") ~ (clean_data[(clean_data$model == "OP-NEMS-LTS" & clean_data$scenario == "LTS.Low" & clean_data$year == 2020 & clean_data$variable == "Emissions|CO2|Energy|Demand|Transportation"),"value"]$value + clean_data[(clean_data$model == "OP-NEMS-LTS" & clean_data$scenario == "LTS.Low" & clean_data$year == 2030 & clean_data$variable == "Emissions|CO2|Energy|Demand|Transportation"),"value"]$value) / 2,
  TRUE ~ value
))

cap_add_avg = clean_data %>% 
  filter(model %in% c("USREP-ReEDS", "GCAM-PNNL", "OP-NEMS"), 
         (grepl("Capacity Additions", variable) | grepl("Capacity Retirements", variable)),
         (year >= 2021 | year <= 2035)) %>%
  filter(!(variable %in% c("Capacity Additions|Electricity|Biomass", "Capacity Additions|Electricity|Biomass|w/ CCS", "Capacity Additions|Electricity|Biomass|w/o CCS",
                           "Capacity Additions|Electricity|Coal", "Capacity Additions|Electricity|Gas", 
                           "Capacity Additions|Electricity|Geothermal", 
                           "Capacity Additions|Electricity|Oil", "Capacity Additions|Electricity|Oil|w/ CCS", "Capacity Additions|Electricity|Oil|w/o CCS",
                           "Capacity Additions|Electricity|Solar|CSP","Capacity Additions|Electricity|Solar|PV",
                           "Capacity Additions|Electricity|Solar|PV|Rooftop","Capacity Additions|Electricity|Solar|PV|Utility-Scale",
                           "Capacity Additions|Electricity|Storage Capacity|Battery","Capacity Additions|Electricity|Storage Capacity|PSH",
                           "Capacity Additions|Electricity|Wind|Offshore","Capacity Additions|Electricity|Wind|Onshore",
                           "Capacity Additions|Electricity|Gas|CT|w/o CCS","Capacity Additions|Electricity|Gas|CT|w/ CCS", "Capacity Additions|Electricity|Gas|CT",
                           "Capacity Additions|Electricity|Gas|CC|w/o CCS","Capacity Additions|Electricity|Gas|CC|w/ CCS", "Capacity Additions|Electricity|Gas|CC",
                           "Capacity Additions|Electricity|Gas|ST|w/o CCS","Capacity Additions|Electricity|Gas|ST|w/ CCS", "Capacity Additions|Electricity|Gas|ST",
                           "Capacity Additions|Electricity"))) %>%
    filter(!(variable %in% c("Capacity Retirements|Electricity|Biomass", "Capacity Retirements|Electricity|Biomass|w/ CCS", 
                           "Capacity Retirements|Electricity|Biomass|w/o CCS",
                           "Capacity Retirements|Electricity|Coal", "Capacity Retirements|Electricity|Gas", 
                           "Capacity Retirements|Electricity|Geothermal", 
                           "Capacity Retirements|Electricity|Oil", "Capacity Retirements|Electricity|Oil|w/ CCS", "Capacity Retirements|Electricity|Oil|w/o CCS",
                           "Capacity Retirements|Electricity|Solar|CSP","Capacity Retirements|Electricity|Solar|PV",
                           "Capacity Retirements|Electricity|Solar|PV|Rooftop","Capacity Retirements|Electricity|Solar|PV|Utility-Scale",
                           "Capacity Retirements|Electricity|Storage Capacity|Battery","Capacity Retirements|Electricity|Storage Capacity|PSH",
                           "Capacity Retirements|Electricity|Wind|Offshore","Capacity Retirements|Electricity|Wind|Onshore",
                           "Capacity Retirements|Electricity|Gas|CT|w/o CCS","Capacity Retirements|Electricity|Gas|CT|w/ CCS", 
                           "Capacity Retirements|Electricity|Gas|CT",
                           "Capacity Retirements|Electricity|Gas|CC|w/o CCS","Capacity Retirements|Electricity|Gas|CC|w/ CCS", 
                           "Capacity Retirements|Electricity|Gas|CC",
                           "Capacity Retirements|Electricity|Gas|ST|w/o CCS","Capacity Retirements|Electricity|Gas|ST|w/ CCS", 
                           "Capacity Retirements|Electricity|Gas|ST",
                           "Capacity Retirements|Electricity"))) %>%
  group_by(model, scenario, unit, datasrc, variable, region) %>%
  summarize(value = mean(value)) %>%
  mutate(variable = paste0(variable,"|Average 2021-2035"), year = 2035)

clean_data = rbind(clean_data, cap_add_avg)

clean_data %>% write.csv("output/data/clean_data.csv", row.names = FALSE)

# data_cdr = data.frame("model" = rep("EIA-LTS",16), "year" = seq(2005,2020,by = 1), "unit" = rep("Mt CO2/yr",16), "scenario" = rep("Historic",16),
#                         "datasrc" = rep("LTS_data_small.xlsx",16), variable = rep("Emissions|CO2|CDR",16), region = "United States",
#                         "value" = rep(0,16))
# clean_data = rbind(clean_data,data_cdr)
```


```{r}
# This function does a bunch of stuff
# Calls the main functions to print a spagetti plot
# Then makes some dot plots to show the distributions: one for 2030, one for 2035
# The inputs are the same as for the print_graph() function, plus some new ones:
#   ymin and ymax: to manually set the y axis limits so that the axes line up across plots
#   plot_title: manually set the plot title of the combined plot
#   metric: what centrality metric to show on the dot plots: "mean" or "median"
dot_plots_sens = function(plot_type, config, emf_data_long, figmap, figure_num, reg, ymin, ymax, plot_title, metric, labels = FALSE, historic_coord = c(0,0), iralow_coord = c(0,0), irahigh_coord = c(0,0)) {
  
  subpalettes = create_subpalettes(figmap_leep_timeseries, config)
  
  # make the spagetti plot
  fig = print_graph(plot_type, config, emf_data_long, figmap, figure_num, reg)
  # update the axis range
  fig = fig + scale_y_continuous(limits = c(ymin, ymax)) +
      #scale_x_continuous(breaks = c(2005, 2021, 2025, 2030, 2035), labels = c(2005, 2021, 2025, 2030, 2035)) +
      scale_alpha(range = c(0.6, 1), guide = "none") + 
      annotate("text", x = historic_coord[1], y = historic_coord[2], label = "Historic", color = "black", alpha = 1) +
      annotate("text", x = iralow_coord[1], y = iralow_coord[2], label = "IRA.Low", color = "#A1A1A1", alpha = 1) +
      annotate("text", x = irahigh_coord[1], y = irahigh_coord[2], label = "IRA.High", color = "#363636", alpha = 1) +
      theme(legend.position = "none", plot.title = element_blank())
  
  if (labels) {
    label_data = data_from_graph(plot_type, config, emf_data_long, figmap, figure_num, reg) %>%
      filter(year == 2035)
    print(unique(label_data$model))
    fig = fig + 
      geom_text(data = label_data, aes(x = year + 0.25, y = value, label = model, color = scenario), size = 2, hjust = 0) +
      #geom_text_repel(data = label_data, aes(label = model), size = 2, hjust = 0) +
      scale_x_continuous(limits = c(NA,2037))
  }
  
  # pull the data from the graph and filter/summarize for 2030/2035
  df_30 = data_from_graph(plot_type, config, emf_data_long, figmap, figure_num, reg) %>%
    filter(year %in% c(2030))
  df_stat_30 = df_30 %>%
    group_by(scenario,year,variable_rename) %>%
    summarise(mean = mean(value, na.rm = TRUE),
           median = median(value, na.rm = TRUE))
  df_35 = data_from_graph(plot_type, config, emf_data_long, figmap, figure_num, reg) %>%
    filter(year %in% c(2035))
  df_stat_35 = df_35 %>%
    group_by(scenario,year,variable_rename) %>%
    summarise(mean = mean(value, na.rm = TRUE),
           median = median(value, na.rm = TRUE))
  
  stats = 0
  # these are the summary stats we'll eventually want to overlay on the plot to highlight the efficacy of the IRA
  # preira_mean_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean
  # ira_mean_30 = df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
  # preira_mean_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean
  # ira_mean_35 = df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean
  # preira_med_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median
  # ira_med_30 = df_stat_30[df_stat_30$scenario == "IRA","median"]$median
  # preira_med_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median
  # ira_med_35 = df_stat_35[df_stat_35$scenario == "IRA","median"]$median
  # 
  # # calculate raw differences
  # mean_diff_30 = preira_mean_30 - ira_mean_30
  # mean_diff_35 = preira_mean_35 - ira_mean_35
  # med_diff_30 = preira_med_30 - ira_med_30
  # med_diff_35 = preira_med_35 - ira_med_35
  # 
  # # calculate percent differences
  # mean_pctdiff_30 = mean_diff_30 / preira_mean_30
  # mean_pctdiff_35 = mean_diff_35 / preira_mean_35
  # med_pctdiff_30 = med_diff_30 / preira_med_30
  # med_pctdiff_35 = med_diff_35 / preira_med_35
  # 
  # # stick em all in a data frame
  # # stats = 0
  # stats = data.frame("year" = c(2030,2035,2030,2035), "metric" = c("mean","mean","median","median"),
  #                    "No IRA mean" = c(preira_mean_30, preira_mean_35, preira_med_30, preira_med_35),
  #                    "IRA mean" = c(ira_mean_30, ira_mean_35, ira_med_30, ira_med_35),
  #                    "difference" = c(mean_diff_30, mean_diff_35, med_diff_30, med_diff_35),
  #                    "percent difference" = c(mean_pctdiff_30, mean_pctdiff_35, med_pctdiff_30, med_pctdiff_35))

  # still not entirely sure what this does...
  # subpalettes = create_subpalettes(figmap_leep_timeseries, config)
  
  # a few of the ggplot lines of code vary based on the year or on the metric chosen, so conditionally choose the right one here
  if (metric == "mean") {
    segment_code_30 = geom_segment(data = df_stat_30, 
                                   aes(x = year - 0.04, xend = year + 0.04, y = mean, yend = mean, color = scenario), 
                                   size = 1)
    segment_code_35 = geom_segment(data = df_stat_35, 
                                   aes(x = year - 0.04, xend = year + 0.04, y = mean, yend = mean, color = scenario),
                                   size = 1)
    text_code = geom_text(data = df_stat_30, aes(x = year - 0.08, y = mean, color = scenario), 
                          label = "Avg", size = 3, hjust = 0.5, angle = 90, position = position_dodge2(width = 0.05))
  } else if (metric == "median") {
    segment_code_30 = geom_segment(data = df_stat_30, 
                                   aes(x = year - 0.04, xend = year + 0.04, y = median, yend = median, color = scenario), 
                                   size = 1)
    segment_code_35 = geom_segment(data = df_stat_35, 
                                   aes(x = year - 0.04, xend = year + 0.04, y = median, yend = median, color = scenario), 
                                   size = 1)
    text_code = geom_text(data = df_stat_30, aes(x = year - 0.08, y = median, color = scenario), 
                          label = "Med", size = 3, hjust = 0.5, angle = 90, position = position_dodge2(width = 0.05))
  }
  
  # dot plot for 2030
  dots_30 = ggplot() +
    geom_point(data = df_30, aes(x = year, y = value, color = scenario), shape = 1, size = 1.5, position = position_dodge(width = 0.05)) +
    segment_code_30 +
    #text_code +
    scale_x_continuous(breaks = c(2030), labels = c("2030"), limits = c(2029.9, 2030.1)) +
    scale_y_continuous(limits = c(ymin, ymax)) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions Sensitivity") +
    theme(panel.grid = element_blank(), plot.title = element_blank(),
          axis.text.y = element_blank(),
          axis.title.y = element_blank(), axis.title.x = element_blank(),
          axis.ticks = element_blank(), panel.border = element_blank(),
          legend.position = "none", plot.margin = margin(0,0,0,0))
  
  # dot plot for 2035
  dots_35 = ggplot() +
    geom_point(data = df_35, aes(x = year, y = value, color = scenario), shape = 1, size = 1.5, position = position_dodge(width = 0.05)) +
    segment_code_35 +
    scale_x_continuous(breaks = c(2035), labels = c("2035"), limits = c(2034.9, 2035.1)) +
    scale_y_continuous(limits = c(ymin,ymax)) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions Sensitivity") +
    theme(panel.grid = element_blank(), plot.title = element_blank(),
          axis.text.y = element_blank(),
          axis.title.y = element_blank(), axis.title.x = element_blank(),
          axis.ticks = element_blank(), panel.border = element_blank(),
          legend.position = "none", plot.margin = margin(0,0,0,0))
  
  # combine all the plots
  final = fig + dots_30 + dots_35 + 
    plot_annotation(title = plot_title, theme = theme(plot.title = element_text(hjust = 0.5))) +
    plot_layout(widths = c(10,1,1)) +
    theme(plot.margin = margin(0,0,0,0))
  
  # return the full plot + the components + the summary stats
  return(list(
    full = final,
    line = fig,
    dot1 = dots_30,
    dot2 = dots_35,
    stats = stats
  ))
}

# p = dot_plots("time_series", config, clean_data, figmap_leep_timeseries, 4, "United States", 0, 2500, "Emissions|CO2|Energy|Demand|Electricity", metric = "median")
# print(p$full)
# print(p$stats)

```

```{r}
dot_plots = function(plot_type, config, emf_data_long, figmap, figure_num, reg, ymin, ymax, plot_title, metric, labels = FALSE, hist_year = 2021, historic_coord = c(0,0), preira_coord = c(0,0), ira_coord = c(0,0)) {
  subpalettes = create_subpalettes(figmap_leep_timeseries, config)
  
  # make the spagetti plot
  fig = print_graph(plot_type, config, emf_data_long, figmap, figure_num, reg)
  # update the axis range
  fig = fig + scale_y_continuous(limits = c(ymin, ymax)) +
      scale_x_continuous(breaks = c(2005,2010, hist_year, 2025, 2030, 2035), labels = c(2005, 2010, hist_year, 2025, 2030, 2035)) +
      scale_alpha(range = c(0.6, 1), guide = "none") + 
      annotate("text", x = historic_coord[1], y = historic_coord[2], label = "Historic", color = "black", alpha = 1) +
      annotate("text", x = preira_coord[1], y = preira_coord[2], label = "No IRA", color = "#0388B3", alpha = 1) +
      annotate("text", x = ira_coord[1], y = ira_coord[2], label = "IRA", color = "#F28063", alpha = 1) +
      theme(legend.position = "none", plot.title = element_blank())
  
  if (labels) {
    label_data = data_from_graph(plot_type, config, emf_data_long, figmap, figure_num, reg) %>%
      filter(year == 2035)
    print(unique(label_data$model))
    fig = fig + 
      geom_text(data = label_data, aes(x = year + 0.25, y = value, label = model, color = scenario), size = 2, hjust = 0) +
      #geom_text_repel(data = label_data, aes(label = model), size = 2, hjust = 0) +
      scale_x_continuous(limits = c(NA,2037))
  }
  
  # pull the data from the graph and filter/summarize for 2030/2035
  df_30 = data_from_graph(plot_type, config, emf_data_long, figmap, figure_num, reg) %>%
    filter(year %in% c(2030))
  df_stat_30 = df_30 %>%
    group_by(scenario,year,variable_rename) %>%
    summarise(mean = mean(value, na.rm = TRUE),
           median = median(value, na.rm = TRUE))
  df_35 = data_from_graph(plot_type, config, emf_data_long, figmap, figure_num, reg) %>%
    filter(year %in% c(2035))
  df_stat_35 = df_35 %>%
    group_by(scenario,year,variable_rename) %>%
    summarise(mean = mean(value, na.rm = TRUE),
           median = median(value, na.rm = TRUE))
  
  # these are the summary stats we'll eventually want to overlay on the plot to highlight the efficacy of the IRA
  preira_mean_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean
  ira_mean_30 = df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
  preira_mean_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean
  ira_mean_35 = df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean
  preira_med_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median
  ira_med_30 = df_stat_30[df_stat_30$scenario == "IRA","median"]$median
  preira_med_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median
  ira_med_35 = df_stat_35[df_stat_35$scenario == "IRA","median"]$median
  
  # calculate raw differences
  mean_diff_30 = preira_mean_30 - ira_mean_30
  mean_diff_35 = preira_mean_35 - ira_mean_35
  med_diff_30 = preira_med_30 - ira_med_30
  med_diff_35 = preira_med_35 - ira_med_35
  
  # calculate percent differences
  mean_pctdiff_30 = mean_diff_30 / preira_mean_30
  mean_pctdiff_35 = mean_diff_35 / preira_mean_35
  med_pctdiff_30 = med_diff_30 / preira_med_30
  med_pctdiff_35 = med_diff_35 / preira_med_35
  
  # stick em all in a data frame
  stats = 0
  # stats = data.frame("year" = c(2030,2035,2030,2035), "metric" = c("mean","mean","median","median"),
  #                    "No IRA mean" = c(preira_mean_30, preira_mean_35, preira_med_30, preira_med_35),
  #                    "IRA mean" = c(ira_mean_30, ira_mean_35, ira_med_30, ira_med_35),
  #                    "difference" = c(mean_diff_30, mean_diff_35, med_diff_30, med_diff_35),
  #                    "percent difference" = c(mean_pctdiff_30, mean_pctdiff_35, med_pctdiff_30, med_pctdiff_35))

  # still not entirely sure what this does...
  subpalettes = create_subpalettes(figmap_leep_timeseries, config)
  
  # a few of the ggplot lines of code vary based on the year or on the metric chosen, so conditionally choose the right one here
  if (metric == "mean") {
    segment_code_30 = geom_segment(data = df_stat_30, 
                                   aes(x = year - 0.04, xend = year + 0.04, y = mean, yend = mean, color = scenario), 
                                   size = 1)
    segment_code_35 = geom_segment(data = df_stat_35, 
                                   aes(x = year - 0.04, xend = year + 0.04, y = mean, yend = mean, color = scenario),
                                   size = 1)
    text_code = geom_text(data = df_stat_30, aes(x = year - 0.08, y = mean, color = scenario), 
                          label = "Avg", size = 3, hjust = 0.5, angle = 90, position = position_dodge2(width = 0.05))
  } else if (metric == "median") {
    segment_code_30 = geom_segment(data = df_stat_30, 
                                   aes(x = year - 0.04, xend = year + 0.04, y = median, yend = median, color = scenario), 
                                   size = 1)
    segment_code_35 = geom_segment(data = df_stat_35, 
                                   aes(x = year - 0.04, xend = year + 0.04, y = median, yend = median, color = scenario), 
                                   size = 1)
    text_code = geom_text(data = df_stat_30, aes(x = year - 0.08, y = median, color = scenario), 
                          label = "Med", size = 3, hjust = 0.5, angle = 90, position = position_dodge2(width = 0.05))
  }
  
  # dot plot for 2030
  dots_30 = ggplot() +
    geom_point(data = df_30, aes(x = year, y = value, color = scenario), shape = 1, size = 1.5, position = position_dodge(width = 0.05)) +
    segment_code_30 +
    #text_code +
    scale_x_continuous(breaks = c(2030), labels = c("2030"), limits = c(2029.9, 2030.1)) +
    scale_y_continuous(limits = c(ymin, ymax)) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(panel.grid = element_blank(), plot.title = element_blank(),
          axis.text.y = element_blank(),
          axis.title.y = element_blank(), axis.title.x = element_blank(),
          axis.ticks = element_blank(), panel.border = element_blank(),
          legend.position = "none", plot.margin = margin(0,0,0,0))
  
  # dot plot for 2035
  dots_35 = ggplot() +
    geom_point(data = df_35, aes(x = year, y = value, color = scenario), shape = 1, size = 1.5, position = position_dodge(width = 0.05)) +
    segment_code_35 +
    scale_x_continuous(breaks = c(2035), labels = c("2035"), limits = c(2034.9, 2035.1)) +
    scale_y_continuous(limits = c(ymin,ymax)) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(panel.grid = element_blank(), plot.title = element_blank(),
          axis.text.y = element_blank(),
          axis.title.y = element_blank(), axis.title.x = element_blank(),
          axis.ticks = element_blank(), panel.border = element_blank(),
          legend.position = "none", plot.margin = margin(0,0,0,0))
  
  # combine all the plots
  final = fig + dots_30 + dots_35 + 
    plot_annotation(title = plot_title, theme = theme(plot.title = element_text(hjust = 0.5))) +
    plot_layout(widths = c(10,1,1)) +
    theme(plot.margin = margin(0,0,0,0))
  
  # return the full plot + the components + the summary stats
  return(list(
    full = final,
    line = fig,
    dot1 = dots_30,
    dot2 = dots_35,
    stats = stats
  ))
}


```

Some data manipulations
```{r}
duplicate_historical_data <- function(data_long, hist_model, hist_year, criteria = FALSE) {
  # short circuit
  if (hist_model == "none") {
    return(data_long)
  }

  # this is the data we'll stamp for every model
  copy_data = data_long %>% filter(model == hist_model, year == hist_year)
  # this is all the historical data, don't lose it
  hist_data = data_long %>% filter(model == hist_model & year <= hist_year)
  # temporary data_long which will be appended many times
  data_in = data_long %>% filter(year >= hist_year & model != hist_model)
  
  if (criteria) {
    data_25 = data_long %>% filter(model != hist_model, year == 2025) %>%
      mutate(year = hist_year)
    data_in = rbind(data_in, data_25)
  }
  
  data_wide = data_in %>% left_join(select(copy_data,c(value,year,variable,region)), by = c("year", "variable","region")) %>%
    mutate(value = case_when(
      year == hist_year & !is.na(value.y) ~ value.y,
      TRUE ~ value.x
    )) %>%
    select(-c(value.x,value.y))
  
  data_final = rbind(data_wide, hist_data)                        

  # the end
  return(data_final)
}

# remove all historical data and replace with EIA-LTS 2020 data for connectivity purposes
# clean_data2 = clean_data %>% duplicate_historical_data("EIA-LTS",2020)
```

Function for cone plots for LTS plots
```{r}
lts_coneplot_with_dots = function(config, data, figmap, lts_fignum, leep_fignum, region, ymin, ymax, metric = "mean", facet = FALSE) {
  # update the historical data (is this even necessary anymore?)
  # data2 = data %>% duplicate_historical_data("EIA-LTS",2020)
  
  # make the LTS cone plot
  fig1 = print_graph("cone_uncertainty", config, data, figmap, lts_fignum, region) +
    scale_y_continuous(limits = c(ymin, ymax)) +
    scale_x_continuous(breaks = c(2005, 2021, 2030, 2040, 2050), labels = c(2005, 2021, 2030, 2040, 2050)) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1), axis.ticks = element_blank())
    
  
  # extract points and summary statistics for 2030 and 2035
  df_30 = data_from_graph("cone_uncertainty", config, data, figmap, leep_fignum, region) %>%
    filter(year %in% c(2030))
  df_stat_30 = df_30 %>%
    group_by(scenario,year,variable_rename) %>%
    summarise(mean = mean(value),
           median = median(value))
  
  df_35 = data_from_graph("cone_uncertainty", config, data, figmap, leep_fignum, region) %>%
    filter(year %in% c(2035))
  df_stat_35 = df_35 %>%
    group_by(scenario,year,variable_rename) %>%
    summarise(mean = mean(value),
           median = median(value))
  
  if (facet) {
    dash_len = 2.0
  } else {
    dash_len = 0.5
  }
  
  if (metric == "mean") {
    segment_code_30 = geom_segment(data = df_stat_30, aes(x = year - dash_len, xend = year + dash_len, y = mean, yend = mean, 
                                                          color = variable_rename), position = position_dodge2(width = 0.5), linewidth = 1)
    segment_code_35 = geom_segment(data = df_stat_35, aes(x = year - dash_len, xend = year + dash_len, y = mean, yend = mean, 
                                                          color = variable_rename), position = position_dodge2(width = 0.5), linewidth = 1)
  } else if (metric == "median") {
    segment_code_30 = geom_segment(data = df_stat_30, aes(x = year - dash_len, xend = year + dash_len, y = median, yend = median, 
                                                          color = variable_rename), position = position_dodge2(width = 0.5), linewidth = 1)
    segment_code_35 = geom_segment(data = df_stat_35, aes(x = year - dash_len, xend = year + dash_len, y = median, yend = median, 
                                                          color = variable_rename), position = position_dodge2(width = 0.5), linewidth = 1)
  }

  
  fig2 = fig1 +
    geom_point(data = df_30, aes(x = year, y = value, color = variable_rename), shape = 1, size = 2, position = position_dodge(width = 1)) +
    segment_code_30 +
    geom_point(data = df_35, aes(x = year, y = value, color = variable_rename), shape = 1, size = 2, position = position_dodge(width = 1)) +
    segment_code_35 +
    theme(legend.position = "none", axis.title.x = element_blank())
    #bottom1
  return(fig2)
  
}

```

Faceted Versions
```{r}
# Buildings Energy
  p = lts_coneplot_with_dots(config, clean_data, figmap_leep_cone, 15, 16, "United States", 0, 15, "mean", facet = TRUE) +
    facet_grid(~factor(variable_rename, levels=c('Electricity', 'NonElectric')))
  p
  ggsave(filename = "output/leep/cone_uncertainty/Fig6.4_LTS_cone_buildings_facet.svg",p, width = 7, height = 5, units = "in")
  
# Transportation Energy
  p3 = lts_coneplot_with_dots(config, clean_data, figmap_leep_cone, 11, 12, "United States", 0, 30, "mean", facet = TRUE)
  p3 + facet_grid(~factor(variable_rename, levels=c('Fossil', 'Electricity', 'Alternative Fuels')))
  ggsave(filename = "output/leep/cone_uncertainty/Fig6.3_LTS_cone_transport_facet.svg",p3, width = 7, height = 5, units = "in")
  
# Industrial Energy
  p4 = lts_coneplot_with_dots(config, clean_data, figmap_leep_cone, 13, 14, "United States", 0, 25, "mean", facet = TRUE) +
    facet_grid(~factor(variable_rename, levels=c('Fossil', 'Electricity', 'Alternative Energy')))
  p4
  ggsave(filename = "output/leep/cone_uncertainty/Fig6.5_LTS_cone_industry_facet.svg",p4, width = 7, height = 5, units = "in")

# Economy-wide Emissions
  p5 = lts_coneplot_with_dots(config, clean_data, figmap_leep_cone, 9, 10, "United States", -100, 2500, "mean", facet = TRUE) +
    facet_grid(~factor(variable_rename, levels=c('Electricity', 'Transportation', 'Buildings', 'Industry')))
  p5
  ggsave(filename = "output/leep/cone_uncertainty/Fig6.2_LTS_cone_emissions_facet_Fig17.svg",p5, width = 7, height = 5, units = "in")
```


```{r}
# data table for LTS plots
models_leep = c("USREP-ReEDS", "EPS-EI", "GCAM-CGS", "GCAM-PNNL", "GCAM-USA", "Haiku-RFF", "IPM-NRDC",
                "IPM-EPA", "MARKAL-NETL", "NEMS-RHG", "NEMS-RHG", "OP-NEMS", "REGEN-EPRI", "RIO-REPEAT",
                "ReEDS-NREL", "Scout-LEEP", "EIA-LTS", "EIA-STEO", "IEA")

lts_data_table = function(focus, leep_models) {
  dta_lts = clean_data %>% 
    filter(variable == focus, model == "GCAM-LTS", scenario == "LTS.Mid1", year %in% c(2030, 2035)) %>%
    group_by(year, unit) %>%
    summarize(median = median(value), mean = mean(value)) %>%
    mutate(scenario = "NZ2050")
  
  dta_leep = clean_data %>% 
    filter(variable == focus, model %in% models_leep, year %in% c(2030, 2035), scenario != "No IRA") %>%
    group_by(year, unit) %>%
    summarize(median = median(value), mean = mean(value)) %>%
    mutate(scenario = "IRA")
  
  dta_combo = rbind(dta_lts, dta_leep) %>%
    mutate(variable = focus) %>%
    select(scenario, variable, year, unit, median, mean) %>%
    pivot_wider(names_from = scenario, values_from = c(mean, median)) %>%
    data.frame() %>%
    mutate(diff_median = median_IRA - median_NZ2050) %>%
    mutate(diff_mean = mean_IRA - mean_NZ2050) %>%
    mutate(pct_diff_median = diff_median / median_NZ2050) %>%
    mutate(pct_diff_mean = diff_mean / mean_NZ2050)
  return(dta_combo)
}

t = lts_data_table("Final Energy|Buildings|NonElectric", leep_models)

# Emissions
tab = rbind(lts_data_table("Emissions|CO2|Energy|Demand|Buildings", leep_models), 
      lts_data_table("Emissions|CO2|Energy|Demand|Industry", leep_models),
      lts_data_table("Emissions|CO2|Energy|Demand|Transportation", leep_models), 
      lts_data_table("Emissions|CO2|Energy|Supply|Electricity", leep_models))
print(tab)
write.csv(tab, "output/Emissions_LTS_table.csv", row.names = FALSE)

# Final Energy Transport
tab = rbind(lts_data_table("Final Energy|Transportation|Fossil", leep_models),
            lts_data_table("Final Energy|Transportation|Alternative Fuels", leep_models),
            lts_data_table("Final Energy|Transportation|Electricity", leep_models))
print(tab)
write.csv(tab, "output/Transportation_Energy_LTS_table.csv", row.names = FALSE)

# Final Energy Buildings
tab = rbind(lts_data_table("Final Energy|Buildings|Electricity", leep_models),
      lts_data_table("Final Energy|Buildings|NonElectric", leep_models))
print(tab)
write.csv(tab, "output/Buildings_Energy_LTS_table.csv", row.names = FALSE)

# Final Energy Industry
tab = rbind(lts_data_table("Final Energy|Industry|Fossil", leep_models),
            lts_data_table("Final Energy|Industry|Alternative Energy", leep_models), 
            lts_data_table("Final Energy|Industry|Electricity", leep_models))
print(tab)
write.csv(tab, "output/Industrial_Energy_LTS_table.csv", row.names = FALSE)


```

Overlaid Versions
```{r}
  # p = lts_coneplot_with_dots(config, clean_data, figmap_leep_cone, 1, 2, "United States", 0, 15, "mean", facet = FALSE)
  # p
  # ggsave(filename = "output/leep/cone_uncertainty/Fig19_LTS_cone_buildings.svg",p, width = 7, height = 5, units = "in")
  # # p2 = lts_coneplot_with_dots(config, clean_data, figmap_leep_cone, 3, 4, "United States", -1000, 2500, "mean", facet = FALSE)
  # # p2
  # # ggsave(filename = "output/leep/cone_uncertainty/LTS_cone_emissions_old.svg",p2, width = 7, height = 5, units = "in")
  # p3 = lts_coneplot_with_dots(config, clean_data, figmap_leep_cone, 5, 6, "United States", 0, 30, "mean", facet = FALSE)
  # p3
  # ggsave(filename = "output/leep/cone_uncertainty/Fig18_LTS_cone_transport.svg",p3, width = 7, height = 5, units = "in")
  # p4 = lts_coneplot_with_dots(config, clean_data, figmap_leep_cone, 7, 8, "United States", 0, 25, "mean", facet = FALSE)
  # p4
  # ggsave(filename = "output/leep/cone_uncertainty/Fig20_LTS_cone_industry.svg",p4, width = 7, height = 5, units = "in")
  # p5 = lts_coneplot_with_dots(config, clean_data, figmap_leep_cone, 3, 4, "United States", -1000, 2500, "mean", facet = FALSE)
  # p5
  # ggsave(filename = "output/leep/cone_uncertainty/Fig17_LTS_cone_emissions_new.svg",p5, width = 7, height = 5, units = "in")
```


```{r}
# uncertainty plot
model_labels = FALSE

clean_data2 = clean_data %>% duplicate_historical_data("EIA-STEO",2020, criteria = TRUE) %>% mutate(alpha = 1)
fig = print_graph("time_series", config, clean_data2, figmap_leep_timeseries, 16, "United States") +
   scale_alpha(range = c(0.6, 1), guide = "none")
dta = data_from_graph("time_series", config, clean_data, figmap_leep_timeseries, 16, "United States")
fig

sens = dot_plots_sens("time_series", config, clean_data2, figmap_leep_timeseries, 16, "United States", 0, 6000, "Emissions", metric = "median", 
                      labels = model_labels, historic_coord = c(2015,5000), iralow_coord = c(2030, 4400), 
                      irahigh_coord = c(2027, 2200))
print(sens$full)

ggsave(filename = "output/leep/time_series/Fig1.4_emis_sensitivity.svg",sens$full, width = 7, height = 5, units = "in")
```


```{r}
# EV share plot
scen_map = read.csv("./data-raw/scenario-mapping.csv") %>% select(datasrc, model, scenario, model_new, scenario_new)

raw = data_raw %>% select(model, scenario, region, variable, unit, datasrc, year, value) %>%
  left_join(scen_map, by = c("datasrc", "model", "scenario")) %>%
  select(-c(model, scenario)) %>%
  rename(model = model_new) %>%
  rename(scenario = scenario_new) %>%
  filter(unit != "thousands") %>%
  filter(!(model == "IEA" & year >= 2022))

iea_2022 = raw %>% filter(model == "IEA", year == 2021) %>% mutate(year = 2022)
clean_data4 = rbind(raw, iea_2022) %>% filter(unit != "thousands") %>% mutate(value = 100 * value) %>%
  filter(model != "EIA-LTS") %>% 
  duplicate_historical_data("IEA",2022, criteria = TRUE) %>% mutate(
    variable = case_when(
      variable %in% c("Energy Service|Transportation|Passenger|BEV|Sales Share",
                      "Energy Service|Transportation|Passenger|FCEV|Sales Share",
                      "Energy Service|Transportation|Passenger|HEV|Sales Share",
                      "Energy Service|Transportation|Freight|BEV|Sales Share",
                      "Energy Service|Transportation|Freight|FCEV|Sales Share",
                      "Energy Service|Transportation|Passenger|PHEV|Sales Share") ~ 
        "Energy Service|Transportation|EV|Sales Share")) %>%
  mutate(alpha = case_when(
    model == "USREP-ReEDS" ~ 1,
    model == "GCAM-PNNL" ~ 1,
    model == "IPM-EPA" ~ 1,
    scenario == "Historic" ~ 1,
    TRUE ~ 0.8)
  )

fig = print_graph("time_series", config, clean_data4, figmap_leep_timeseries, 18, "United States")
dta = data_from_graph("time_series", config, clean_data4, figmap_leep_timeseries, 18, "United States")
fig

      # annotate("text", x = 2015, y = 8, label = "Historic", color = "black", alpha = 1) +
      # annotate("text", x = 2030, y = 16, label = "No IRA", color = "#0388B3", alpha = 1) +
      # annotate("text", x = 2027, y = 45, label = "IRA", color = "#F28063", alpha = 1) +
p = dot_plots("time_series", config, clean_data4, figmap_leep_timeseries, 18, "United States", 0, 100, "EV Share", metric = "mean", hist_year = 2022, historic_coord = c(2015,8), preira_coord = c(2030, 16), ira_coord = c(2027, 45))
print(p$full)
print(p$stats)


ggsave(filename = "output/leep/time_series/Fig3.4_ev_share.svg",p$full, width = 7, height = 5, units = "in")
```

```{r}

# clean_data5 = data_raw %>% filter(grepl("GHGI",variable)) %>% 
#   select(-c(datasrc,Model,Scenario,Region,Variable,Unit,...34,...35)) %>%
#   gather("year","value","2020":"2018") %>%
#   filter(year >= 1990 & year <= 2021) %>%
#   mutate(year = as.factor(year), datasrc = "x")


fig = print_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 3, "United States", 
                  level_var = c("Lubricants", "Motorcycles", "Buses", "Pipelines", "Rail", 
                                "Water", "Aircraft", "MHD Trucks", "LD Trucks", "Passenger Cars")) +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5)) +
  bottom1

fig
dta = data_from_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 3, "United States")
dta

# iea_2022 = clean_data %>% filter(model == "IEA", year == 2021) %>% mutate(year = 2022)
# clean_data3 = rbind(clean_data, iea_2022)
# clean_data3 = clean_data3 %>% filter(model != "EIA-LTS") %>% 
#   duplicate_historical_data("IEA",2022) %>% 
#   mutate(value = 100 * value)
# 
# fig = print_graph("time_series", config, clean_data3, figmap_leep_timeseries, 18, "United States")
# dta = data_from_graph("time_series", config, clean_data3, figmap_leep_timeseries, 18, "United States")
# fig
# 
# p = dot_plots("time_series", config, clean_data3, figmap_leep_timeseries, 18, "United States", 0, 2, "EV Share", metric = "mean")
# print(p$full)
# print(p$stats)


ggsave(filename = "output/leep/stacked_bar/Fig3.1_trans_co2.svg",fig, width = 7, height = 5, units = "in")
```


```{r}
# capacity addition plot

ymin = -40
ymax = 130

subpalettes = create_subpalettes(figmap_leep_stackbar, config)

fig = print_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 4, "United States") +
  scale_subpalette(subpalettes, "Capacity Additions2") +
  scale_y_continuous(limits = c(ymin, ymax)) +
  ggtitle("Historical Annual Capacity Additions") +
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5, size = 10),
        axis.text.x = element_text(angle = 45))

dta = data_from_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 4, "United States")

fig

# var_map = data.frame("variable" = c("Capacity Additions|Electricity|Coal|w/ CCS",
#                                     "Capacity Additions|Electricity|Coal|w/o CCS",
#                                     "Capacity Additions|Electricity|Gas|w/ CCS",
#                                     "Capacity Additions|Electricity|Gas|w/o CCS",
#                                     "Capacity Additions|Electricity|Hydro",
#                                     "Capacity Additions|Electricity|Nuclear",
#                                     "Capacity Additions|Electricity|Solar",
#                                     "Capacity Additions|Electricity|Wind",
#                                     "Capacity Additions|Electricity|Storage Capacity",
#                                     "Capacity Retirements|Electricity|Coal|w/ CCS",
#                                     "Capacity Retirements|Electricity|Coal|w/o CCS",
#                                     "Capacity Retirements|Electricity|Gas|w/ CCS",
#                                     "Capacity Retirements|Electricity|Gas|w/o CCS",
#                                     "Capacity Retirements|Electricity|Hydro",
#                                     "Capacity Retirements|Electricity|Nuclear",
#                                     "Capacity Retirements|Electricity|Solar",
#                                     "Capacity Retirements|Electricity|Wind",
#                                     "Capacity Retirements|Electricity|Storage Capacity"),
#                      "variable_rename" = c("Coal CCS", "Coal", "Gas CCS", "Gas", "Hydro", "Nuclear",
#                                       "Solar", "Wind", "Storage",
#                                       "Coal CCS", "Coal", "Gas CCS", "Gas", "Hydro", "Nuclear",
#                                       "Solar", "Wind", "Storage"))
# 
# dta = data_from_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 4, "United States")
# dta
# dta2 = data_from_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 5, "United States") %>%
#   mutate(unit = "GW/yr") %>%
#   group_by(model, scenario, variable, region, datasrc, unit) %>%
#   summarize(value = mean(value)) %>%
#   mutate(value = case_when(
#     grepl("Retire",variable) ~ -1 * value,
#     TRUE ~ value
#   )) %>% left_join(var_map, by = "variable") %>%
#   group_by(model, scenario, region, datasrc, unit, variable_rename) %>%
#   summarize(value = sum(value))
# 
# dta_ttl = dta2 %>% group_by(model, scenario, region, datasrc, unit) %>%
#   summarize(value = sum(value)) %>% 
#   mutate(variable_rename = "Total")
# 
# dta3 = rbind(dta2, dta_ttl) %>%
#   mutate(variable_rename = factor(variable_rename, levels = c("Total", "Solar", "Wind", "Nuclear", "Hydro", "Storage", "Coal", "Coal CCS", "Gas", "Gas CCS")))
# 
# stats = dta3 %>% group_by(variable_rename) %>% summarize(mean = mean(value), median = median(value))

# dotplot = dta3 %>% ggplot() +
#   geom_point(aes(x = variable_rename, y = value, color = variable_rename), shape = 1, size = 2) + 
#   #geom_point(data = stats, aes(x = variable_rename, y = median, color = variable_rename), shape = 3, size = 2) +
#   geom_segment(data = stats, aes(x = as.numeric(variable_rename) - 0.2, xend = as.numeric(variable_rename) + 0.2, y = median, yend = median, color = variable_rename), linewidth = 0.5) +
#   scale_y_continuous(limits = c(ymin, ymax)) +
#   scale_subpalette(subpalettes, "Capacity Additions2") +
#   theme_emf() +
#   theme(plot.title = element_blank(), axis.text.y = element_blank(),
#         axis.title.y = element_blank(), axis.ticks = element_blank(),
#         axis.title.x = element_blank(),
#         axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "None")
# dotplot

dta4 = data_from_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 6, "United States")
dta_ttl = dta4 %>% 
  mutate(temp = case_when(
    grepl("Additions",variable) ~ "Capacity Additions",
    TRUE ~ "Capacity Retirements")) %>%
  group_by(model, scenario, region, datasrc, unit, temp) %>%
  summarize(value = sum(value)) %>% 
  select(-temp) %>%
  mutate(variable_rename = "Total")

dta4 = rbind(dta4,dta_ttl) %>% mutate(variable_rename = factor(variable_rename, 
                                  levels = c("Total", "Solar", "Wind", "Storage", "Coal CCS", "Gas CCS", "Gas", "Hydro", "Nuclear", "Coal"))) %>%
  mutate(stagger = case_when((variable_rename %in% c("Coal", "Nuclear", "Gas", "Total") & (value >= 0)) ~ -0.1,
                             (variable_rename %in% c("Coal", "Nuclear", "Gas", "Total") & (value < 0)) ~ 0.1,
                             TRUE ~ 0))

stats = dta4 %>% group_by(variable_rename, stagger) %>% summarize(mean = mean(value), median = median(value))

dotplot2 = dta4 %>% ggplot() + 
  geom_point(aes(x = (as.numeric(variable_rename) + stagger), y = value, color = variable_rename), shape = 16, size = 2) + 
  #geom_point(data = stats, aes(x = variable_rename, y = median, color = variable_rename), shape = 3, size = 2) +
  geom_segment(data = stats, aes(x = as.numeric(variable_rename) - 0.25 + stagger, xend = as.numeric(variable_rename) + 0.25 + stagger, 
                                 y = median, yend = median, color = variable_rename), linewidth = 0.5) +
  scale_x_continuous(breaks = seq(1,10), labels = c("Total", "Solar", "Wind", "Storage", "Coal CCS", "Gas CCS", "Gas", "Hydro", "Nuclear", "Coal")) +
  scale_y_continuous(limits = c(ymin, ymax)) +
  scale_subpalette(subpalettes, "Capacity Additions2") +
  ggtitle("Average Annual Capacity Additions (2021-2035)") +
  theme_emf() +
  theme(plot.title = element_text(hjust = 0.5, size = 10), axis.text.y = element_blank(),
        axis.title.y = element_blank(), axis.ticks = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none")
dotplot2
  

combined = 
  fig + dotplot2 + 
  plot_annotation(title = "Capacity Additions/Retirements (GW)",
                  theme = theme(plot.title = element_text(hjust = 0.5))) +
    plot_layout(widths = c(1,1)) +
    theme(plot.margin = margin(0,0,0,0))
    # bottom1
combined


ggsave(filename = "output/leep/stacked_bar/Fig2.4_capacity.svg",combined, width = 7, height = 5, units = "in")
print(stats)
```
```{r}
# industrial final energy plots

clean_data6 = clean_data %>% duplicate_historical_data("EIA-LTS", 2020) %>%
  filter(model != "GCAM-PNNL")

p1 = dot_plots("time_series", config, clean_data6, figmap_leep_timeseries, 19, "United States", 0, 30, "Industrial Final Energy: Fossil", metric = "median", historic_coord = c(2015,15), preira_coord = c(2030, 16), ira_coord = c(2027, 25))
print(p1$full)
ggsave(filename = "output/leep/time_series/Fig5.3_industrial_energy_fossil.svg",p1$full, width = 7, height = 5, units = "in")
print(p1$stats)


p2 = dot_plots("time_series", config, clean_data6, figmap_leep_timeseries, 20, "United States", 0, 5, "Industrial Final Energy: Fossil", metric = "median", historic_coord = c(2015,3.2), preira_coord = c(2030, 3), ira_coord = c(2027, 4))
print(p2$full)
ggsave(filename = "output/leep/time_series/Fig5.4_industrial_energy_elec.svg",p2$full, width = 7, height = 5, units = "in")
print(p2$stats)

p3 = dot_plots("time_series", config, clean_data6, figmap_leep_timeseries, 21, "United States", 0, 5, "Industrial Final Energy: Fossil", metric = "median", historic_coord = c(2015,3.2), preira_coord = c(2032, .75), ira_coord = c(2027, .6))
print(p3$full)
ggsave(filename = "output/leep/time_series/Fig5.5_industrial_energy_alternative.svg",p3$full, width = 7, height = 5, units = "in")
print(p3$stats)


dta = data_from_graph("time_series", config, clean_data, figmap_leep_timeseries, 19, "United States")
# View(dta)

```
```{r}
print_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 7, "United States")
dta = data_from_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 7, "United States") %>%
  mutate(variable_rename2 = case_when(
    grepl("Commercial", variable) ~ "Buildings",
    grepl("Residential", variable) ~ "Buildings",
    grepl("Industry", variable) ~ "Industrial",
    grepl("Electricity", variable) ~ "Electricity Generation",
    grepl("Transportation", variable) ~ "Transportation",
    TRUE ~ "Unknown")
  ) %>%
  mutate(variable_rename2 = factor(variable_rename2, levels = c("Buildings", "Industrial", "Transportation", "Electricity Generation")))

totals = dta %>% group_by(variable_rename2, year) %>% summarize(value = sum(value)) %>%
  mutate(value = round(value,0))

dta2 = data_from_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 8, "United States") %>%
  mutate(variable_rename2 = case_when(
      grepl("Commercial", variable) ~ "Buildings",
      grepl("Residential", variable) ~ "Buildings",
      grepl("Industry", variable) ~ "Industrial",
      grepl("Electricity", variable) ~ "Electricity Generation",
      grepl("Transportation", variable) ~ "Transportation",
      TRUE ~ "Unknown")
    )
eg = data.frame("variable_rename2" = c("Electricity Generation", "Electricity Generation"), "value" = c(0,0), 
                "variable_rename" = c("Indirect", "Indirect"), year = c(2005, 2021))
dta2 = rbind(dta2,eg) %>%
  mutate(variable_rename2 = factor(variable_rename2, levels = c("Buildings", "Industrial", "Transportation", "Electricity Generation")))

totals2 = dta2 %>% group_by(variable_rename2, year) %>% summarize(value = sum(value)) %>%
  mutate(value = round(value,0))

subpalettes = create_subpalettes(figmap_leep_stackbar, config)

p1 = dta %>% ggplot() +
  geom_bar(aes(x = variable_rename2, y = value, fill = variable_rename), position = "stack", stat = "identity") + 
  geom_text(data = totals, aes(x = variable_rename2, y = value, label = value), vjust = -0.4, stat = "identity", size = 3) +
  facet_grid(cols = vars(year)) +
  scale_y_continuous(limits = c(0, 2600)) +
  scale_subpalette(subpalettes, "Emissions Direct") +
  theme_emf() + 
  labs(y = "MMT CO2") +
  theme(axis.text.x = element_blank(), plot.margin = margin(0,0,0,0),
        axis.title.x = element_blank(), axis.ticks = element_blank())
p1

p2 = dta2 %>% ggplot() +
  geom_bar(aes(x = variable_rename2, y = value, fill = variable_rename), position = "stack", stat = "identity") + 
  geom_text(data = totals2, aes(x = variable_rename2, y = value, label = value), vjust = -0.4, stat = "identity", size = 3) +
  facet_grid(cols = vars(year)) +
  scale_y_continuous(limits = c(0, 2600)) +
  scale_subpalette(subpalettes, "Emissions Direct") +
  # scale_x_discrete(breaks = c("Buildings", "Industrial", "Transportation", "Electricity Generation"), 
  #                  labels = c("Buildings", "Industrial", "Transportation", "Electricity Generation")) +
  theme_emf() + 
  labs(y = "MMT CO2") +
  theme(axis.text.x = element_text(angle = 45, size = 7, hjust = 1),
        axis.title.x = element_blank(), axis.ticks = element_blank(),
        strip.text.x = element_blank(), plot.margin = margin(0,0,0,0))
p2

combined = p1 / p2 +
  plot_annotation(title = "Emissions from Fossil Fuel Combustion by Sector and Fuel Type", 
                  theme = theme(plot.title = element_text(hjust = 0.5))) +
  plot_layout(guides = "collect")
combined
ggsave(filename = "output/leep/stacked_bar/Fig1.1_emissions.svg",combined, width = 7, height = 5, units = "in")


  

```

More

```{r}
clean_data7 = clean_data %>% duplicate_historical_data("EPA",2021, criteria = TRUE) %>%
  mutate(alpha = case_when(
    model == "USREP-ReEDS" ~ 1,
    model == "GCAM-PNNL" ~ 1,
    model == "IPM-EPA" ~ 1,
    scenario == "Historic" ~ 1,
    TRUE ~ 0.8)
  ) %>%
  filter(value > 1e-4)

nox = print_graph("time_series", config, clean_data7, figmap_leep_timeseries, 22, "United States") +
  scale_alpha(range = c(0.6, 1), guide = "none")
nox

sox = print_graph("time_series", config, clean_data7, figmap_leep_timeseries, 23, "United States") +
  scale_alpha(range = c(0.6, 1), guide = "none")
sox

nox_full = dot_plots("time_series", config, clean_data7, figmap_leep_timeseries, 22, "United States", 0, 3, "Power Sector NOx Emissions", metric = "median", 
                     historic_coord = c(2015,1.8), preira_coord = c(2030, 0.95), ira_coord = c(2029, 0.15))
print(nox_full$full)
print(nox_full$stats)
ggsave(filename = "output/leep/time_series/Fig2.5_nox.svg",nox_full$full, width = 7, height = 5, units = "in")

sox_full = dot_plots("time_series", config, clean_data7, figmap_leep_timeseries, 23, "United States", 0, 5, "Power Sector SO2 Emissions", metric = "median", 
                     historic_coord = c(2017,2), preira_coord = c(2030, 1.2), ira_coord = c(2029, 0.12))
print(sox_full$full)
print(sox_full$stats)
ggsave(filename = "output/leep/time_series/Fig2.6_sox.svg",sox_full$full, width = 7, height = 5, units = "in")



dta = data_from_graph("time_series", config, clean_data7, figmap_leep_timeseries, 22, "United States")
# View(dta)
```

```{r}
# Figure 1.1
subpalettes = create_subpalettes(figmap_leep_stackbar, config)
subpalettes$`Emissions Stack`[["Electricity Generation"]] = "#0388B3"
subpalettes$`Emissions Stack`[["Other Sectors"]] = "#DEDEDE"

emis_stack = function(dta, title) {
  totals = dta %>% group_by(year) %>%
    summarize(value = sum(value))
  
  dta = dta %>% group_by(year, variable_rename) %>%
    summarize(value = sum(value))
  
  p = dta %>% ggplot() +
    geom_bar(aes(x = year, y = value, fill = variable_rename), position = position_stack(), stat = "identity") +
    geom_text(aes(x = year, y = value, label = round(value, 0), fill = variable_rename), size = 2.5, position = position_stack(vjust = 0.5, reverse = FALSE)) +
    geom_text(data = totals, aes(x = year, y = value, label = round(value, 0)), vjust = -0.4, stat = "identity", size = 2.5) +
    labs(y = "Mt CO2/yr", title = title) +
    scale_subpalette(subpalettes, "Emissions Stack") +
    theme_emf() + 
    theme(axis.ticks = element_blank(), axis.title.x = element_blank()) + 
    bottom1
    
  return(p)  
}

dta1 = data_from_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 9, "United States") %>%
  mutate(variable_rename = factor(variable_rename, 
                                  levels = c("Industry: Indirect", "Industry: Direct", "Buildings: Indirect", 
                                             "Buildings: Direct", "Transportation: Indirect", "Transportation: Direct")))

p1 = emis_stack(dta1, "Economy-Wide Emissions")
p1
ggsave(filename = "output/leep/stacked_bar/Fig1.1_emis.svg",p1, width = 7, height = 5, units = "in")


# 3.1
dta2 = data_from_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 9, "United States") %>%
  mutate(variable_rename = case_when(
    variable_rename == "Transportation: Direct" ~ variable_rename,
    variable_rename == "Transportation: Indirect" ~ variable_rename,
    TRUE ~ "Other Sectors"
  )) %>%
  mutate(variable_rename = factor(variable_rename, 
                                  levels = c("Other Sectors", "Transportation: Indirect", "Transportation: Direct")))

p2 = emis_stack(dta2, "Transportation Emissions")
p2
ggsave(filename = "output/leep/stacked_bar/Fig3.1_emis_trans.svg",p2, width = 7, height = 5, units = "in")


# 4.1
dta3 = data_from_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 9, "United States") %>%
  mutate(variable_rename = case_when(
    variable_rename == "Buildings: Direct" ~ variable_rename,
    variable_rename == "Buildings: Indirect" ~ variable_rename,
    TRUE ~ "Other Sectors"
  )) %>%
  mutate(variable_rename = factor(variable_rename, 
                                  levels = c("Other Sectors", "Buildings: Indirect", "Buildings: Direct")))

p3 = emis_stack(dta3, "Buildings Emissions")
p3
ggsave(filename = "output/leep/stacked_bar/Fig4.1_emis_build.svg",p3, width = 7, height = 5, units = "in")


# 5.1
dta4 = data_from_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 9, "United States") %>%
  mutate(variable_rename = case_when(
    variable_rename == "Industry: Direct" ~ variable_rename,
    variable_rename == "Industry: Indirect" ~ variable_rename,
    TRUE ~ "Other Sectors"
  )) %>%
  mutate(variable_rename = factor(variable_rename, 
                                  levels = c("Other Sectors", "Industry: Indirect", "Industry: Direct")))

p4 = emis_stack(dta4, "Industrial Emissions")
p4
ggsave(filename = "output/leep/stacked_bar/Fig5.1_emis_ind.svg",p4, width = 7, height = 5, units = "in")


# 2.1 (MAYBE)
dta5 = data_from_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 9, "United States") %>%
  mutate(variable_rename = case_when(
    variable_rename == "Industry: Indirect" ~ "Electricity Generation",
    variable_rename == "Buildings: Indirect" ~ "Electricity Generation",
    variable_rename == "Transportation: Indirect" ~ "Electricity Generation",
    TRUE ~ "Other Sectors"
  )) %>%
  mutate(variable_rename = factor(variable_rename, 
                                  levels = c("Other Sectors", "Electricity Generation")))

p5 = emis_stack(dta5, "Electric Sector Emissions")
p5
ggsave(filename = "output/leep/stacked_bar/Fig2.1_emis_elec.svg",p5, width = 7, height = 5, units = "in")

#CH4, N2O, HFCs

```
```{r}
subpalettes = create_subpalettes(figmap_leep_stackbar, config)
subpalettes$`Total GHGs4`[["CO2"]] = "#0388B3"

dta = data_from_graph("stacked_bar", config, clean_data, figmap_leep_stackbar, 13, "United States")
diff = dta %>% mutate(value = case_when(
    variable == "Emissions|Non-CO2 GHG" ~ -value, 
    TRUE ~ value
  )) %>%
  group_by(year) %>% summarize(value = sum(value)) %>%
  mutate(variable = "Emissions|CO2", unit = "Mt CO2e/yr", variable_rename = "CO2")
dta2 = rbind(dta,diff) %>% filter(variable != "Emissions|GHG") %>%
  mutate(variable_rename = factor(variable_rename, levels = c("NonCO2","CO2")))

totals = dta2 %>% group_by(year) %>% summarize(value = sum(value))

p = dta2 %>% ggplot() +
  geom_bar(aes(x = year, y = value, fill = variable_rename), position = position_stack(reverse = FALSE), stat = "identity") +
  geom_text(aes(x = year, y = value, fill = variable_rename, label = round(value, 0)), position = position_stack(reverse = FALSE, vjust = 0.5), stat = "identity") +
  geom_text(data = totals, aes(x = year, y = value, label = round(value, 0)), vjust = -0.4, stat = "identity") +
  scale_subpalette(subpalettes, "Total GHGs4") +
  scale_x_continuous(breaks = c(2005, 2021), labels = c(2005, 2021)) +
  scale_y_continuous(limits = c(0, 8000)) +
  labs(y = "Mt CO2e/yr", title = "Total Historic GHG Emissions: 2005, 2021") +
  theme_emf() + 
  theme(axis.ticks = element_blank(), axis.title.x = element_blank(),
        plot.title = element_text(hjust = 0.5))
p

ggsave(filename = "output/leep/stacked_bar/Fig1.1a_emis_nonco2ghg.svg",p, width = 7, height = 5, units = "in")


```
