---
title: "LEEP Pre-Brief"
output: 
  html_document:
    toc: true
    toc_float: true
date: "`r Sys.time()`"
params:
  mode: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
knitr::opts_knit$set(root.dir = here::here())
```

```{r}
if(is.null(params$mode)) {
  source("packages.R")
  devtools::load_all(here())
}

# load data from targets pipeline
targets::tar_load(config)
targets::tar_load(clean_data)
targets::tar_load(figmap_leep_timeseries)
targets::tar_load(figmap_leep_stackbar)

# temporary filter on clean data
clean_data = clean_data %>%
  filter(!(model == "IPM-EPA" & year == 2025))
```

# Summary Range

## Core only

```{r}
Econ_data = spg_clean(
  99,
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "Haiku-RFF"),
  "EPA-GHGI",
  config,
  clean_data,
  figmap_leep_timeseries
)

Elec_data = spg_clean(
  98,
  c("Scout-LEEP"),
  "EPA-GHGI",
  config,
  clean_data,
  figmap_leep_timeseries
)

Tran_data = spg_clean(
  19,
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP"),  
  "EPA-GHGI",
  config,
  clean_data,
  figmap_leep_timeseries
)

Ind_data = spg_clean(
  21, 
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP"),
  "EPA-GHGI", 
  config,
  clean_data, 
  figmap_leep_timeseries)

Buil_data = spg_clean(
  23, 
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL"), 
  "EPA-GHGI", 
  config, 
  clean_data, 
  figmap_leep_timeseries)

subpalettes = create_subpalettes(figmap_leep_timeseries, config)

indicators_econ = Econ_data %>% filter(year %in% c(2030, 2035))
indicators_econ_baseline = Econ_data %>% filter(year == 2005)

indicators_elec = Elec_data %>% filter(year %in% c(2030, 2035))
indicators_elec_baseline = Elec_data %>% filter(year == 2005)

indicators_tran = Tran_data %>% filter(year %in% c(2030, 2035))
indicators_tran_baseline = Tran_data %>% filter(year == 2005)

indicators_ind = Ind_data %>% filter(year %in% c(2030, 2035))
indicators_ind_baseline = Ind_data %>% filter(year == 2005)

indicators_buil = Buil_data %>% filter(year %in% c(2030, 2035))
indicators_buil_baseline = Buil_data %>% filter(year == 2005)

indicators_all = bind_rows(indicators_econ, indicators_elec, 
                           indicators_tran, indicators_ind, indicators_buil)
indicators_all_baseline = bind_rows(indicators_econ_baseline, 
                                    indicators_elec_baseline, indicators_tran_baseline,
                                    indicators_ind_baseline, indicators_buil_baseline)

variable_rename = data.frame("variable" = c("Emissions|CO2", "Emissions|CO2|Energy|Demand|Transportation|Total",
                                            "Emissions|CO2|Energy|Supply|Electricity",
                                            "Emissions|CO2|Energy|Demand|Industry and Fuel Production|Total",
                                            "Emissions|CO2|Energy|Demand|Buildings|Total"), 
                             "sector" = c("Economy-Wide", "Transportation", 
                                          "Electricity", "Industry", "Buildings"))

indicators_all = indicators_all %>% left_join(
  (indicators_all_baseline %>%
     mutate(value_2005 = value) %>%
     select(variable, value_2005)), 
  by = c("variable")) %>%
  # we're plotting reductions - so multiplying this by -1
  mutate(pct_diff = -100 * (value - value_2005) / value_2005) %>%
  left_join(variable_rename, by = "variable") %>%
  select(-variable) %>%
  mutate(category = interaction(sector, scenario)) %>%
  mutate(category = factor(category, levels = c(
    "Industry.No IRA", "Industry.IRA",
    "Buildings.No IRA", "Buildings.IRA",
    "Transportation.No IRA", "Transportation.IRA",
    "Electricity.No IRA", "Electricity.IRA",
    "Economy-Wide.No IRA", "Economy-Wide.IRA"
  ))) %>%
  mutate(scenario = factor(scenario, levels = c("IRA", "No IRA")))

indicators_summ = indicators_all %>% 
  group_by(category, year, sector, scenario) %>%
  summarize(min = min(pct_diff),
            max = max(pct_diff),
            median = median(pct_diff))

p1 = ranges(indicators_all, indicators_summ, "Economy-Wide", bottom = TRUE, top = FALSE,
                     subtitle = expression(paste("Economy-Wide C",O[2], " Emissions Reductions")))
p2 = ranges(indicators_all, indicators_summ, "Electricity", bottom = FALSE, top = TRUE,
                     subtitle = expression(paste("Electricity C", O[2], " Emissions Reductions")))
p3 = ranges(indicators_all, indicators_summ, "Transportation", 
                     subtitle = expression(paste("Transportation C", O[2], " Emissions Reductions (Direct + Indirect from Electricity)")))
p4 = ranges(indicators_all, indicators_summ, "Buildings", 
                     subtitle = expression(paste("Buildings C", O[2], " Emissions Reductions (Direct + Indirect from Electricity)")))
p5 = ranges(indicators_all, indicators_summ, "Industry", bottom = FALSE, top = FALSE,
                     subtitle = expression(paste("Industry C", O[2], " Emissions Reductions (Direct + Indirect from Electricity)")))

combined = (p2 / p3 / p4 / p5 / p1) +
  plot_layout(guides = "collect") +
#  annotate("segment", x = 50, xend = 50, y = 0, yend = 100, color = "blue") +
#  plot_annotation(theme = theme(legend.position = "top")) + 
  theme(plot.margin = margin(0, 0, 0, 0))
combined

ggsave(filename = "output/pre-brief/summary_range_core.png",
         plot = combined,
         width = 7,
         height = 5,
         units = "in")

indicators_all_clean = indicators_all %>% 
  select(model,scenario,unit,region,title_name.y,year,value,value_2005,pct_diff) %>% 
  rename(`percent diff 2005` = pct_diff)

summary_IRA = indicators_summ %>%
  ungroup() %>%
  select(sector, scenario, year, min, median, max) %>%
  filter(scenario == "IRA") %>%
  select(sector, year,
         `IRA Min` = min, `IRA Median` = median, `IRA Max` = max)

summary_NoIRA = indicators_summ %>%
  ungroup() %>%
  select(sector, scenario, year, min, median, max) %>%
  filter(scenario == "No IRA")%>%
  select(sector, year,
         `No IRA Min` = min, `No IRA Median` = median, `No IRA Max` = max)

summary_core = merge(summary_IRA, summary_NoIRA, by = c("sector", "year"))

write.xlsx(summary_core, "output/pre-brief/summary_range_table_all_sensitivities.xlsx")
```

## All sensitivities

```{r}
clean_data1 = clean_data  %>%
  mutate(region = "United States") %>%
  mutate(model = case_when(
    datasrc == "ReEDS_compiled.csv" ~ "ReEDS-NRELr",
    TRUE~model)) %>%
  mutate(region = "United States") %>%
  # remove bistline models with incorrect indirect emissions for end-use sectors
  # MARKAL-NETL sensitivities included here, but we exclude from LEEP Report sensitivity analysis: should decide what to do
  filter(!(model %in% c("GCAM-CGS","MARKAL-NETL","REGEN-EPRI") & 
             scenario %in% c("IRA.Low","IRA.High") &
             variable %in% c("Emissions|CO2|Energy|Demand|Buildings|Total",
                             "Emissions|CO2|Energy|Demand|Industry and Fuel Production|Total",
                             "Emissions|CO2|Energy|Demand|Transportation|Total"))) %>%
  filter(!(model %in% c("MARKAL-NETL") & 
             scenario %in% c("IRA.Low","IRA.High") &
             variable %in% c("Emissions|CO2|Energy|Supply|Electricity")))
  
Econ_data = spg_clean(
  1000,
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "Haiku-RFF"),
  "EPA-GHGI",
  config,
  clean_data1,
  figmap_leep_timeseries
)

Elec_data = spg_clean(
  1001,
  c("Scout-LEEP"),
  "EPA-GHGI",
  config,
  clean_data1,
  figmap_leep_timeseries
)

Tran_data = spg_clean(
  1002,
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP"),  
  "EPA-GHGI",
  config,
  clean_data1,
  figmap_leep_timeseries
)

Ind_data = spg_clean(
  1003, 
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP"),
  "EPA-GHGI", 
  config,
  clean_data1, 
  figmap_leep_timeseries)

Buil_data = spg_clean(
  1004, 
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL"), 
  "EPA-GHGI", 
  config, 
  clean_data1, 
  figmap_leep_timeseries)

subpalettes = create_subpalettes(figmap_leep_timeseries, config)

indicators_econ = Econ_data %>% filter(year %in% c(2030, 2035))
indicators_econ_baseline = Econ_data %>% filter(year == 2005)

indicators_elec = Elec_data %>% filter(year %in% c(2030, 2035))
indicators_elec_baseline = Elec_data %>% filter(year == 2005)

indicators_tran = Tran_data %>% filter(year %in% c(2030, 2035))
indicators_tran_baseline = Tran_data %>% filter(year == 2005)

indicators_ind = Ind_data %>% filter(year %in% c(2030, 2035))
indicators_ind_baseline = Ind_data %>% filter(year == 2005)

indicators_buil = Buil_data %>% filter(year %in% c(2030, 2035))
indicators_buil_baseline = Buil_data %>% filter(year == 2005)

indicators_all = bind_rows(indicators_econ, indicators_elec, 
                           indicators_tran, indicators_ind, indicators_buil) %>%
  mutate(scenario = case_when(
    str_detect(scenario, "No IRA") ~ "No IRA",
    TRUE~"IRA"))

indicators_all_baseline = bind_rows(indicators_econ_baseline, 
                                    indicators_elec_baseline, indicators_tran_baseline,
                                    indicators_ind_baseline, indicators_buil_baseline)

variable_rename = data.frame("variable" = c("Emissions|CO2", "Emissions|CO2|Energy|Demand|Transportation|Total",
                                            "Emissions|CO2|Energy|Supply|Electricity",
                                            "Emissions|CO2|Energy|Demand|Industry and Fuel Production|Total",
                                            "Emissions|CO2|Energy|Demand|Buildings|Total"), 
                             "sector" = c("Economy-Wide", "Transportation", 
                                          "Electricity", "Industry", "Buildings"))

indicators_all = indicators_all %>% left_join(
  (indicators_all_baseline %>%
     mutate(value_2005 = value) %>%
     select(variable, value_2005)), 
  by = c("variable")) %>%
  # we're plotting reductions - so multiplying this by -1
  mutate(pct_diff = -100 * (value - value_2005) / value_2005) %>%
  left_join(variable_rename, by = "variable") %>%
  select(-variable) %>%
  mutate(category = interaction(sector, scenario)) %>%
  mutate(category = factor(category, levels = c(
    "Industry.No IRA", "Industry.IRA",
    "Buildings.No IRA", "Buildings.IRA",
    "Transportation.No IRA", "Transportation.IRA",
    "Electricity.No IRA", "Electricity.IRA",
    "Economy-Wide.No IRA", "Economy-Wide.IRA"
  ))) %>%
  mutate(scenario = factor(scenario, levels = c("IRA", "No IRA")))

indicators_summ = indicators_all %>% 
  group_by(category, year, sector, scenario) %>%
  summarize(min = min(pct_diff),
            max = max(pct_diff),
            median = median(pct_diff))

p1 = ranges(indicators_all, indicators_summ, "Economy-Wide", bottom = TRUE, top = FALSE,
                     subtitle = expression(paste("Economy-Wide C",O[2], " Emissions Reductions")))
p2 = ranges(indicators_all, indicators_summ, "Electricity", bottom = FALSE, top = TRUE,
                     subtitle = expression(paste("Electricity C", O[2], " Emissions Reductions")))
p3 = ranges(indicators_all, indicators_summ, "Transportation", 
                     subtitle = expression(paste("Transportation C", O[2], " Emissions Reductions (Direct + Indirect from Electricity)")))
p4 = ranges(indicators_all, indicators_summ, "Buildings", 
                     subtitle = expression(paste("Buildings C", O[2], " Emissions Reductions (Direct + Indirect from Electricity)")))
p5 = ranges(indicators_all, indicators_summ, "Industry", bottom = FALSE, top = FALSE,
                     subtitle = expression(paste("Industry C", O[2], " Emissions Reductions (Direct + Indirect from Electricity)")))

combined = (p2 / p3 / p4 / p5 / p1) +
  plot_layout(guides = "collect") +
#  annotate("segment", x = 50, xend = 50, y = 0, yend = 100, color = "blue") +
#  plot_annotation(theme = theme(legend.position = "top")) + 
  theme(plot.margin = margin(0, 0, 0, 0))
combined

ggsave(filename = "output/pre-brief/summary_range_sensitivities.png",
         plot = combined,
         width = 7,
         height = 5,
         units = "in")

indicators_all_clean = indicators_all %>% 
  select(model,scenario,unit,region,title_name.y,year,value,value_2005,pct_diff) %>% 
  rename(`percent diff 2005` = pct_diff)

summary_IRA = indicators_summ %>%
  ungroup() %>%
  select(sector, scenario, year, min, median, max) %>%
  filter(scenario == "IRA") %>%
  select(sector, year,
         `IRA Min` = min, `IRA Median` = median, `IRA Max` = max)

summary_NoIRA = indicators_summ %>%
  ungroup() %>%
  select(sector, scenario, year, min, median, max) %>%
  filter(scenario == "No IRA")%>%
  select(sector, year,
         `No IRA Min` = min, `No IRA Median` = median, `No IRA Max` = max)

summary_all = merge(summary_IRA, summary_NoIRA, by = c("sector", "year"))

write.xlsx(summary_all, "output/pre-brief/summary_range_table_all_sensitivities.xlsx")
```

## Joint table

```{r}
core = summary_core[,1:5] %>%
  rename(coreMin = `IRA Min`,
         coreMed = `IRA Median`,
         coreMax = `IRA Max`)
all = summary_all[,3:5] %>%
  rename(allMin = `IRA Min`,
         allMed = `IRA Median`,
         allMax = `IRA Max`)
joint = cbind(core, all) %>%
  mutate(
    diffMin = allMin-coreMin,
    diffMed = allMed-coreMed,
    diffMax = allMax-coreMax
  )

write.xlsx(joint, "output/pre-brief/summary_range_changes.xlsx")
```

# EW Projections

```{r}
# TODO: delta figure doesnt work w/ multiple scenarios? or something...

EconSpg = spg2(Econ_data,
  "",
  expression(paste("Economy-wide C", O[2], " Emissions (Mt C", O[2], "/yr)")),
  gd = "none",
  0,
  6500,
  c(0, 2000, 4000, 6000),
  scales::comma,
  1, 
  c(2015, 4900), 
  c(2027.5, 5500), 
  c(2022, 3800), 
  config, 
  figmap_leep_timeseries) 

cleanEcon = EconSpg$data %>%
  mutate(scenario2 = case_when(
    !scenario %in% c("Historic","No IRA") ~ "IRA",
    TRUE~scenario
  ))

EconSpg = spg_msb(cleanEcon,
  "",
  expression(paste("Economy-wide C", O[2], " Emissions (Mt C", O[2], "/yr)")),
  gd = "none",
  0,
  6500,
  c(0, 2000, 4000, 6000),
  scales::comma,
  1, 
  c(2015, 4900), 
  c(2027.5, 5500), 
  c(2022, 3800), 
  config, 
  figmap_leep_timeseries) 

EconDot = dotted_msb(cleanEcon, EconSpg$figure, "median", 0, 7000, config, figmap_leep_timeseries)
EconDot

# saveall(EconDot, EconSpg$data, fig_no)

delta = delta_msb(1005, c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "Haiku-RFF"), config, clean_data, figmap_leep_timeseries)
delta
# saveall(delta$figure, delta$df, paste(fig_no, "delta"), wd = 3.012, ht = 3)
```
