---
title: "TJM_Revised"
author: "Tyler Minor"
date: "`r Sys.Date()`"
output: html_document
---

```{r Knit Setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, fig.height=5, fig.width=7, message=FALSE, warning=FALSE)
```

```{r Library, include=FALSE}
source("packages.R")
devtools::load_all(here())

tar_load(config)
tar_load(clean_data)
tar_load(figmap_leep_timeseries)
tar_load(figmap_leep_diffbar)

subpalettes = create_subpalettes(figmap_leep_timeseries, config)
```

```{r Print Function, include=FALSE}
drop_warn = function(drop) {
  if(drop == "") {
    print("No models have been dropped from this figure.")
  } else {
  paste("The model(s)", paste(drop, collapse = " & "), "have been dropped from this figure.")
  }
}
```

```{r Spaghetti Plot Function, include=FALSE}
spg = function(ts_map_ID, histsrc, title, yname, gd, drop, ymin, ymax, ybreaks, yax) {
  
  df = data_from_graph(
    "time_series",
    config,
    clean_data,
    figmap_leep_timeseries,
    ts_map_ID,
    "United States"
  ) %>%
    filter(!model %in% drop) %>%
    filter(!datasrc %in% drop) %>%
    mutate(
      alpha = case_when(
        model == "USREP-ReEDS" ~ 1,
        model == "GCAM-PNNL" ~ 1,
        model == "IPM-EPA" ~ 1,
        scenario == "Historic" ~ 1,
        T ~ 0.6
      )
    ) %>%
    filter(year <= 2021 &
             model == histsrc |
             year >= 2021 & scenario != "Historic") %>%
    pivot_wider(names_from = year, values_from = value) %>%
    mutate(`2021` = case_when(T ~ `2021`[model == histsrc])) %>%
    pivot_longer(cols = starts_with("20"),
                 names_to = "year",
                 values_to = "value") %>%
    filter(!is.na(value)) %>%
    mutate(year = as.numeric(year))
  
  figure = ggplot(df, aes(year,value, color = scenario, group = interaction(model, scenario))) + geom_line(aes(alpha = alpha), size = 0.5) +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme_emf() +
    scale_x_continuous(breaks = c(2005, 2021, 2025, 2030, 2035)) +
    scale_y_continuous(limits = c(ymin, ymax), breaks = ybreaks, labels = yax) +
    scale_alpha(range = c(0.5, 1), guide = F) + 
    labs(title = title, 
         x = element_blank(), 
         y = yname) +
        theme(legend.position = gd,
          axis.text.x = element_text(angle = 45, hjust = 1))
  
return(figure)
}

```

```{r Dots Function} 
dotted = function(df, spg, metric, ymin, ymax) {
  df_30 = df %>%
    filter(year %in% c(2030))
  df_stat_30 = df_30 %>%
    group_by(scenario,year,variable_rename) %>%
    summarise(mean = mean(value),
           median = median(value))
  
  df_35 = df %>%
    filter(year %in% c(2035))
  df_stat_35 = df_35 %>%
    group_by(scenario,year,variable_rename) %>%
    summarise(mean = mean(value),
           median = median(value))
  
  
  mean_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","mean"]$mean - df_stat_30[df_stat_30$scenario == "IRA","mean"]$mean
  mean_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","mean"]$mean - df_stat_35[df_stat_35$scenario == "IRA","mean"]$mean
  median_diff_30 = df_stat_30[df_stat_30$scenario == "No IRA","median"]$median - df_stat_30[df_stat_30$scenario == "IRA","median"]$median
  median_diff_35 = df_stat_35[df_stat_35$scenario == "No IRA","median"]$median - df_stat_35[df_stat_35$scenario == "IRA","median"]$median
  # stick em all in a data frame
  stats = data.frame("year" = c(2030,2035,2030,2035), "metric" = c("mean","mean","median","median"), 
                     "difference" = c(mean_diff_30, mean_diff_35, median_diff_30, median_diff_35))

  # a few of the ggplot lines of code vary based on the year or on the metric chosen, so conditionally choose the right one here
  if (metric == "mean") {
    segment_code_30 = geom_segment(data = df_stat_30, aes(x = year - 0.1, xend = year + 0.1, y = mean, yend = mean, color = scenario), 
                                   size = 1)
    segment_code_35 = geom_segment(data = df_stat_35, aes(x = year - 0.1, xend = year + 0.1, y = mean, yend = mean, color = scenario),
                                   size = 1)
  } else if (metric == "median") {
    segment_code_30 = geom_segment(data = df_stat_30, aes(x = year - 0.1, xend = year + 0.1, y = median, yend = median, color = scenario), 
                                   size = 1)
    segment_code_35 = geom_segment(data = df_stat_35, aes(x = year - 0.1, xend = year + 0.1, y = median, yend = median, color = scenario), 
                                   size = 1)
  }
  
  dots_30 = ggplot() +
    geom_point(data = df_30, aes(x = year, y = value, color = scenario, alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = 0.2)) +
    segment_code_30 +
    scale_x_continuous(breaks = c(2030), labels = c("2030"), limits = c(2029.9, 2030.1)) +
    scale_y_continuous(limits = c(ymin, ymax)) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(panel.grid = element_blank(), plot.title = element_blank(),
          axis.text.y = element_blank(),
          axis.text.x = element_text(angle = 45, hjust=1),
          axis.title.y = element_blank(), axis.title.x = element_blank(),
          axis.ticks = element_blank(), panel.border = element_blank(),
          legend.position = "none", plot.margin = margin(0,0,0,0))+
  scale_alpha(range = c(0.6, 1), guide = F)
  
  # dot plot for 2035
  dots_35 = ggplot() +
    geom_point(data = df_35, aes(x = year, y = value, color = scenario, alpha = alpha), shape = 1, size = 1.5, position = position_dodge(width = 0.2)) +
    segment_code_35 +
    scale_x_continuous(breaks = c(2035), labels = c("2035"), limits = c(2034.9, 2035.1)) +
    scale_y_continuous(limits = c(ymin,ymax)) +
    theme_emf() +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme(panel.grid = element_blank(), plot.title = element_blank(),
          axis.text.x = element_text(angle = 45, hjust=1),
          axis.text.y = element_blank(),
          axis.title.y = element_blank(), axis.title.x = element_blank(),
          axis.ticks = element_blank(), panel.border = element_blank(),
          legend.position = "none", plot.margin = margin(0,0,0,0))+
  scale_alpha(range = c(0.6, 1), guide = F)
  
    figure = spg + dots_30 + dots_35 +
    plot_layout(widths = c(10,1,1)) +
    theme(plot.margin = margin(0,0,0,0))
    
    return(figure)
}

```

```{r htmlTable Function, include=FALSE}
html = function(df, title) {
  base = df %>%
    filter(year == 2005)
  
  baseline = base$value[1]

base <- as.data.frame(base) %>%
  select(Year = year, 
         `Absolute Level (Mt CO2)` = value) %>%
  mutate(Scenario = "Baseline", 
    `% Reductions from 2005` = NA,
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA)  %>%
  select(Year, Scenario, `Absolute Level (Mt CO2)`, `% Reductions from 2005`, `% Reductions from No IRA`, `Reductions from No IRA (Mt CO2)`)

NoIRA <- df %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "No IRA") %>%
  group_by(year) %>%
  summarize(`No IRA Median` = median(value), 
            `No IRA Min` = min(value),
            `No IRA Max` =  max(value))%>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(`2005_perc_red` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100) %>%
  mutate(
    Year = year, 
    `% Reductions from 2005` = `2005_perc_red`, 
    `% Reductions from No IRA` = NA, 
    `Reductions from No IRA (Mt CO2)` = NA
  ) %>%
  select(!year & !`2005_perc_red`)

IRA <- df %>%
  filter(year == 2030 | year == 2035) %>%
  filter(scenario == "IRA") %>%
  select(!scenario) %>%
  group_by(year) %>%
  summarize(
    `IRA Max` = max(value), 
    `IRA Min` = min(value), 
    `IRA Median` = median(value)) %>%
  pivot_longer(cols = !year, names_to = "Scenario", values_to = "Absolute Level (Mt CO2)") %>%
  mutate(
    `% Reductions from 2005` = ((baseline-`Absolute Level (Mt CO2)`)/baseline) * 100
  )%>%
  mutate(
    `% Reductions from No IRA` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]) * 100,
      
            year == 2035 & Scenario == "IRA Max" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]) * 100, 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]) * 100, 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        ((NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)/NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]) * 100
    ), 

    `Reductions from No IRA (Mt CO2)` = case_when(
      year == 2030 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2030 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2030 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`),
      
            year == 2035 & Scenario == "IRA Max" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Max"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Median" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Median"]-`Absolute Level (Mt CO2)`), 
      
      year == 2035 & Scenario == "IRA Min" ~ 
        (NoIRA$`Absolute Level (Mt CO2)`[NoIRA$Year == 2035 & NoIRA$Scenario == "No IRA Min"]-`Absolute Level (Mt CO2)`)
    )
  ) %>%
  rename(Year = year)

IRA = rbind(NoIRA, IRA)

IRA <- IRA %>%
  arrange(desc(IRA)) %>%
  arrange(Year)

IRA = rbind(base, IRA)

IRA$`Absolute Level (Mt CO2)` = round(IRA$`Absolute Level (Mt CO2)`, 3)
IRA$`% Reductions from 2005` = round(IRA$`% Reductions from 2005`, 3)
IRA$`% Reductions from No IRA` = round(IRA$`% Reductions from No IRA`, 3)
IRA$`Reductions from No IRA (Mt CO2)` = round(IRA$`Reductions from No IRA (Mt CO2)`,3)

tab = IRA %>%
tableHTML(caption = paste(title), rownames = F)

return(tab)
}
```

```{r Percent Difference Function, include=FALSE}

#Function to create standard percent difference figs
pd = function(ts_map_ID, title, yname, gd, drop) {
  #Take data from leep_timeseries map based on ID.
  df = data_from_graph(
      "time_series",
      config,
      clean_data,
      figmap_leep_timeseries,
      ts_map_ID,
      "United States"
    ) %>%
    filter(!scenario == "No IRA") %>%
    filter(year > 2021) %>%
    filter(!model %in% drop)
  
  medians = df %>%
    filter(year %in% c(2030, 2035)) %>%
    filter(value != 0) %>%
    group_by(year) %>% 
    summarize(median = median(value))
  
  #Set 2021 value to zero for all models
  hist <- df %>%
    group_by(model) %>%
    slice(1) %>%
    mutate(scenario = "Historic",
           value = 0,
           year = 2021)
  
  #Stitch it back together with main data
  df <- rbind(df, hist)
  
  #Plot standard figure
  figure = ggplot() +
    geom_line(data = df, aes(
    x = year,
    y = value,
    group = model,
    color = model), 
    size = 0.75) + 
    geom_point(aes(x = 2021, y = 0), color = "black") + 
    geom_point(
      data = medians,
      aes(x = year, y = median),
      color = "black",
      shape = 16,
      size = 2
    ) + 
    scale_subpalette(subpalettes, "Emissions|CO2|Percent difference from No IRA") + #Standard subpallete
    labs(title = title,
         x = "",
         y = yname) +
    theme_emf() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      panel.spacing.x = unit(4, "mm"),
      legend.position = gd
    ) +
    scale_x_continuous(breaks = c(2021, 2025, 2030, 2035))
  return(figure)
}
```

```{r Absolute Difference Function, include=FALSE}
ad = function(diff_ID, title, yname, gd, drop) {
  
  df = data_from_graph("diff_bar",
                       config,
                       clean_data,
                       figmap_leep_diffbar,
                       diff_ID,
                       "United States") %>%
    filter(!model %in% drop) %>%
    filter(year > 2021)
  
  medians = df %>%
    filter(year %in% c(2030, 2035)) %>%
    group_by(year) %>%
    summarize(median = median(diff))
  
  hist <- df %>%
    group_by(model) %>%
    slice(1) %>%
    mutate(scenario = "Historic",
           diff = 0,
           year = 2021)
  
  df <- rbind(df, hist)
  
  figure = ggplot() +
    geom_line(data = df,
              aes(
                x = year,
                y = diff,
                group = model,
                color = model
              ),
              size = 0.75) +
    geom_point(aes(x = 2021, y = 0), color = "black") +
    geom_point(
      data = medians,
      aes(x = year, y = median),
      color = "black",
      shape = 16,
      size = 2
    ) +
    scale_subpalette(subpalettes, "Emissions|CO2|Percent difference from No IRA") + 
    labs(title = title,
         x = "",
         y = yname) +
    theme_emf() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      panel.spacing.x = unit(4, "mm"),
      legend.position = gd
    ) +
    scale_x_continuous(breaks = c(2021, 2025, 2030, 2035))
  return(figure)
}
```

```{r Four Corners Function, include = FALSE}
ts_map_ID = 98
pd_map_ID = 26 
ad_map_ID = 4
drop = c("")
histsrc = "EPA-GHGI"

four_corners = function(ts_map_ID, pd_map_ID, ad_map_ID, drop, histsrc) {

  #Time Series Dataframe
      ts_df = data_from_graph(
    "time_series",
    config,
    clean_data,
    figmap_leep_timeseries,
    ts_map_ID,
    "United States"
  ) %>%
    filter(!model %in% drop) %>%
    filter(!datasrc %in% drop) %>%
    mutate(
      alpha = case_when(
        model == "USREP-ReEDS" ~ 1,
        model == "GCAM-PNNL" ~ 1,
        model == "IPM-EPA" ~ 1,
        scenario == "Historic" ~ 1,
        T ~ 0.6
      )
    ) %>%
    filter(year <= 2021 &
             model == histsrc |
             year >= 2021 & scenario != "Historic") %>%
    pivot_wider(names_from = year, values_from = value) %>%
    mutate(`2021` = case_when(T ~ `2021`[model == histsrc])) %>%
    pivot_longer(cols = starts_with("20"),
                 names_to = "year",
                 values_to = "value") %>%
    filter(!is.na(value)) %>%
    mutate(year = as.numeric(year))
      
        NOIRAfigure = ggplot(ts_df[ts_df$scenario == "No IRA",], aes(year,value, color = scenario, group = interaction(model, scenario))) + geom_line(aes(alpha = alpha), size = 0.5) +
    scale_subpalette(subpalettes, "Emissions|CO2|Energy|Demand|Industry") +
    theme_emf() +
    scale_x_continuous(breaks = c(2021, 2025, 2030, 2035)) +
    scale_alpha(range = c(0.5, 1), guide = F) + 
    labs(title = title, 
         x = element_blank(), 
         y = "Mt CO2") +
        theme(legend.position = "none",
          axis.text.x = element_text(angle = 45, hjust = 1))
    
    #Percent Difference
      
    pd_df = data_from_graph(
      "time_series",
      config,
      clean_data,
      figmap_leep_timeseries,
      pd_map_ID,
      "United States"
    ) %>%
    filter(!scenario == "No IRA") %>%
    filter(year > 2021) %>%
    filter(!model %in% drop) %>%
    filter(!datasrc %in% drop)
  
  pd_medians = pd_df %>%
    filter(year %in% c(2030, 2035)) %>%
    filter(value != 0) %>%
    group_by(year) %>% 
    summarize(median = median(value))
  
  hist <- pd_df %>%
    group_by(model) %>%
    slice(1) %>%
    mutate(scenario = "Historic",
           value = 0,
           year = 2021)
  
  pd_df <- rbind(pd_df, hist)
  
    figure = ggplot() +
    geom_line(data = pd_df, aes(
    x = year,
    y = value,
    group = model,
    color = model), 
    size = 0.75) + 
    geom_point(aes(x = 2021, y = 0), color = "black") + 
    geom_point(
      data = pd_medians,
      aes(x = year, y = median),
      color = "black",
      shape = 16,
      size = 2
    ) + 
    scale_subpalette(subpalettes, "Emissions|CO2|Percent difference from No IRA") + #Standard subpallete
    labs(title = title,
         x = "",
         y = "Percent Difference (%)") +
    theme_emf() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      panel.spacing.x = unit(4, "mm"),
      legend.position = "none"
    ) +
    scale_x_continuous(breaks = c(2021, 2025, 2030, 2035))
  
  
}

```

# Econ Wide
## Fig 1.2 FIN
```{r Economy-Wide Fig 1.2}
EconSpg = spg(
  99,
  "EPA-GHGI",
  expression(paste("Economy-Wide C", O[2])),
  expression(paste("Mt C", O[2], "/yr")),
  gd = "none",
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "Haiku-RFF"),
  0,
  7000,
  c(0, 2000, 4000, 6000),
  scales::comma) + 
  annotate("text", x = 2015, y = 4900, label = "Historic", color = "black") + 
  annotate("text", x = 2027.5, y = 5500, label = "No IRA", color = "#F28063") + 
  annotate("text", x = 2022, y = 3800, label = "IRA", color = "#0388B3")

EconTab = html(EconSpg$data, "Economy-Wide CO<sub>2<sub>")

ElecSpg = spg(
  98,
  "EPA-GHGI",
  expression(paste("Electricity C", O[2])),
  "",
  gd = "none",
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "Haiku-RFF"),
  0,
  7000,
  c(0, 2000, 4000, 6000),
  NULL)

ElecTab = html(ElecSpg$data, "Electricity CO<sub>2<sub>")

TranSpg = spg(
  19,
  "EPA-GHGI",
  expression(paste("Transportation C", O[2])),
  expression(paste("Mt C", O[2], "/yr")),
  gd = "none",
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "USREP-ReEDS"),
  0,
  2500,
  c(0, 1250, 2500),
  scales::comma)

TranTab = html(TranSpg$data, "Transportation CO<sub>2<sub>")

IndSpg = spg(
  21,
  "EPA-GHGI",
  expression(paste("Industry C", O[2])),
  "",
  gd = "none",
  c("IPM-NRDC", "IPM-EPA", "GCAM-PNNL"),
  0,
  2500,
  c(0, 1250, 2500),
  NULL)

IndTab = html(IndSpg$data, "Industry CO<sub>2<sub>")

BuilSpg = spg(
  23,
  "EPA-GHGI",
  expression(paste("Building C", O[2])),
  "",
  gd = "none",
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "MARKAL-NETL", "GCAM-PNNL"),
  0,
  2500,
  c(0, 1250, 2500),
  NULL)
BuilTab = html(BuilSpg$data, "Building CO<sub>2<sub>")

figure = (EconSpg | ElecSpg) / (TranSpg | BuilSpg | IndSpg) + 
  plot_annotation(tag_levels = list(c("", "", "Sectoral Emissions: Direct + Indirect from Electricity", "", ""))) & 
  theme(plot.tag.position = c(1.09, 1.1))



print(figure)

EconTab
ElecTab
TranTab
BuilTab
IndTab
```

## Fig1.3 FIN
```{r Economy-Wide Fig 1.3}
CoalSpg = spg(
  94,
  "EIA",
  expression(paste("Coal")),
  expression(paste("Quads")),
  gd = "none",
  c("RIO-REPEAT","EIAinEMF37.csv"),
  0,
  45,
  c(0, 10, 20 , 30 , 40),
  scales::comma)

CoalDot = dotted(CoalSpg$data, CoalSpg, "median", 0, 45)

CoalTab = html(CoalSpg$data, "Coal")

GasSpg = spg(
  93,
  "EIA",
  expression(paste("Gas")),
  "",
  gd = "none",
  c("RIO-REPEAT","EIAinEMF37.csv"),
  0,
  45,
  c(0, 10, 20 , 30 , 40),
  NULL)+
  annotate("text", x = 2010, y = 35, label = "Historic", color = "black") + 
  annotate("text", x = 2027.5, y = 35, label = "No IRA", color = "#F28063") + 
  annotate("text", x = 2022, y = 22.5, label = "IRA", color = "#0388B3")

GasDot = dotted(GasSpg$data, GasSpg, "median", 0, 45)

GasTab = html(GasSpg$data, "Gas")

PetrolSpg = spg(
  92,
  "EIA",
  expression(paste("Petroleum")),
  "",
  gd = "none",
  c("RIO-REPEAT","EIAinEMF37.csv"),
  0,
  45,
  c(0, 10, 20 , 30 , 40),
  NULL)

PetrolDot = dotted(PetrolSpg$data, PetrolSpg, "median", 0, 45)

PetrolTab = html(PetrolSpg$data, "Petroleum")

figure = (CoalDot | GasDot | PetrolDot) 



print(figure)
CoalTab
GasTab
PetrolTab
```

# Electricity
## Fig 2.1 FIN
```{r}
data <- clean_data %>%
  filter(model == "EPA-GHGI") %>%
  filter(year >= 2005) %>%
  filter(variable == "Emissions|CO2|Energy|Demand|Buildings|Commercial|Coal"|
         variable == "Emissions|CO2|Energy|Demand|Buildings|Commercial|Gas" |
         variable == "Emissions|CO2|Energy|Demand|Buildings|Commercial|Oil" |
         variable == "Emissions|CO2|Energy|Demand|Buildings|Residential|Coal" |
         variable == "Emissions|CO2|Energy|Demand|Buildings|Residential|Gas" |
         variable == "Emissions|CO2|Energy|Demand|Buildings|Residential|Oil" |
         variable == "Emissions|CO2|Energy|Demand|Industry|Coal" |
         variable == "Emissions|CO2|Energy|Demand|Industry|Gas" |
         variable == "Emissions|CO2|Energy|Demand|Industry|Oil" |
         variable == "Emissions|CO2|Energy|Demand|Transportation|Gas" |
         variable == "Emissions|CO2|Energy|Demand|Transportation|Oil" |
         variable == "Emissions|CO2|Energy|Supply|Electricity|Coal" |
         variable == "Emissions|CO2|Energy|Supply|Electricity|Gas" |
         variable == "Emissions|CO2|Energy|Supply|Electricity|Oil") %>%
  mutate(variable_rename = case_when(
    grepl("Demand", variable) ~ "Other Sectors",
    grepl("Coal", variable) ~ "Coal", 
    grepl("Gas", variable) ~ "Gas", 
    grepl("Oil", variable) ~ "Petroleum",
  )) %>%
  group_by(year, variable_rename) %>%
  summarise(value = sum(value)) %>%
  mutate(alpha = case_when(
    variable_rename == "Other Sectors" ~ 0.5, 
    T ~ 1))

data$variable_rename <- factor(data$variable_rename, level = c("Other Sectors", "Coal", "Gas", "Petroleum"))

fig = ggplot(data, aes(fill = variable_rename, y = value, alpha = alpha, x = year, color = variable_rename)) + 
  geom_bar(position = "stack", stat = "identity") + 
  theme_emf() +
  labs(title = "",
         x = "",
         y = expression(paste("Mt C", O[2], "/yr"))) +
    scale_y_continuous(limits = c(0, 6000), labels = scales::comma) +
    scale_x_continuous(breaks = c(2005, 2021)) + 
    theme(panel.spacing.x = unit(4, "mm"), legend.position = "bottom") +
    scale_alpha(range = c(0.6, 1), guide = F)+
  scale_color_manual(breaks = c( "Coal", "Gas", "Petroleum", "Other Sectors"), 
                     values = c( "#003052", "#BC8F73", "#733D3D", "#DEDEDE")) +
  scale_fill_manual(breaks = c( "Coal", "Gas", "Petroleum", "Other Sectors"), 
                     values = c( "#003052", "#BC8F73", "#733D3D", "#DEDEDE")) 

print(fig)
```
## Fig 2.3 FIN
```{r Electricity Fig 2.3}
ElecSpg = spg(
  98,
  "EPA-GHGI",
  "",
  expression(paste("Mt C", O[2], "/yr")),
  gd = "none",
  c("Scout-LEEP"),
  0,
  2500,
  c(0, 500, 1000, 1500, 2000, 2500),
  scales::comma) +
  annotate("text", x = 2015, y = 2250, label = "Historic", color = "black") + 
  annotate("text", x = 2027.5, y = 1750, label = "No IRA", color = "#F28063") + 
  annotate("text", x = 2023, y = 650, label = "IRA", color = "#0388B3")

ElecDot = dotted(ElecSpg$data, ElecSpg, "median", 0, 2500)

ElecTab = html(ElecSpg$data, "Electricity CO<sub>2<sub>")

print(ElecDot)
ElecTab
```
## Fig 2.4

# Transportation
## Fig 3.3 FIN
```{r}
TranSpg = spg(
  19,
  "EPA-GHGI",
  "",
  expression(paste("Mt C", O[2], "/yr")),
  gd = "none",
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "USREP-ReEDS"),
  0,
  2500,
  c(0, 500, 1000, 1500, 2000, 2500),
  scales::comma) + 
  annotate("text", x = 2015, y = 2000, label = "Historic", color = "black") + 
  annotate("text", x = 2030, y = 2100, label = "No IRA", color = "#F28063") + 
  annotate("text", x = 2025, y = 1250, label = "IRA", color = "#0388B3")

TranDot = dotted(TranSpg$data, TranSpg, "median", 0, 2500)

TranTab = html(TranSpg$data, "Transportation CO<sub>2<sub>")

print(TranDot)
TranTab
```
## Fig 3.5

# Building
## Fig 4.2 FIN
```{r}
TotSpg = spg(
  23,
  "EPA-GHGI",
  expression(paste("Total Building C", O[2])),
  expression(paste("Mt C", O[2], "/yr")),
  gd = "none",
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "MARKAL-NETL", "GCAM-PNNL"),
  0,
  2500,
  c(0, 500, 1000, 1500, 2000, 2500),
  scales::comma) + 
  annotate("text", x = 2015, y = 2250, label = "Historic", color = "black") + 
  annotate("text", x = 2030, y = 1675, label = "No IRA", color = "#F28063") + 
  annotate("text", x = 2022.5, y = 1000, label = "IRA", color = "#0388B3")

TotDot = dotted(TotSpg$data, TotSpg, "median", 0, 2500)

TotTab = html(TotSpg$data, "Total Building CO<sub>2<sub>")

DirSpg = spg(
  95,
  "EPA-GHGI",
  expression(paste("Direct Combustion")),
  expression(paste("Mt C", O[2], "/yr")),
  gd = "none",
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "MARKAL-NETL", "GCAM-PNNL"),
  0,
  2000,
  c(0, 500, 1000, 1500, 2000),

  scales::comma)

DirDot = dotted(DirSpg$data, DirSpg, "median", 0, 2000)

DirTab = html(DirSpg$data, "Direct Building CO<sub>2<sub>")

IndDirSpg = spg(
  22,
  "EPA-GHGI",
  expression(paste("Indirect from Electricity")),
  "",
  gd = "none",
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "MARKAL-NETL", "GCAM-PNNL"),
  0,
  2000,
  c(0, 500, 1000, 1500, 2000),
  NULL)

IndDirDot = dotted(IndDirSpg$data, IndDirSpg, "median", 0, 2000)

IndDirTab = html(IndDirSpg$data, "Indirect Building CO<sub>2<sub>")

figure = TotDot / (DirDot | IndDirDot)

TotTab
DirTab
IndDirTab
  
```
## Fig 4.3

# Industry
## Fig 5.2 FIN
```{r}
IndSpg = spg(
  21,
  "EPA-GHGI",
  "",
  expression(paste("Mt C", O[2], "/yr")),
  gd = "none",
  c("IPM-NRDC", "IPM-EPA", "GCAM-PNNL"),
  0,
  2500,
  c(0, 500, 1000, 1500, 2000, 2500),
  scales::comma) +
  annotate("text", x = 2015, y = 1550, label = "Historic", color = "black") + 
  annotate("text", x = 2030, y = 1575, label = "No IRA", color = "#F28063") + 
  annotate("text", x = 2020, y = 750, label = "IRA", color = "#0388B3")

IndDot = dotted(IndSpg$data, IndSpg, "median", 0, 2500)

IndTab = html(IndSpg$data, "Industry CO<sub>2<sub>")

print(IndDot)
IndTab
```

# Exec Summary
## Fig ES1 FIN
```{r}
ElecSpg = spg(
  98,
  "EPA-GHGI",
  "",
  expression(paste("Mt C", O[2], "/yr")),
  gd = "none",
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "Haiku-RFF"),
  0,
  2500,
  c(0, 500, 1000, 1500, 2000, 2500),
  scales::comma) +
  annotate("text", x = 2015, y = 2250, label = "Historic", color = "black") + 
  annotate("text", x = 2027.5, y = 1750, label = "No IRA", color = "#F28063") + 
  annotate("text", x = 2023, y = 650, label = "IRA", color = "#0388B3")

ElecDot = dotted(ElecSpg$data, ElecSpg, "median", 0, 2500)

ElecTab = html(ElecSpg$data, "Electricity CO<sub>2<sub>")

print(ElecDot)
ElecTab
```

## Fig ES2 FIN
```{r}
EconSpg = spg(
  99,
  "EPA-GHGI",
  expression(paste("Economy-Wide C", O[2])),
  expression(paste("Mt C", O[2], "/yr")),
  gd = "none",
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "Haiku-RFF"),
  0,
  7000,
  c(0, 2000, 4000, 6000),
  scales::comma) + 
  annotate("text", x = 2015, y = 4900, label = "Historic", color = "black") + 
  annotate("text", x = 2027.5, y = 5500, label = "No IRA", color = "#F28063") + 
  annotate("text", x = 2022, y = 3800, label = "IRA", color = "#0388B3")

EconTab = html(EconSpg$data, "Economy-Wide CO<sub>2<sub>")

TranSpg = spg(
  19,
  "EPA-GHGI",
  expression(paste("Transportation C", O[2])),
  expression(paste("Mt C", O[2], "/yr")),
  gd = "none",
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "USREP-ReEDS"),
  0,
  2500,
  c(0, 1250, 2500),
  scales::comma)

TranTab = html(TranSpg$data, "Transportation CO<sub>2<sub>")

IndSpg = spg(
  21,
  "EPA-GHGI",
  expression(paste("Industry C", O[2])),
  "",
  gd = "none",
  c("IPM-NRDC", "IPM-EPA", "GCAM-PNNL"),
  0,
  2500,
  c(0, 1250, 2500),
  NULL)

IndTab = html(IndSpg$data, "Industry CO<sub>2<sub>")

BuilSpg = spg(
  23,
  "EPA-GHGI",
  expression(paste("Building C", O[2])),
  "",
  gd = "none",
  c("IPM-NRDC", "IPM-EPA", "ReEDS-NREL", "Scout-LEEP", "MARKAL-NETL", "GCAM-PNNL"),
  0,
  2500,
  c(0, 1250, 2500),
  NULL)
BuilTab = html(BuilSpg$data, "Building CO<sub>2<sub>")

figure = (EconSpg) / (TranSpg | BuilSpg | IndSpg) + 
  plot_layout(heights = c(25, 15, 15,15), widths = c(9, 3.2, 2.9, 2.9)) +
  plot_annotation(tag_levels = list(c("", "Sectoral Emissions: Direct + Indirect from Electricity", "", ""))) & 
  theme(plot.tag.position = c(1.09, 1.1))

print(figure)

EconTab
TranTab
BuilTab
IndTab
```
## Fig ES3

# Appendix
## Economy-Wide Diff FIN
```{r EconWide Differnce}
EconPD = pd(25, "", "Percent Difference (%)", "none", "")
EconAD = ad(3, "", "Absolute Difference (Mt CO2)", "right", "")

figure = (EconPD | EconAD) + 
  plot_layout(guides = "collect")

print(figure)
```
## Electricity Diff FIN
```{r Electricity Differnce}
ElecPD = pd(26, "", "Percent Difference (%)", "none", "")
ElecAD = ad(4, "", "Absolute Difference (Mt CO2)", "right", "")

figure = (ElecPD | ElecAD) + 
  plot_layout(guides = "collect")

print(figure)
```
## Transportation Diff FIN
```{r Transportation Differnce}
TranPD = pd(27, "", "Percent Difference (%)", "none", "")
TranAD = ad(5, "", "Absolute Difference (Mt CO2)", "right", "")

figure = (TranPD | TranAD) + 
  plot_layout(guides = "collect")

print(figure)

test = TranSpg / (TranPD | TranAD) + 
  plot_layout(guides = "collect")

print(test)

#Note: final = (No IRA | IRA) / (TradAD | TranPD)
```
## Building Diff FIN
```{r Building Differnce}
BuilPD = pd(28, "", "Percent Difference (%)", "none", "")
BuilAD = ad(7, "", "Absolute Difference (Mt CO2)", "right", "")

figure = (BuilPD | BuilAD) + 
  plot_layout(guides = "collect")

print(figure)
```

## Industry Diff FIN
```{r Industry Differnce}
IndPD = pd(29, "", "Percent Difference (%)", "none", "")
IndAD = ad(6, "", "Absolute Difference (Mt CO2)", "right", "")

figure = (IndPD | IndAD) + 
  plot_layout(guides = "collect")

print(figure)
```

## Coal Emissions
## Gas
## Petrol

## ALL Generation
















