---
title: "Net Zero Performance"
output: 
  html_document:
    toc: true
    toc_depth: 5
    theme: cerulean
    toc_float: 
      collapsed: true
      smooth_scroll: true
params:
  mode: NULL
---

```{r setup, include=FALSE}
library(targets)
library(tarchetypes)
library(tidyverse)
library(here)
library(glue)
library(plotly)
library(data.table)
devtools::load_all(here())
knitr::opts_knit$set(root.dir = here::here())
knitr::opts_chunk$set(echo = FALSE)
```

```{r load data}
targets::tar_load(emf_data_long)
targets::tar_load(config)
```

### Joule Figure 1A scatter Plot ----

```{r}
var_list = list(x = "Final Energy|Percent Electricity",
             y = "Final Energy|Electricity|Percent of 2020")

df <- emf_data_long %>%
  filter(region == "United States") %>%
  filter(model %in% config$models_main) %>%
  filter(year == 2050 | (year == 2020 & scenario == "NT.Ref")) %>%
  filter(scenario %in% c("NT.Ref", "0by50.Ref","0by50.Adv")) %>%
  filter(variable %in% var_list) %>%
  select(-datasrc, -unit)

df_wide <- df %>%
  pivot_wider(names_from = variable,
              values_from = value)

df_2020 <- df_wide %>% filter(year == 2020)
df_2050 <- df_wide %>% filter(year == 2050)

data_list <- list(x = var_list$x,
             y = var_list$y,
             color = "scenario",
             shape = "model")

mapping_list = list(xlab = var_list$x,
                    ylab = var_list$y)

ggplot() +
    geom_point(data = df_2050, aes(x = .data[[data_list$x]], y = .data[[data_list$y]],
                      color = .data[[data_list$color]], shape = .data[[data_list$shape]]),
               size = 2) +
    geom_point(data = df_2020, aes(x = .data[[data_list$x]], y = .data[[data_list$y]],
                      shape = .data[[data_list$shape]]),
               size = 2.5, color = "orange") +
    labs(x = mapping_list$xlab,
         y = mapping_list$ylab,
         color = "") +
   # scale_subpalette(mapping_list$palettes, mapping_list$model_color_palette) +
    scale_y_continuous(labels = scales::comma)  +
    theme_emf() #+
    #theme(panel.spacing.x = unit(4, "mm"))
```

### Joule Figure 1B Scatter Plot ----

```{r}
var_list = list(x = "Emissions Intensity|CO2|Electricity",
             y = "Emissions|CO2|Percent difference from 2020")

df <- emf_data_long %>%
  filter(region == "United States") %>%
  filter(model %in% config$models_main) %>%
  filter(year == 2050 | (year == 2020 & scenario == "NT.Ref")) %>%
  filter(scenario %in% c("NT.Ref", "0by50.Ref","0by50.Adv")) %>%
  filter(variable %in% var_list) %>%
  select(-datasrc, -unit)

df_wide <- df %>%
  pivot_wider(names_from = variable,
              values_from = value)

df_2020 <- df_wide %>% filter(year == 2020)
df_2050 <- df_wide %>% filter(year == 2050)


data_list <- list(x = var_list$x,
             y = var_list$y,
             color = "scenario",
             shape = "model")

mapping_list = list(xlab = var_list$x,
                    ylab = var_list$y)

ggplot() +
    geom_point(data = df_2050, aes(x = .data[[data_list$x]], y = .data[[data_list$y]],
                      color = .data[[data_list$color]], shape = .data[[data_list$shape]]),
               size = 2) +
    geom_point(data = df_2020, aes(x = .data[[data_list$x]], y = .data[[data_list$y]],
                      shape = .data[[data_list$shape]]),
               size = 2.5, color = "orange") +
    labs(x = mapping_list$xlab,
         y = mapping_list$ylab,
         color = "") +
   # scale_subpalette(mapping_list$palettes, mapping_list$model_color_palette) +
    scale_y_continuous(labels = scales::comma)  +
    theme_emf() #+
    #theme(panel.spacing.x = unit(4, "mm"))
```

### Joule Figure 1C Scatter Plot ----

```{r}
var_list = list(x = "Final Energy|Per Capita",
             y = "Final Energy|Electricity|Percent of 2020")

df <- emf_data_long %>%
  filter(region == "United States") %>%
  filter(model %in% config$models_main) %>%
  filter(year == 2050 | (year == 2020 & scenario == "NT.Ref")) %>%
  filter(scenario %in% c("NT.Ref", "0by50.Ref","0by50.Adv")) %>%
  filter(variable %in% var_list) %>%
  select(-datasrc, -unit)

df_wide <- df %>%
  pivot_wider(names_from = variable,
              values_from = value)

df_2020 <- df_wide %>% filter(year == 2020)
df_2050 <- df_wide %>% filter(year == 2050)


data_list <- list(x = var_list$x,
             y = var_list$y,
             color = "scenario",
             shape = "model")

mapping_list = list(xlab = var_list$x,
                    ylab = var_list$y)

ggplot() +
    geom_point(data = df_2050, aes(x = .data[[data_list$x]], y = .data[[data_list$y]],
                      color = .data[[data_list$color]], shape = .data[[data_list$shape]]),
               size = 2) +
    geom_point(data = df_2020, aes(x = .data[[data_list$x]], y = .data[[data_list$y]],
                      shape = .data[[data_list$shape]]),
               size = 2.5, color = "orange") +
    labs(x = mapping_list$xlab,
         y = mapping_list$ylab,
         color = "") +
   # scale_subpalette(mapping_list$palettes, mapping_list$model_color_palette) +
    scale_y_continuous(labels = scales::comma)  +
    theme_emf() #+
    #theme(panel.spacing.x = unit(4, "mm"))
```

### Joule Figure 1D Scatter Plot ----

```{r}
var_list = list(x = "Primary Energy|Fossil|Percent difference from 2020",
             y = "Emissions|CO2|Percent difference from 2020")

df <- emf_data_long %>%
  filter(region == "United States") %>%
  filter(model %in% config$models_main) %>%
  filter(year == 2050 | (year == 2020 & scenario == "NT.Ref")) %>%
  filter(scenario %in% c("NT.Ref", "0by50.Ref","0by50.Adv")) %>%
  filter(variable %in% var_list) %>%
  select(-datasrc, -unit)

df_wide <- df %>%
  pivot_wider(names_from = variable,
              values_from = value)

df_2020 <- df_wide %>% filter(year == 2020)
df_2050 <- df_wide %>% filter(year == 2050)


data_list <- list(x = var_list$x,
             y = var_list$y,
             color = "scenario",
             shape = "model")

mapping_list = list(xlab = var_list$x,
                    ylab = var_list$y)

ggplot() +
    geom_point(data = df_2050, aes(x = .data[[data_list$x]], y = .data[[data_list$y]],
                      color = .data[[data_list$color]], shape = .data[[data_list$shape]]),
               size = 2) +
    geom_point(data = df_2020, aes(x = .data[[data_list$x]], y = .data[[data_list$y]],
                      shape = .data[[data_list$shape]]),
               size = 2.5, color = "orange") +
    labs(x = mapping_list$xlab,
         y = mapping_list$ylab,
         color = "") +
   # scale_subpalette(mapping_list$palettes, mapping_list$model_color_palette) +
    scale_y_continuous(labels = scales::comma)  +
    theme_emf() #+
    #theme(panel.spacing.x = unit(4, "mm"))
```


