---
title: "Net-Zero Stacked Bars"
output: 
  html_document:
    toc: true
    toc_depth: 5
    theme: cerulean
    toc_float: 
      collapsed: true
      smooth_scroll: true
params:
  mode: NULL
---

```{r setup, include=FALSE}
library(targets)
library(tarchetypes)
library(tidyverse)
library(here)
library(glue)
library(plotly)
library(data.table)
devtools::load_all(here())
knitr::opts_knit$set(root.dir = here::here())
knitr::opts_chunk$set(echo = FALSE)
```

```{r load data}
targets::tar_load(emf_data_long)
targets::tar_load(config)
targets::tar_load(overview_ref_sb_figmap)
```

```{r setup}
data_long <- left_join(overview_ref_sb_figmap, emf_data_long, by = "variable") %>%
  mutate(variable = variable_rename)

subpalettes = create_subpalettes(overview_ref_sb_figmap, config)
```

```{r ref data}
reference <- data_long %>% 
  filter(model == "GCAM" & year == 2020 & scenario == "NT.Ref" & region == "United States") %>%
  mutate(model = "2020") %>%
  mutate(type = "ref")
```

```{r NT Ref}
scen <- "NT.Ref"

modeled <- data_long %>% 
  filter(year == 2050 & scenario == scen) %>%
  mutate(type = "mod")

df <- rbind(reference,modeled)

modeled_plot <- ggplot() +
  geom_col(data = df %>% filter(type == "ref"),
           aes(x = model, y = value, fill = variable),
           position = "stack", color = "black", size = 1.5) +
  geom_col(data = df %>% filter(type == "mod"),
           aes(x = model, y = value, fill = variable),
           position = "stack") +
  theme_emf() +
  theme(axis.text.x = element_text(angle = 90, hjust=1)) +
  labs(title = scen,
       y="Mt CO2", x = "Model") +
  geom_hline(yintercept=0, color = "black", size=.75) +
  scale_subpalette(subpalettes, "CO2 Emissions")
modeled_plot

ggsave(paste("output/round1/overview_presentation/",scen,".png",sep=""),modeled_plot)
```

```{r 0by50 Ref}
scen <- "0by50.Ref"

modeled <- data_long %>% 
  filter(year == 2050 & scenario == scen) %>%
  mutate(type = "mod")

df <- rbind(reference,modeled)

modeled_plot <- ggplot() +
  geom_col(data = df %>% filter(type == "ref"),
           aes(x = model, y = value, fill = variable),
           position = "stack", color = "black", size = 1.5) +
  geom_col(data = df %>% filter(type == "mod"),
           aes(x = model, y = value, fill = variable),
           position = "stack") +
  theme_emf() +
  theme(axis.text.x = element_text(angle = 90, hjust=1)) +
  labs(title = scen,
       y="Mt CO2", x = "Model") +
  geom_hline(yintercept=0, color = "black", size=.75) +
  scale_subpalette(subpalettes, "CO2 Emissions") +
  scale_y_continuous(limits = c(-8000,8000))
modeled_plot

ggsave(paste("output/round1/overview_presentation/",scen,".png",sep=""),modeled_plot)
```

```{r 0by50 Adv}
scen <- "0by50.Adv"

modeled <- data_long %>% 
  filter(year == 2050 & scenario == scen) %>%
  mutate(type = "mod")

df <- rbind(reference,modeled)

modeled_plot <- ggplot() +
  geom_col(data = df %>% filter(type == "ref"),
           aes(x = model, y = value, fill = variable),
           position = "stack", color = "black", size = 1.5) +
  geom_col(data = df %>% filter(type == "mod"),
           aes(x = model, y = value, fill = variable),
           position = "stack") +
  theme_emf() +
  theme(axis.text.x = element_text(angle = 90, hjust=1)) +
  labs(title = scen,
       y="Mt CO2", x = "Model") +
  geom_hline(yintercept=0, color = "black", size=.75) +
  scale_subpalette(subpalettes, "CO2 Emissions") +
  scale_y_continuous(limits = c(-8000,8000))
modeled_plot

ggsave(paste("output/round1/overview_presentation/",scen,".png",sep=""),modeled_plot)
```

```{r 0by50 BSG Adv}
scen <- "0by50.BSG.Adv"

modeled <- data_long %>% 
  filter(year == 2050 & scenario == scen) %>%
  mutate(type = "mod")

df <- rbind(reference,modeled)

modeled_plot <- ggplot() +
  geom_col(data = df %>% filter(type == "ref"),
           aes(x = model, y = value, fill = variable),
           position = "stack", color = "black", size = 1.5) +
  geom_col(data = df %>% filter(type == "mod"),
           aes(x = model, y = value, fill = variable),
           position = "stack") +
  theme_emf() +
  theme(axis.text.x = element_text(angle = 90, hjust=1)) +
  labs(title = scen,
       y="Mt CO2", x = "Model") +
  geom_hline(yintercept=0, color = "black", size=.75) +
  scale_subpalette(subpalettes, "CO2 Emissions") +
  scale_y_continuous(limits = c(-8000,8000))
modeled_plot

ggsave(paste("output/round1/overview_presentation/",scen,".png",sep=""),modeled_plot)
```

```{r 0by50 CMSG}
scen <- "0by50.CMSG.Adv"

modeled <- data_long %>% 
  filter(year == 2050 & scenario == scen) %>%
  mutate(type = "mod")

df <- rbind(reference,modeled)

modeled_plot <- ggplot() +
  geom_col(data = df %>% filter(type == "ref"),
           aes(x = model, y = value, fill = variable),
           position = "stack", color = "black", size = 1.5) +
  geom_col(data = df %>% filter(type == "mod"),
           aes(x = model, y = value, fill = variable),
           position = "stack") +
  theme_emf() +
  theme(axis.text.x = element_text(angle = 90, hjust=1)) +
  labs(title = scen,
       y="Mt CO2", x = "Model") +
  geom_hline(yintercept=0, color = "black", size=.75) +
  scale_subpalette(subpalettes, "CO2 Emissions") +
  scale_y_continuous(limits = c(-8000,8000))
modeled_plot

ggsave(paste("output/round1/overview_presentation/",scen,".png",sep=""),modeled_plot)
```

```{r 0by50 ISG}
scen <- "0by50.ISG.Adv"

modeled <- data_long %>% 
  filter(year == 2050 & scenario == scen) %>%
  mutate(type = "mod")

df <- rbind(reference,modeled)

modeled_plot <- ggplot() +
  geom_col(data = df %>% filter(type == "ref"),
           aes(x = model, y = value, fill = variable),
           position = "stack", color = "black", size = 1.5) +
  geom_col(data = df %>% filter(type == "mod"),
           aes(x = model, y = value, fill = variable),
           position = "stack") +
  theme_emf() +
  theme(axis.text.x = element_text(angle = 90, hjust=1)) +
  labs(title = scen,
       y="Mt CO2", x = "Model") +
  geom_hline(yintercept=0, color = "black", size=.75) +
  scale_subpalette(subpalettes, "CO2 Emissions") +
  scale_y_continuous(limits = c(-8000,8000))
modeled_plot

ggsave(paste("output/round1/overview_presentation/",scen,".png",sep=""),modeled_plot)
```

```{r 0by50 TSG}
scen <- "0by50.TSG.Adv"

modeled <- data_long %>% 
  filter(year == 2050 & scenario == scen) %>%
  mutate(type = "mod")

df <- rbind(reference,modeled)

modeled_plot <- ggplot() +
  geom_col(data = df %>% filter(type == "ref"),
           aes(x = model, y = value, fill = variable),
           position = "stack", color = "black", size = 1.5) +
  geom_col(data = df %>% filter(type == "mod"),
           aes(x = model, y = value, fill = variable),
           position = "stack") +
  theme_emf() +
  theme(axis.text.x = element_text(angle = 90, hjust=1)) +
  labs(title = scen,
       y="Mt CO2", x = "Model") +
  geom_hline(yintercept=0, color = "black", size=.75) +
  scale_subpalette(subpalettes, "CO2 Emissions") +
  scale_y_continuous(limits = c(-8000,8000))
modeled_plot

ggsave(paste("output/round1/overview_presentation/",scen,".png",sep=""),modeled_plot)
```

## Faceted Plots

```{r 0by50 Ref and Adv}
scen <- c("0by50.Adv","0by50.Ref")

modeled <- data_long %>% 
  filter(year == 2050 & scenario %in% scen) %>%
  mutate(type = "mod")

df <- rbind(reference,modeled)

modeled_plot <- ggplot() +
  geom_col(data = df %>% filter(type == "ref"),
           aes(x = model, y = value, fill = variable),
           position = "stack", color = "black", size = 1.5) +
  geom_col(data = df %>% filter(type == "mod"),
           aes(x = model, y = value, fill = variable),
           position = "stack") +
  theme_emf() +
  theme(axis.text.x = element_text(angle = 90, hjust=1)) +
  labs(title = scen,
       y="Mt CO2", x = "Model") +
  geom_hline(yintercept=0, color = "black", size=.75) +
  facet_grid(~scenario) +
  scale_subpalette(subpalettes, "CO2 Emissions")
modeled_plot
```


