---
title: "Overview Presentation Figures"
author: "Ruying Gao"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 5
    theme: cerulean
    toc_float: 
      collapsed: true
      smooth_scroll: true
params:
  mode: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = here::here())
```

```{r, warning = FALSE}
if(is.null(params$mode)) {
  library(targets)
  library(tidyverse)
  library(here)
  library(glue)
  library(plotly)
  library(data.table)
  devtools::load_all(here())
}
```

# Part 0. Basic Setup 

Read in the necessary data

```{r data, include = TRUE}
tar_load(config)
stopifnot(exists("config"))

tar_load(emf_data_long)
stopifnot(exists("emf_data_long"))

tar_load(emf_summary_long)
stopifnot(exists("emf_summary_long"))
```

Note: There is no need for the user to change anything else if stacked bar, diff bar, and time series plots are all wanted

```{r file title, include = TRUE}
title  = "overview"
tar_load(overview_sb_presentation_figmap)
stopifnot(exists("overview_sb_presentation_figmap"))

tar_load(overview_db_presentation_figmap)
stopifnot(exists("overview_db_presentation_figmap"))

tar_load(overview_ts_presentation_figmap)
stopifnot(exists("overview_ts_presentation_figmap"))

tar_load(overview_cu_presentation_figmap)
stopifnot(exists("overview_cu_presentation_figmap"))
```

Set up file paths 

```{r file path setup, include = TRUE}
overall_path = paste("./output/round1/", title, "_presentation/", sep = "")
subfolders = c("", "stacked_bar", "diff_bar", "time_series", "cone_uncertainty")
create_folders(sapply(subfolders, function(x) {paste(overall_path, x, sep = "")}))
```


# Part I. Graphs: Stacked Bar, Diff Bar, and Time Series
 
```{r pre-processing and create graphs, echo=FALSE, include = TRUE}

graph_types_w_names = c("sb" = "stacked_bar", "db" = "diff_bar","ts" = "time_series", "cu" = "cone_uncertainty")
# graph_types_w_names = c("cu" = "cone_uncertainty")
for (i in 1:length(graph_types_w_names)) {
  
  # load the figure request figmaps
  plot_list <- get(paste(title, "_", names(graph_types_w_names)[i], "_presentation_figmap", sep = ""))
  
  # select the key variables, flip values, and merge with specific figure requests
  df <- preliminary_data_processing_for_plotting(emf_data_long, plot_list)
  
  # assign color palettes
  subpalettes = create_subpalettes(plot_list, config)
  
  # full processing based on figure requests + create pdf of plots 
  pdf_plots(overall_path, df, title, graph_types_w_names[i], subpalettes, config)
  
  # full processing based on figure requests + create png of plots
  png_plots(overall_path, df, title, graph_types_w_names[i], subpalettes, config)
}
```


