
# Themes

theme_emf <- function(fig_size = "auto") {

  if(fig_size == "auto") {
    theme <- theme_light() +
      theme(text = element_text(size = 12),
            legend.background = element_rect(fill="white",color=NA),
            legend.title=element_blank(),
            legend.position="right",
            plot.margin = margin(8,10,8,8),
            axis.text.y = element_text(size=11),
            axis.text.x = element_text(size=9),
            axis.title.y = element_text(face="bold",vjust=2),
            strip.text.x = element_text(size = 10, color = "black"),
            strip.text.y = element_text(size = 9, color = "black"),
            strip.background = element_rect(fill="#C5CFE3", size=1))
  }
  else if(fig_size == "small") {
    theme <- theme_light() +
      theme(text = element_text(size = 11),
            plot.subtitle = element_text(face="bold",size = 10,hjust=0.5),
            axis.text.y = element_text(size=10),
            axis.title.y = element_text(size=10,face="bold",vjust=2))
    theme
  }}

xup <- theme(axis.text.x = element_text(vjust = 12))
xup_light <- theme(axis.text.x = element_text(vjust = 10))
slantx <- theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 9))
bottom1 <- theme(legend.position = "bottom", legend.title = element_blank())
nolegend <- theme(legend.position='none')

# Color Palette

master_palette <- c(
  "very dark blue" = "#003052",
  "light orange" = "#FDD56D",
  "very dark teal" = "#2A4849",
  "dark salmon" = "#E6544D",
  "purple" = "#8F507F",
  "dark gray blue" = "#595764",
  "teal blue" = "#0388B3",
  "teal green" = "#2EAD96",
  "very dark olive" = "#414833",
  "light salmon" = "#F28063",
  "dark cobalt" = "#442F91",
  "cerulean blue" = "#2b59c3",
  "dark cornflower" = "#253c78",
  "cinnamon" = "#d36582",
  "cream" = "#ffeecf",
  "light brown" = "#c9a690",
  "mauve" = "#6d2e46",
  "copper" = "#a26769",
  "gray pink" = "#d5b9b2",
  "dark gray pink" = "#AF8D84",
  "darkest gray pink" = "#80665F",
  "gray green" = "#5f7470",
  "aqua" = "#2ab7ca",
  "black" = "#000000",
  "m.teal" = "#148896",
  "m.blue" = "#044980",
  "m.green" = "#149664",
  "dark m.green" = "#02643E",
  "m.red" = "#E51A32",
  "m.orange" = "#E5671A",
  "m.pink" = "#E51A98",
  "m.yellow" = "#DAC125",
  "dark m.yellow" = "#DAAB25",
  "m.neongreen" = "#99DA25",
  "m.burnorange" = "#DA6625",
  "m.indigo" = "#7539C6",
  "m.violet" = "#BC39C6",
  "m.cobalt" = "#3943C6",
  "light blue" = "#9CA3F9",
  "brown" = "#BC8F73",
  "dark brown" = "#825335",
  "slate" = "#767684",
  "dark slate" = "#36363B",
  "brown red" = "#733D3D",
  "dark brown red" = "#481B1B",
  "light purple" = "#B390B6",
  "dark gray" = "#363636",
  "dark gray red" = "#6B5050",
  "dark gray purple" = "#66506B",
  "dark gray green" = "#506B5E",
  "dark gray blue" = "#505A6B",
  "dark gray yellow" = "#686B50",
  "mid gray" = "#676767",
  "mid gray red" = "#723535",
  "mid gray purple" = "#653572",
  "mid gray green" = "#357238",
  "mid gray blue" = "#353B72",
  "mid gray yellow" = "#6F7235",
  "bright yellow" = "#FFF362",
  "darker yellow" = "#FFEB00",
  "dark dark yellow" = "#D5C500",
  "darkest yellow" = "#AA9C00",
  "bright purple" = "#C788FF",
  "darker purple" = "#A761E5",
  "dark dark purple" = "#6A23A7",
  "darkest purple" = "#450081",
  "bright green" = "#75FF8E",
  "darker green" = "#3CE259",
  "dark dark green" = "#16B231",
  "darkest green" = "#007515",
  "bright blue" = "#74A3FF",
  "darker blue" = "#477ADD",
  "dark dark blue" = "#1F4FAB",
  "darkest blue" = "#002A7B",
  "hue1" = "#4E5357",
  "hue2" = "#5B7C93",
  "hue3" = "#5A9DCB",
  "hue4" = "#40A4EA",
  "hue5" = "#0097FF")

# Color Mapping - labels matched to hex codes

color_map <- c(
  # scenarios
  ## no target
  "NT.Ref" = "dark gray",
  "NT.Adv" = "dark gray red",
  "NT.BSG.Adv" = "dark gray purple",
  "NT.ISG.Adv" = "dark gray green",
  "NT.TSG.Adv" = "dark gray blue",
  "NT.CMSG.Adv" = "dark gray yellow",
  ## 0by50
  "0by50.Ref" = "mid gray",
  "0by50.Adv" = "mid gray red",
  "0by50.BSG.Adv" = "mid gray purple",
  "0by50.ISG.Adv" = "mid gray green",
  "0by50.TSG.Adv" = "mid gray blue",
  "0by50.CMSG.Adv" = "mid gray yellow",
  ### CMSG
  "0by50.CMSG1" = "bright yellow",
  "0by50.CMSG2" = "darker yellow",
  "0by50.CMSG3" = "dark dark yellow",
  "0by50.CMSG4" = "darkest yellow",
  ### ISG
  "0by50.ISG1" = "bright green",
  "0by50.ISG2" = "darker green",
  "0by50.ISG3" = "dark dark green",
  "0by50.ISG4" = "darkest green",
  ### TSG
  "0by50.TSG1" = "bright blue",
  "0by50.TSG2" = "darker blue",
  "0by50.TSG3" = "dark dark blue",
  "0by50.TSG4" = "darkest blue",
  ### BSG
  "0by50.BSG1" = "bright purple",
  "0by50.BSG2" = "dark dark purple",
  ## 0GHGby50
  "0GHGby50.Ref" = "mid gray",
  "0GHGby50.Adv" = "mid gray red",
  ## 0by60
  "0by60.Ref" = "mid gray",
  "0by60.Adv" = "mid gray red",
  "0by60.CMSG2" = "darker yellow",
  "0by60.CMSG3" = "dark dark yellow",
  "0by60.CMSG4" = "darkest yellow",
  ## 0by80
  "0by80.Ref" = "mid gray",
  "0by80.Adv" = "mid gray red",
  "0by80.CMSG2" = "darker yellow",
  "0by80.CMSG3" = "dark dark yellow",
  "0by80.CMSG4" = "darkest yellow",

  # models
  "ADAGE" = "m.teal",
  "AEO2020" = "black",
  "AEO2021" = "black",
  "AnyMOD" = "dark gray blue",
  "CTUS-NEMS" = "m.green",
  "EC-MSMR" = "m.cobalt",
  "ENERGY2020" = "purple",
  "EIA_Historic" = "black",
  "EIA_STEO" = "black",
  "EPA_GHGI" = "black",
  "EPA-TIMES" = "m.red",
  "EPS" = "m.yellow",
  "FARM" = "m.pink",
  "GCAM" = "copper",
  "GCAM-USA" = "m.burnorange",
  "gTech" = "light purple",
  "MA3T" = "bright purple",
  "MARKAL-NETL" = "m.violet",
  "MER" = "black",
  "NATEM" = "light blue",
  "Pathways" = "bright green",
  "ReEDS" = "darkest yellow",
  "RIO" = "darker purple",
  "Scout" = "teal green",
  "TEMPO" = "bright blue",
  "TEMOA" = "pink",
  "US-REGEN" = "m.neongreen",
  "USREP-ReEDS" = "bright yellow",

  # fuels
  "Fossil" = "very dark blue",
  "Biogas" = "teal green",
  "Biomass" = "m.violet",
  "Biomass Liquids" = "m.violet",
  "Biomass Solids" = "m.indigo",
  "Coal" = "slate",
  "Gas" = "brown",
  "Oil" = "brown red",
  "Solar" = "m.yellow",
  "Wind" = "m.green",
  "Hydro" = "m.cobalt",
  "Geothermal" = "#E01616",
  "Ocean" = "m.blue",
  "Nuclear" = "#E01616",
  "Storage" = "gray pink",
  "Battery" = "bright green",
  "PSH" = "very dark blue",
  "Total Solar" = "m.yellow",
  "Solar from CSP" = "very dark blue",
  "Solar from PV" = "m.violet",
  "Total Wind" = "m.green",
  "Offshore Wind" = "very dark blue",
  "Onshore Wind" = "m.violet",
  "Peak summer electricity load" = "very dark blue",
  "Peak winter electricity load" = "m.violet",


  # technology
  "Fossil w/ CCS" = "dark cobalt",
  "Fossil w/o CCS" = "dark gray blue",
  "Biomass w/o CCS" = "m.indigo",
  "Biomass w/ CCS" = "m.violet",
  "Coal w/ CCS" = "slate",
  "Coal w/o CCS" = "dark slate",
  "Gas w/ CCS" = "brown",
  "Gas w/o CCS" = "dark brown",
  "Oil w/ CCS" = "brown red",
  "Oil w/o CCS" = "dark brown red",
  "Solar CSP" = "dark m.yellow",
  "Solar PV" = "m.yellow",
  "Storage Battery" = "gray pink",
  "Storage PSH" = "dark gray pink",
  "Storage Other" = "darkest gray pink",
  "Wind Offshore" = "m.green",
  "Wind Onshore" = "dark m.green",
  "Other" = "light purple",

  "Electrolysis" = "teal blue",
  "Ethanol" = "cinnamon",
  "Photoelectrochemical" = "dark m.yellow",

  "Renewables" = "teal green",
  "Electricity" = "teal blue",
  "Hydrogen" = "m.burnorange",
  "Non-Fossil Combustion" = "#EA9C9C",
  "Biomass and H2" = "teal green",
  "Synthetic Gas" = "cinnamon",
  "Synthetic Liquids" = "copper",
  "Synthetic Fuels" = "copper",

  "Fuel Cell" = "teal green",
  "NG Blend" = "cinnamon",

  "Biomass gassification w/ CCS" = "dark cobalt",
  "Biomass gassification w/o CCS" = "dark gray blue",
  "Coal gassification to hydrogen plants w/ CCS" = "m.indigo",
  "Hydrogen-by-electrolysis plants" = "m.violet",
  "Ethanol SMR w/o CCS" = "slate",
  "Gas SMR w/ CCS" = "gray pink",
  "Gas SMR w/o CCS" = "brown",
  "Photoelectrochemical w/o CCS" = "dark brown",
  "Thermochemical w/o CCS" = "m.yellow",

  #sectors
  "AFOLU" = "m.green",
  "LULUCF" = "dark dark green",
  "Biofeedstock" = "teal green",
  "Biofuels" = "teal green",
  "BECCS" = "m.violet",
  "Chemical Feedstocks" = "very dark teal",
  "Refining" = "very dark teal",
  "Petroleum Refining" = "slate",
  "Industrial Processes" = "slate",
  "Energy" = "teal blue",
  "Energy & Industrial Processes" = "teal blue",
  "Buildings" = "light orange",
  "Transportation" = "dark salmon",
  "Industry" = "m.green",
  "Heat" = "m.red",
  "Energy Supply (pos)" = "m.violet",
  "Energy Supply (neg)" = "teal green",
  "Final Energy" = "m.violet",
  "Primary Energy" = "black",
  "Residential" = "teal blue",
  "Commercial" = "light orange",
  "EInt Mfg" = "light orange",
  "NonEInt Mfg" = "teal blue",
  "Non Mfg" = "m.green",

  #emissions accounting
  "Net CO2" = "very dark teal",
  "Gross Positive CO2" = "dark salmon",
  "CO2 + Fossil CCS" = "light orange",
  "BECCS (neg)" = "teal green",
  "BECCS + LULUCF (neg)" = "dark dark green",
  "BECCS + LULUCF + DAC (neg)" = "darkest green",

  # transportation,
  "Freight" = "m.red",
  "Offroad" = "teal green",
  "Passenger" = "teal blue",
  "Pipeline" = "very dark teal",
  "Aviation" = "light orange",
  "Rail" = "dark salmon",
  "Road" = "m.indigo",
  "Shipping" = "m.green",
  "Diesel" = "dark m.yellow",
  "Gasoline" = "m.neongreen",
  "Jet Fuel" = "m.burnorange",

  # emissions
  "Direct" = "teal blue",
  "Indirect" = "teal green",
  "*Indirect" = "teal green",
  "CO2" =  "teal blue",
  "Non-CO2" = "dark salmon",
  "CH4" = "teal blue",
  "Non-CO2" = "dark salmon",
  "F-Gases" = "light orange",
  "Land Sink"= "teal green",
  "CDR" = "very dark blue",
  "DAC" = "very dark blue",
  "Net-GHG" = "#B2B3BD",

  # welfare
  "Welfare" = "teal blue",
  "Quintile 1" = "hue1",
  "Quintile 2" = "hue2",
  "Quintile 3" = "hue3",
  "Quintile 4" = "hue4",
  "Quintile 5" = "hue5") %>%
  find_color(master_palette)

sub_palettes <- list(
  `test` = c("ADAGE"  = "ADAGE" ,
                    "AnyMOD" = "AnyMOD",
                    "CTUS-NEMS" = "CTUS-NEMS",
                    "EPA-TIMES" = "EPA-TIMES",
                    "EPS" = "EPS",
                    "FARM" = "FARM",
                    "GCAM" = "GCAM",
                    "GCAM-USA" = "GCAM-USA",
                    "gTech" = "gTech",
                    "MARKAL-NETL" = "MARKAL-NETL",
                    "NATEM" = "NATEM",
                    "TEMPO" = "TEMPO",
                    "US-REGEN" = "US-REGEN")
) %>%
  map(~find_color(.x, color_map))


